In [1]:
import math
import os
import pandas as pd
import numpy as np

In [2]:
#calculate passage number when I ran out of passage 5 vials ;;
def passage_number(time):
    base_vial = 6
    if time > 2:
        base_vial = base_vial-1 
    pnum = base_vial + (3 * time)
    return pnum



def well_namer(row, col):
    well_name = str(chr(ord('@')+ row)) + str(col).rjust(2, '0')  #make the number have a left align, adding a zero
    return well_name

import re

def extract_number(string):
    match = re.search(r'\d+', string)
    if match:
        return int(match.group())
    else:
        return None

In [3]:
#Get 96-well plate CSV file from benchiling/Notion NOTE: don't initialze an empty df, use a list and convert after.

plate_path = 'plate_metadata/' #'/home/mattiazzilab/Documents/Allie_Scripts/May 8 seeding.csv'

export_path = 'plate_metadata/'#'/mnt/bigdisk1/Allie_S/Replicative_Age_Project/Data Mining/metadata/'

def load_plate_df(path):    
    raw_plate_df = pd.read_csv(path, header=0, usecols=range(1,13)).dropna(axis=1,how='all')
    plate_df = raw_plate_df.dropna(axis=0, thresh=2)
    print(plate_df.shape) #Checks if correct number of rows and columns
    
    return plate_df

def make_map_df():
    '''
    Return a df with the required columns
    '''
    plate_map_df = pd.DataFrame(columns = ['Metadata_Well', 'Metadata_WellRow', 'Metadata_WellColumn', 'Metadata_Field',
                                'TimepointName', 'SerialPassage_BatchNumber', 'AgeGroup', 'PassageNumber', 'Staining', 'Drug'])
    print(plate_map_df.columns)
    return plate_map_df
#plate_df.head(13)
#print(columns_row)

In [4]:
def export_platemap_csv(plate_df, export_path):
    plate_map_df = make_map_df()
    columns_row = plate_df.columns#get_columns_row(plate_df)
    for index,data in plate_df.iterrows():
        row = data.to_list()
        for count,value in enumerate(row):
            curr_well = value
            if pd.isna(curr_well):
                continue
            row_list = []
            # get string data and label of row in df (e.g. col1, text= R1T0 EAA1-488 Tfn-647)
            # regex to separate into different variables
            # then add them to dict with their respective col index (label) and index of the row in the column (column.index)
            for i in range(40):
                
                row_entry = {}
                
                row_index = index+1  #Make it 1-indexed
                
                column_index = columns_row[count]  # Use header row for column index
                #print(column_index)
            
                if ~np.isnan(row_index): 
                    well_name = well_namer(row_index, column_index)
                else:
                    well_name = 'Empty'
                    continue
                
                #seperate well metadata by space
                text = curr_well.split(' ')
                
                #use regex to extract the numerical bits
                serial_passage_batch = extract_number(text[0])
                age_group = extract_number(text[1]) #time used to mean age group - deprecated term but still used in code
                passage_num = extract_number(text[2]) #passage_number(Int(time)) - use the function if you don;t have passage number in the table
                
                #grab drug, name and stains
                if '_' in text[1]: #if there is an underscore than the well is drug-treated for this group
                    drug = text[1].split('_')[1] #grab the drug name past the underscore
                else:
                    drug = 'None'
                
                name = text[0] + ' ' + text[1] + ' ' + text[2]
                stains = ' '.join(text[3:len(text)]) #Use if 3 passage number is in the table values
                
                field = i+1 #information for the field is just 1-40, nothing else changes

                print(name, serial_passage_batch, age_group, passage_num, field, stains, drug, sep=',') 
        
                row_entry.update({'Metadata_Well': well_name, 'Metadata_WellRow': row_index, 'Metadata_WellColumn': column_index, 'Metadata_Field': field,
                                'TimepointName':name, 'SerialPassage_BatchNumber': serial_passage_batch, 'AgeGroup': age_group, 'PassageNumber': passage_num, 'Staining': stains, 'Drug': drug })

                row_list.append(row_entry)
                
            rows = pd.DataFrame(row_list)
            plate_map_df = pd.concat([plate_map_df, rows],ignore_index=True)
            #column_index = column_index+1
    plate_map_df.to_csv(os.path.join(export_path,'map.csv'), index=False)

In [5]:
for root, dirs, files in os.walk(plate_path):
    for filename in files:
        if filename.endswith(".csv") and "map" not in filename:
            file_path = os.path.join(root,filename)
            plate_df = load_plate_df(os.path.abspath(file_path))
            display(plate_df)
            export_path = os.path.abspath(root)
            print(f"Exporting {filename} to {export_path}")
            export_platemap_csv(plate_df, export_path)

(6, 12)

,1,2,3,4,5,6,7,8,9,10,11,12
1,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG6 P25 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG5 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG3 P16 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG2 P14 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG0 P7 LAMP1-488 + MitoRed + Phalloidin-647,SPB11 AG0 P7 p16INK4A-594 1:800 + Phalloidin-647,SPB5 AG3_Doxo P16 p16INK4A-594 1:800 + Phalloi...
2,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG6 P25 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG5 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG3 P16 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG2 P14 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG0 P7 LAMP1-488 + MitoRed + Phalloidin-647,SPB11 AG0 P7 p16INK4A-594 1:1600 + Phalloidin-647,SPB5 AG3_Doxo P16 p16INK4A-594 1:1600 + Phallo...
3,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG6 P25 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG5 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG3 P16 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG2 P14 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG0 P7 LAMP1-488 + MitoRed + Phalloidin-647,SPB11 AG0 P7 p16INK4A-594 1:2600 + Phalloidin-647,SPB5 AG3_Doxo P16 p16INK4A-594 1:2600 + Phallo...
4,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG6 P25 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG5 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG3 P16 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG2 P14 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG0 P7 LAMP1-488 + MitoRed + Phalloidin-647,SPB11 AG0 P7 p16INK4A-594 1:3600 + Phalloidin-647,SPB5 AG3_Doxo P16 p16INK4A-594 1:3600 + Phallo...
5,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG6 P25 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG5 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG3 P16 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG2 P14 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG0 P7 LAMP1-488 + MitoRed + Phalloidin-647,SPB11 AG0 P7 p16INK4A-594 1:3600 LMNB1 1:400 +...,SPB5 AG3_Doxo P16 p16INK4A-594 1:3600 LMNB1 1:...
6,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG6 P25 LAMP1-488 + MitoRed + Phalloidin-647,SPB5 AG5 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG3 P16 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG2 P14 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG0 P7 LAMP1-488 + MitoRed + Phalloidin-647,SPB11 AG0 P7 p21-594 1:6000 + Phalloidin-647,SPB5 AG3_Doxo P16 p21-594 1:600 + Phalloidin-647

Exporting mar28plate.csv to /Users/allielas/HTP_fibroblasts_mitolyso/plate_metadata/20250328_rep05_metadata
Index(['Metadata_Well', 'Metadata_WellRow', 'Metadata_WellColumn',
       'Metadata_Field', 'TimepointName', 'SerialPassage_BatchNumber',
       'AgeGroup', 'PassageNumber', 'Staining', 'Drug'],
      dtype='object')
SPB8 AG3_Doxo P16,8,3,16,1,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,2,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,3,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,4,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,5,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,6,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,7,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,8,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,9,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,10,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,11,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,12,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,13,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,14,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,15,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,16,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,17,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,18,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,19,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,20,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,21,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,22,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,23,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,24,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,25,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,26,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,27,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,28,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,29,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,30,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,31,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,32,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,33,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,34,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,35,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,36,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,37,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,38,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,39,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,40,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB2 AG8 P29,2,8,29,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG8 P29,2,8,29,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG7 P27,4,7,27,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG6 P25,5,6,25,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB5 AG5 P22,5,5,22,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG3 P16,8,3,16,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG2 P14,9,2,14,20,LAMP1-488 + MitoRed + Phalloidin-647,None

,2,3,4,5,6,7,8,9,10,11
1,SPB2 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG2 P12 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB6 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG4 P17 EEA1-488 + ConA-594 + Tfn-647,SPB3 AG3 EEA1-488 + ConA-594 + Tfn-647,SPB4 AG2 EEA1-488 + ConA-594 + Tfn-647,SPB5 AG1 EEA1-488 + ConA-594 + Tfn-647,SPB6 AG0 EEA1-488 + ConA-594 + Tfn-647
2,SPB2 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG2 P12 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB6 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG4 P17 EEA1-488 + ConA-594 + Tfn-647,SPB3 AG3 EEA1-488 + ConA-594 + Tfn-647,SPB4 AG2 EEA1-488 + ConA-594 + Tfn-647,SPB5 AG1 EEA1-488 + ConA-594 + Tfn-647,SPB6 AG0 EEA1-488 + ConA-594 + Tfn-647
3,SPB2 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG2 P12 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB6 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG4 P17 EEA1-488 + ConA-594 + Tfn-647,SPB3 AG3 EEA1-488 + ConA-594 + Tfn-647,SPB4 AG2 EEA1-488 + ConA-594 + Tfn-647,SPB5 AG1 EEA1-488 + ConA-594 + Tfn-647,SPB6 AG0 EEA1-488 + ConA-594 + Tfn-647
4,SPB2 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG2 P12 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB6 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG4 P17 EEA1-488 + ConA-594 + Tfn-647 + IKA,SPB3 AG3 EEA1-488 + ConA-594 + Tfn-647+ IKA,SPB4 AG2 EEA1-488 + ConA-594 + Tfn-647+ IKA,SPB5 AG1 EEA1-488 + ConA-594 + Tfn-647+ IKA,SPB6 AG0 EEA1-488 + ConA-594 + Tfn-647+ IKA
5,SPB2 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG2 P12 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB6 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG4 P17 EEA1-488 + Tfn-568 + WGA-CF640R,SPB3 AG3 EEA1-488 + Tfn-568 + WGA-CF640R,SPB4 AG2 EEA1-488 + Tfn-568 + WGA-CF640R,SPB5 AG1 EEA1-488 + Tfn-568 + WGA-CF640R,SPB6 AG0 EEA1-488 + Tfn-568 + WGA-CF640R
6,SPB1 AG5 P20 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG5 P20 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG5 P20 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG5 P20 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG5 P20 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG5 P20 EEA1-488 + ConA-594 + Tfn-647,SPB1 AG5 P20 EEA1-488 + ConA-594 + Tfn-647,SPB1 AG5 P20 EEA1-488 + ConA-594 + Tfn-647,SPB1 AG5 P20 EEA1-488 + ConA-594 + Tfn-647,SPB1 AG5 P20 EEA1-488 + ConA-594 + Tfn-647

Exporting mar26plate.csv to /Users/allielas/HTP_fibroblasts_mitolyso/plate_metadata/20240326_rep02_metadata
Index(['Metadata_Well', 'Metadata_WellRow', 'Metadata_WellColumn',
       'Metadata_Field', 'TimepointName', 'SerialPassage_BatchNumber',
       'AgeGroup', 'PassageNumber', 'Staining', 'Drug'],
      dtype='object')
SPB2 AG4 P17,2,4,17,1,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,2,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,3,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,4,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,5,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,6,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,7,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,8,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,9,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,10,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,11,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,12,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,13,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,14,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,15,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,16,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,17,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,18,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,19,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,20,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,21,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,22,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,23,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,24,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,25,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,26,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,27,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,28,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,29,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,30,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,31,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,32,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,33,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,34,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,35,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,36,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,37,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,38,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,39,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,40,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,1,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,2,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,3,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,4,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,5,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,6,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,7,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,8,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,9,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,10,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,11,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,12,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,13,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,14,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,15,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,16,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,17,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,18,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,19,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,20,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,21,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,22,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,23,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,24,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,25,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,26,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,27,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,28,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,29,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,30,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,31,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,32,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,33,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,34,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,35,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,36,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,37,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,38,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,39,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG3 P14,3,3,14,40,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,1,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,2,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,3,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,4,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,5,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,6,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,7,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,8,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,9,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,10,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,11,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,12,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,13,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,14,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,15,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,16,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,17,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,18,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,19,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,20,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,21,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,22,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,23,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,24,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,25,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,26,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,27,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,28,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,29,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,30,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,31,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,32,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,33,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,34,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,35,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,36,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,37,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,38,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,39,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG2 P12,4,2,12,40,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,1,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,2,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,3,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,4,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,5,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,6,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,7,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,8,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,9,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,10,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,11,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,12,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,13,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,14,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,15,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,16,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,17,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,18,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,19,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,20,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,21,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,22,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,23,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,24,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,25,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,26,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,27,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,28,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,29,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,30,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,31,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,32,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,33,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,34,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,35,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,36,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,37,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,38,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,39,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG1 P9,5,1,9,40,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,1,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,2,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,3,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,4,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,5,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,6,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,7,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,8,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,9,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,10,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,11,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,12,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,13,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,14,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,15,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,16,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,17,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,18,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,19,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,20,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,21,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,22,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,23,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,24,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,25,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,26,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,27,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,28,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,29,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,30,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,31,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,32,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,33,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,34,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,35,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,36,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,37,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,38,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,39,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB6 AG0 P6,6,0,6,40,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG4 P17,2,4,17,1,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,2,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,3,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,4,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,5,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,6,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,7,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,8,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,9,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,10,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,11,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,12,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,13,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,14,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,15,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,16,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,17,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,18,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,19,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,20,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,21,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,22,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,23,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,24,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,25,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,26,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,27,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,28,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,29,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,30,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,31,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,32,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,33,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,34,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,35,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,36,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,37,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,38,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,39,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG4 P17,2,4,17,40,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,1,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,2,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,3,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,4,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,5,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,6,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,7,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,8,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,9,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,10,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,11,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,12,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,13,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,14,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,15,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,16,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,17,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,18,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,19,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,20,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,21,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,22,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,23,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,24,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,25,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,26,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,27,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,28,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,29,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,30,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,31,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,32,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,33,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,34,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,35,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,36,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,37,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,38,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,39,+ ConA-594 + Tfn-647,None
SPB3 AG3 EEA1-488,3,3,1,40,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,1,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,2,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,3,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,4,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,5,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,6,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,7,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,8,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,9,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,10,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,11,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,12,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,13,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,14,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,15,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,16,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,17,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,18,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,19,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,20,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,21,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,22,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,23,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,24,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,25,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,26,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,27,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,28,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,29,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,30,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,31,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,32,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,33,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,34,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,35,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,36,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,37,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,38,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,39,+ ConA-594 + Tfn-647,None
SPB4 AG2 EEA1-488,4,2,1,40,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,1,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,2,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,3,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,4,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,5,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,6,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,7,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,8,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,9,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,10,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,11,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,12,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,13,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,14,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,15,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,16,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,17,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,18,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,19,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,20,+ ConA-594 + Tfn-647,None
SPB5 AG1 EEA1-488,5,1,1,21,+ ConA-594 + Tfn-647,None

,2,3,4,5,6,7,8,10,11
1,SPB2 AG6 P24 LAMP1-488 + MitoRed,SPB3 AG5 P20 LAMP1-488 + MitoRed,SPB6 AG4 P18 LAMP1-488 + MitoRed,SPB7 AG3 P16 LAMP1-488 + MitoRed,SPB8 AG2 P12 LAMP1-488 + MitoRed,SPB9 AG1 P10 LAMP1-488 + MitoRed,SPB10 AG0 P7 LAMP1-488 + MitoRed,SPB9 AG1 P10 p21-488,SPB2 AG6 P24 p21-488
2,SPB2 AG6 P24 LAMP1-488 + MitoRed,SPB3 AG5 P20 LAMP1-488 + MitoRed,SPB6 AG4 P18 LAMP1-488 + MitoRed,SPB7 AG3 P16 LAMP1-488 + MitoRed,SPB8 AG2 P12 LAMP1-488 + MitoRed,SPB9 AG1 P10 LAMP1-488 + MitoRed,SPB10 AG0 P7 LAMP1-488 + MitoRed,SPB9 AG1 P10 p21-488,SPB2 AG6 P24 p21-488
3,SPB2 AG6 P24 LAMP1-488 + MitoRed,SPB3 AG5 P20 LAMP1-488 + MitoRed,SPB6 AG4 P18 LAMP1-488 + MitoRed,SPB7 AG3 P16 LAMP1-488 + MitoRed,SPB8 AG2 P12 LAMP1-488 + MitoRed,SPB9 AG1 P10 LAMP1-488 + MitoRed,SPB10 AG0 P7 LAMP1-488 + MitoRed,SPB9 AG1 P10 p21-488,SPB2 AG6 P24 p21-488
4,SPB2 AG6 P24 LAMP1-488 + MitoRed,SPB3 AG5 P20 LAMP1-488 + MitoRed,SPB6 AG4 P18 LAMP1-488 + MitoRed,SPB7 AG3 P16 LAMP1-488 + MitoRed,SPB8 AG2 P12 LAMP1-488 + MitoRed,SPB9 AG1 P10 LAMP1-488 + MitoRed,SPB10 AG0 P7 LAMP1-488 + MitoRed,SPB9 AG1 P10 yH2AX-488,SPB2 AG6 P24 yH2AX-488
5,SPB2 AG6 P24 LAMP1-488 + MitoRed,SPB3 AG5 P20 LAMP1-488 + MitoRed,SPB6 AG4 P18 LAMP1-488 + MitoRed,SPB7 AG3 P16 LAMP1-488 + MitoRed,SPB8 AG2 P12 LAMP1-488 + MitoRed,SPB9 AG1 P10 LAMP1-488 + MitoRed,SPB10 AG0 P7 LAMP1-488 + MitoRed,SPB9 AG1 P10 yH2AX-488,SPB2 AG6 P24 yH2AX-488
6,SPB2 AG6 P24 LAMP1-488 + MitoRed,SPB3 AG5 P20 LAMP1-488 + MitoRed,SPB6 AG4 P18 LAMP1-488 + MitoRed,SPB7 AG3 P16 LAMP1-488 + MitoRed,SPB8 AG2 P12 LAMP1-488 + MitoRed,SPB9 AG1 P10 LAMP1-488 + MitoRed,SPB10 AG0 P7 LAMP1-488 + MitoRed,SPB9 AG1 P10 yH2AX-488,SPB2 AG6 P24 yH2AX-488

Exporting nov12plate.csv to /Users/allielas/HTP_fibroblasts_mitolyso/plate_metadata/20241112_rep04_metadata
Index(['Metadata_Well', 'Metadata_WellRow', 'Metadata_WellColumn',
       'Metadata_Field', 'TimepointName', 'SerialPassage_BatchNumber',
       'AgeGroup', 'PassageNumber', 'Staining', 'Drug'],
      dtype='object')
SPB2 AG6 P24,2,6,24,1,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,2,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,3,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,4,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,5,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,6,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,7,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,8,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,9,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,10,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,11,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,12,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,13,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,14,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,15,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,16,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,17,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,18,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,19,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,20,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,21,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,22,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,23,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,24,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,25,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,26,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,27,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,28,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,29,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,30,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,31,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,32,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,33,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,34,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,35,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,36,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,37,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,38,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,39,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,40,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,1,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,2,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,3,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,4,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,5,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,6,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,7,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,8,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,9,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,10,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,11,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,12,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,13,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,14,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,15,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,16,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,17,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,18,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,19,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,20,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,21,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,22,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,23,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,24,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,25,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,26,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,27,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,28,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,29,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,30,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,31,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,32,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,33,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,34,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,35,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,36,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,37,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,38,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,39,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,40,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,1,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,2,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,3,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,4,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,5,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,6,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,7,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,8,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,9,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,10,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,11,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,12,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,13,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,14,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,15,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,16,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,17,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,18,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,19,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,20,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,21,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,22,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,23,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,24,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,25,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,26,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,27,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,28,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,29,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,30,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,31,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,32,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,33,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,34,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,35,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,36,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,37,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,38,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,39,LAMP1-488 + MitoRed,None
SPB6 AG4 P18,6,4,18,40,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,1,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,2,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,3,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,4,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,5,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,6,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,7,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,8,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,9,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,10,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,11,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,12,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,13,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,14,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,15,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,16,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,17,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,18,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,19,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,20,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,21,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,22,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,23,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,24,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,25,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,26,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,27,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,28,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,29,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,30,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,31,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,32,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,33,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,34,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,35,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,36,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,37,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,38,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,39,LAMP1-488 + MitoRed,None
SPB7 AG3 P16,7,3,16,40,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,1,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,2,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,3,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,4,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,5,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,6,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,7,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,8,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,9,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,10,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,11,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,12,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,13,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,14,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,15,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,16,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,17,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,18,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,19,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,20,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,21,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,22,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,23,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,24,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,25,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,26,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,27,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,28,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,29,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,30,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,31,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,32,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,33,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,34,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,35,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,36,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,37,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,38,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,39,LAMP1-488 + MitoRed,None
SPB8 AG2 P12,8,2,12,40,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,1,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,2,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,3,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,4,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,5,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,6,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,7,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,8,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,9,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,10,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,11,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,12,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,13,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,14,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,15,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,16,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,17,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,18,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,19,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,20,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,21,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,22,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,23,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,24,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,25,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,26,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,27,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,28,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,29,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,30,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,31,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,32,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,33,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,34,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,35,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,36,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,37,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,38,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,39,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,40,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,1,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,2,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,3,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,4,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,5,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,6,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,7,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,8,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,9,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,10,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,11,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,12,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,13,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,14,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,15,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,16,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,17,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,18,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,19,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,20,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,21,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,22,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,23,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,24,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,25,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,26,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,27,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,28,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,29,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,30,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,31,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,32,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,33,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,34,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,35,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,36,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,37,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,38,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,39,LAMP1-488 + MitoRed,None
SPB10 AG0 P7,10,0,7,40,LAMP1-488 + MitoRed,None
SPB9 AG1 P10,9,1,10,1,p21-488,None
SPB9 AG1 P10,9,1,10,2,p21-488,None
SPB9 AG1 P10,9,1,10,3,p21-488,None
SPB9 AG1 P10,9,1,10,4,p21-488,None
SPB9 AG1 P10,9,1,10,5,p21-488,None
SPB9 AG1 P10,9,1,10,6,p21-488,None
SPB9 AG1 P10,9,1,10,7,p21-488,None
SPB9 AG1 P10,9,1,10,8,p21-488,None
SPB9 AG1 P10,9,1,10,9,p21-488,None
SPB9 AG1 P10,9,1,10,10,p21-488,None
SPB9 AG1 P10,9,1,10,11,p21-488,None
SPB9 AG1 P10,9,1,10,12,p21-488,None
SPB9 AG1 P10,9,1,10,13,p21-488,None
SPB9 AG1 P10,9,1,10,14,p21-488,None
SPB9 AG1 P10,9,1,10,15,p21-488,None
SPB9 AG1 P10,9,1,10,16,p21-488,None
SPB9 AG1 P10,9,1,10,17,p21-488,None
SPB9 AG1 P10,9,1,10,18,p21-488,None
SPB9 AG1 P10,9,1,10,19,p21-488,None
SPB9 AG1 P10,9,1,10,20,p21-488,None
SPB9 AG1 P10,9,1,10,21,p21-488,None
SPB9 AG1 P10,9,1,10,22,p21-488,None
SPB9 AG1 P10,9,1,10,23,p21-488,None
SPB9 AG1 P10,9,1,10,24,p21-488,None
SPB9 AG1 P10,9,1,10,25,p21-488,None
SPB9 AG1 P10,9,1,10,26,p21-488,None
SPB9 AG1 P10,9,1,10,27,p21-488,None
SPB9 AG1 P10,9,1,10,28,p21-488,None
SPB9 AG1 P10,9,1,10,29,p21-488,None
SPB9 AG1 P10,9,1,10,30,p21-488,None
SPB9 AG1 P10,9,1,10,31,p21-488,None
SPB9 AG1 P10,9,1,10,32,p21-488,None
SPB9 AG1 P10,9,1,10,33,p21-488,None
SPB9 AG1 P10,9,1,10,34,p21-488,None
SPB9 AG1 P10,9,1,10,35,p21-488,None
SPB9 AG1 P10,9,1,10,36,p21-488,None
SPB9 AG1 P10,9,1,10,37,p21-488,None
SPB9 AG1 P10,9,1,10,38,p21-488,None
SPB9 AG1 P10,9,1,10,39,p21-488,None
SPB9 AG1 P10,9,1,10,40,p21-488,None
SPB2 AG6 P24,2,6,24,1,p21-488,None
SPB2 AG6 P24,2,6,24,2,p21-488,None
SPB2 AG6 P24,2,6,24,3,p21-488,None
SPB2 AG6 P24,2,6,24,4,p21-488,None
SPB2 AG6 P24,2,6,24,5,p21-488,None
SPB2 AG6 P24,2,6,24,6,p21-488,None
SPB2 AG6 P24,2,6,24,7,p21-488,None
SPB2 AG6 P24,2,6,24,8,p21-488,None
SPB2 AG6 P24,2,6,24,9,p21-488,None
SPB2 AG6 P24,2,6,24,10,p21-488,None
SPB2 AG6 P24,2,6,24,11,p21-488,None
SPB2 AG6 P24,2,6,24,12,p21-488,None
SPB2 AG6 P24,2,6,24,13,p21-488,None
SPB2 AG6 P24,2,6,24,14,p21-488,None
SPB2 AG6 P24,2,6,24,15,p21-488,None
SPB2 AG6 P24,2,6,24,16,p21-488,None
SPB2 AG6 P24,2,6,24,17,p21-488,None
SPB2 AG6 P24,2,6,24,18,p21-488,None
SPB2 AG6 P24,2,6,24,19,p21-488,None
SPB2 AG6 P24,2,6,24,20,p21-488,None
SPB2 AG6 P24,2,6,24,21,p21-488,None
SPB2 AG6 P24,2,6,24,22,p21-488,None
SPB2 AG6 P24,2,6,24,23,p21-488,None
SPB2 AG6 P24,2,6,24,24,p21-488,None
SPB2 AG6 P24,2,6,24,25,p21-488,None
SPB2 AG6 P24,2,6,24,26,p21-488,None
SPB2 AG6 P24,2,6,24,27,p21-488,None
SPB2 AG6 P24,2,6,24,28,p21-488,None
SPB2 AG6 P24,2,6,24,29,p21-488,None
SPB2 AG6 P24,2,6,24,30,p21-488,None
SPB2 AG6 P24,2,6,24,31,p21-488,None
SPB2 AG6 P24,2,6,24,32,p21-488,None
SPB2 AG6 P24,2,6,24,33,p21-488,None
SPB2 AG6 P24,2,6,24,34,p21-488,None
SPB2 AG6 P24,2,6,24,35,p21-488,None
SPB2 AG6 P24,2,6,24,36,p21-488,None
SPB2 AG6 P24,2,6,24,37,p21-488,None
SPB2 AG6 P24,2,6,24,38,p21-488,None
SPB2 AG6 P24,2,6,24,39,p21-488,None
SPB2 AG6 P24,2,6,24,40,p21-488,None
SPB2 AG6 P24,2,6,24,1,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,2,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,3,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,4,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,5,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,6,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,7,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,8,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,9,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,10,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,11,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,12,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,13,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,14,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,15,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,16,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,17,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,18,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,19,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,20,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,21,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,22,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,23,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,24,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,25,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,26,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,27,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,28,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,29,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,30,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,31,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,32,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,33,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,34,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,35,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,36,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,37,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,38,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,39,LAMP1-488 + MitoRed,None
SPB2 AG6 P24,2,6,24,40,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,1,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,2,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,3,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,4,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,5,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,6,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,7,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,8,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,9,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,10,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,11,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,12,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,13,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,14,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,15,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,16,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,17,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,18,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,19,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,20,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,21,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,22,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,23,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,24,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,25,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,26,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,27,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,28,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,29,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,30,LAMP1-488 + MitoRed,None
SPB3 AG5 P20,3,5,20,31,LAMP1-488 + MitoRed,None

,1,2,3,4,5,6,7,8,9,10,11,12
1,SPB12 AG2_Doxo P12 LAMP1-488 + MitoRed + Phall...,SPB3 AG9 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG8 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG6 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG3 P17 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG2 P15 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG1 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647
2,SPB12 AG2_Doxo P12 LAMP1-488 + MitoRed + Phall...,SPB3 AG9 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG8 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG6 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG3 P17 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG2 P15 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG1 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647
3,SPB12 AG2_Doxo P12 LAMP1-488 + MitoRed + Phall...,SPB3 AG9 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG8 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG6 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG3 P17 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG2 P15 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG1 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647
4,SPB12 AG2_Doxo P12 LAMP1-488 + MitoRed + Phall...,SPB3 AG9 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG8 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG6 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG3 P17 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG2 P15 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG1 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647
5,SPB12 AG2_Doxo P12 LAMP1-488 + MitoRed + Phall...,SPB3 AG9 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG8 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG6 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG3 P17 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG2 P15 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG1 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647
6,SPB12 AG2_Doxo P12 LAMP1-488 + MitoRed + Phall...,SPB3 AG9 P29 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG8 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG6 P22 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG4 P18 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG3 P17 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG2 P15 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG1 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647,SPB13 AG0 P9 LAMP1-488 + MitoRed + Phalloidin-647

Exporting may01plate.csv to /Users/allielas/HTP_fibroblasts_mitolyso/plate_metadata/20250501_rep07_metadata
Index(['Metadata_Well', 'Metadata_WellRow', 'Metadata_WellColumn',
       'Metadata_Field', 'TimepointName', 'SerialPassage_BatchNumber',
       'AgeGroup', 'PassageNumber', 'Staining', 'Drug'],
      dtype='object')
SPB12 AG2_Doxo P12,12,2,12,1,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,2,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,3,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,4,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,5,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,6,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,7,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,8,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,9,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,10,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,11,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,12,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,13,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,14,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,15,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,16,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,17,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,18,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,19,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,20,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,21,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,22,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,23,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,24,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,25,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,26,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,27,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,28,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,29,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,30,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,31,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,32,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,33,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,34,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,35,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,36,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,37,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,38,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,39,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB12 AG2_Doxo P12,12,2,12,40,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB3 AG9 P29,3,9,29,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB3 AG9 P29,3,9,29,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG8 P27,4,8,27,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB2 AG7 P24,2,7,24,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB8 AG6 P22,8,6,22,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB9 AG5 P20,9,5,20,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,18,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,19,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,20,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,21,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,22,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,23,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,24,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,25,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,26,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,27,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,28,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,29,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,30,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,31,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,32,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,33,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,34,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,35,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,36,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,37,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,38,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,39,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB4 AG4 P18,4,4,18,40,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,1,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,2,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,3,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,4,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,5,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,6,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,7,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,8,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,9,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,10,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,11,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,12,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,13,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,14,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,15,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,16,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,17,LAMP1-488 + MitoRed + Phalloidin-647,None
SPB10 AG3 P17,10,3,17,18,LAMP1-488 + MitoRed + Phalloidin-647,None

,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,SPB8 AG3_Doxo P16 LAMP1-488 + MitoRed + Phallo...,NaN,NaN,NaN,NaN,NaN
1,SPB11 AG1_Doxo P9 LMNB1-594 1:250 + Phalloidin...,SPB11 AG1_Doxo P9 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P30 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB3 AG6 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG4 P19 LAMP1-488 + MitoRed + Phalloidin-647,SPB9 AG3 P17 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG2 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG0 P8 LAMP1-488 + MitoRed + Phalloidin-647,SPB12 AG0 P8 LMNB1-594 1:250 + Phalloidin-647
2,SPB11 AG1_Doxo P9 LMNB1-594 1:500 + Phalloidin...,SPB11 AG1_Doxo P9 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P30 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB3 AG6 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG4 P19 LAMP1-488 + MitoRed + Phalloidin-647,SPB6 AG3 P17 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG2 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG0 P8 LAMP1-488 + MitoRed + Phalloidin-647,SPB12 AG0 P8 LMNB1-594 1:500 + Phalloidin-647
3,SPB11 AG1_Doxo P9 LMNB1-594 1:750 + Phalloidin...,SPB11 AG1_Doxo P9 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P30 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB3 AG6 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG4 P19 LAMP1-488 + MitoRed + Phalloidin-647,SPB6 AG3 P17 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG2 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG0 P8 LAMP1-488 + MitoRed + Phalloidin-647,SPB12 AG0 P8 LMNB1-594 1:750 + Phalloidin-647
4,SPB11 AG1_Doxo P9 LMNB1&Ki67-594 1:250 + Phall...,SPB11 AG1_Doxo P9 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P30 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB3 AG6 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG4 P19 LAMP1-488 + MitoRed + Phalloidin-647,SPB6 AG3 P17 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG2 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG0 P8 LAMP1-488 + MitoRed + Phalloidin-647,SPB12 AG0 P8 LMNB1&Ki67-594 1:250 + Phalloidin...
5,SPB11 AG1_Doxo P9 LMNB1&Ki67-594 1:500 + Phall...,SPB11 AG1_Doxo P9 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P30 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB3 AG6 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG4 P19 LAMP1-488 + MitoRed + Phalloidin-647,SPB6 AG3 P17 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG2 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG0 P8 LAMP1-488 + MitoRed + Phalloidin-647,SPB12 AG0 P8 LMNB1&Ki67-594 1:500 + Phalloidin...
6,SPB11 AG1_Doxo P9 LMNB1&Ki67-594 1:750 + Phall...,SPB11 AG1_Doxo P9 LAMP1-488 + MitoRed + Phallo...,SPB2 AG8 P30 LAMP1-488 + MitoRed + Phalloidin-647,SPB2 AG7 P27 LAMP1-488 + MitoRed + Phalloidin-647,SPB3 AG6 P24 LAMP1-488 + MitoRed + Phalloidin-647,SPB4 AG5 P20 LAMP1-488 + MitoRed + Phalloidin-647,SPB8 AG4 P19 LAMP1-488 + MitoRed + Phalloidin-647,SPB6 AG3 P17 LAMP1-488 + MitoRed + Phalloidin-647,SPB10 AG2 P13 LAMP1-488 + MitoRed + Phalloidin...,SPB11 AG1 P10 LAMP1-488 + MitoRed + Phalloidin...,SPB12 AG0 P8 LAMP1-488 + MitoRed + Phalloidin-647,SPB12 AG0 P8 LMNB1&Ki67-594 1:750 + Phalloidin...

Exporting apr10plate.csv to /Users/allielas/HTP_fibroblasts_mitolyso/plate_metadata/20250410_rep06_metadata
Index(['Metadata_Well', 'Metadata_WellRow', 'Metadata_WellColumn',
       'Metadata_Field', 'TimepointName', 'SerialPassage_BatchNumber',
       'AgeGroup', 'PassageNumber', 'Staining', 'Drug'],
      dtype='object')
SPB8 AG3_Doxo P16,8,3,16,1,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,2,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,3,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,4,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,5,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,6,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,7,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,8,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,9,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,10,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,11,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,12,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,13,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,14,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,15,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,16,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,17,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,18,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,19,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,20,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,21,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,22,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,23,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,24,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,25,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,26,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,27,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,28,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,29,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,30,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,31,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,32,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,33,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,34,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,35,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,36,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,37,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,38,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,39,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,40,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,1,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,2,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,3,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,4,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,5,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,6,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,7,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,8,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,9,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,10,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,11,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,12,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,13,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,14,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,15,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,16,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,17,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,18,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,19,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,20,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,21,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,22,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,23,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,24,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,25,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,26,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,27,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,28,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,29,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,30,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,31,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,32,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,33,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,34,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,35,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,36,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,37,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,38,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,39,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,40,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,1,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,2,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,3,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,4,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,5,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,6,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,7,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,8,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,9,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,10,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,11,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,12,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,13,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,14,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,15,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,16,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,17,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,18,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,19,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,20,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,21,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,22,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,23,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,24,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,25,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,26,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,27,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,28,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,29,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,30,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,31,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,32,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,33,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,34,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,35,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,36,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,37,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,38,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,39,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,40,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,1,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,2,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,3,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,4,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,5,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,6,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,7,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,8,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,9,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,10,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,11,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,12,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,13,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,14,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,15,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,16,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,17,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,18,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,19,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,20,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,21,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,22,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,23,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,24,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,25,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,26,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,27,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,28,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,29,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,30,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,31,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,32,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,33,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,34,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,35,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,36,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,37,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,38,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,39,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,40,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,1,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,2,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,3,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,4,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,5,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,6,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,7,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,8,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,9,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,10,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,11,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,12,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,13,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,14,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,15,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,16,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,17,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,18,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,19,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,20,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,21,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,22,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,23,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,24,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,25,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,26,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,27,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,28,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,29,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,30,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,31,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,32,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,33,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,34,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,35,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,36,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,37,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,38,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,39,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,40,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,1,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,2,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,3,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,4,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,5,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,6,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,7,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,8,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,9,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,10,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,11,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,12,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,13,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,14,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,15,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,16,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,17,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,18,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,19,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,20,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,21,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,22,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,23,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,24,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,25,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,26,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,27,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,28,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,29,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,30,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,31,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,32,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,33,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,34,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,35,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,36,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,37,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,38,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,39,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB8 AG3_Doxo P16,8,3,16,40,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,1,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,2,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,3,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,4,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,5,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,6,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,7,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,8,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,9,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,10,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,11,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,12,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,13,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,14,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,15,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,16,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,17,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,18,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,19,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,20,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,21,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,22,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,23,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,24,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,25,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,26,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,27,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,28,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,29,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,30,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,31,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,32,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,33,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,34,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,35,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,36,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,37,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,38,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,39,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,40,LMNB1-594 1:250 + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,1,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,2,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,3,LAMP1-488 + MitoRed + Phalloidin-647,Doxo
SPB11 AG1_Doxo P9,11,1,9,4,LAMP1-488 + MitoRed + Phalloidin-647,Doxo

,2,3,4,5,6,7,8,9,10,11
1,SPB1 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG2 P11 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG4 P17 EEA1-488 + ConA-594 + Tfn-647,SPB2 AG3 P14 EEA1-488 + ConA-594 + Tfn-647,SPB3 AG2 P11 EEA1-488 + ConA-594 + Tfn-647,SPB4 AG1 P9 EEA1-488 + ConA-594 + Tfn-647,SPB5 AG0 P6 EEA1-488 + ConA-594 + Tfn-647
2,SPB1 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG2 P11 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG4 P17 EEA1-488 + ConA-594 + Tfn-647,SPB2 AG3 P14 EEA1-488 + ConA-594 + Tfn-647,SPB3 AG2 P11 EEA1-488 + ConA-594 + Tfn-647,SPB4 AG1 P9 EEA1-488 + ConA-594 + Tfn-647,SPB5 AG0 P6 EEA1-488 + ConA-594 + Tfn-647
3,SPB1 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG2 P11 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG4 P17 EEA1-488 + ConA-594 + Tfn-647,SPB2 AG3 P14 EEA1-488 + ConA-594 + Tfn-647,SPB3 AG2 P11 EEA1-488 + ConA-594 + Tfn-647,SPB4 AG1 P9 EEA1-488 + ConA-594 + Tfn-647,SPB5 AG0 P6 EEA1-488 + ConA-594 + Tfn-647
4,SPB1 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG2 P11 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG4 P17 EEA1-488 + ConA-594 + Tfn-647,SPB2 AG3 P14 EEA1-488 + ConA-594 + Tfn-647,SPB3 AG2 P11 EEA1-488 + ConA-594 + Tfn-647,SPB4 AG1 P9 EEA1-488 + ConA-594 + Tfn-647,SPB5 AG0 P6 EEA1-488 + ConA-594 + Tfn-647
5,SPB1 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG2 P11 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG4 P17 EEA1-488 + ConA-594 + Tfn-647,SPB2 AG3 P14 EEA1-488 + ConA-594 + Tfn-647,SPB3 AG2 P11 EEA1-488 + ConA-594 + Tfn-647,SPB4 AG1 P9 EEA1-488 + ConA-594 + Tfn-647,SPB5 AG0 P6 EEA1-488 + ConA-594 + Tfn-647
6,SPB1 AG4 P17 LAMP1-488 + MitoRed + WGA-CF640R,SPB2 AG3 P14 LAMP1-488 + MitoRed + WGA-CF640R,SPB3 AG2 P11 LAMP1-488 + MitoRed + WGA-CF640R,SPB4 AG1 P9 LAMP1-488 + MitoRed + WGA-CF640R,SPB5 AG0 P6 LAMP1-488 + MitoRed + WGA-CF640R,SPB1 AG4 P17 EEA1-488 + ConA-594 + Tfn-647,SPB2 AG3 P14 EEA1-488 + ConA-594 + Tfn-647,SPB3 AG2 P11 EEA1-488 + ConA-594 + Tfn-647,SPB4 AG1 P9 EEA1-488 + ConA-594 + Tfn-647,SPB5 AG0 P6 EEA1-488 + ConA-594 + Tfn-647

Exporting mar13plate.csv to /Users/allielas/HTP_fibroblasts_mitolyso/plate_metadata/20240313_rep01_metadata
Index(['Metadata_Well', 'Metadata_WellRow', 'Metadata_WellColumn',
       'Metadata_Field', 'TimepointName', 'SerialPassage_BatchNumber',
       'AgeGroup', 'PassageNumber', 'Staining', 'Drug'],
      dtype='object')
SPB1 AG4 P17,1,4,17,1,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,2,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,3,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,4,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,5,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,6,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,7,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,8,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,9,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,10,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,11,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,12,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,13,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,14,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,15,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,16,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,17,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,18,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,19,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,20,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,21,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,22,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,23,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,24,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,25,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,26,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,27,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,28,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,29,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,30,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,31,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,32,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,33,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,34,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,35,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,36,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,37,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,38,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,39,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,40,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,1,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,2,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,3,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,4,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,5,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,6,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,7,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,8,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,9,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,10,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,11,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,12,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,13,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,14,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,15,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,16,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,17,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,18,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,19,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,20,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,21,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,22,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,23,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,24,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,25,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,26,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,27,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,28,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,29,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,30,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,31,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,32,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,33,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,34,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,35,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,36,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,37,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,38,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,39,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB2 AG3 P14,2,3,14,40,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,1,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,2,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,3,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,4,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,5,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,6,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,7,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,8,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,9,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,10,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,11,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,12,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,13,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,14,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,15,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,16,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,17,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,18,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,19,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,20,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,21,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,22,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,23,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,24,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,25,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,26,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,27,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,28,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,29,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,30,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,31,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,32,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,33,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,34,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,35,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,36,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,37,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,38,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,39,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB3 AG2 P11,3,2,11,40,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,1,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,2,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,3,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,4,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,5,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,6,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,7,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,8,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,9,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,10,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,11,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,12,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,13,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,14,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,15,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,16,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,17,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,18,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,19,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,20,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,21,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,22,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,23,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,24,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,25,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,26,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,27,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,28,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,29,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,30,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,31,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,32,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,33,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,34,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,35,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,36,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,37,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,38,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,39,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB4 AG1 P9,4,1,9,40,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,1,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,2,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,3,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,4,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,5,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,6,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,7,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,8,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,9,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,10,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,11,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,12,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,13,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,14,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,15,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,16,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,17,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,18,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,19,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,20,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,21,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,22,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,23,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,24,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,25,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,26,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,27,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,28,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,29,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,30,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,31,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,32,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,33,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,34,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,35,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,36,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,37,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,38,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,39,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB5 AG0 P6,5,0,6,40,LAMP1-488 + MitoRed + WGA-CF640R,None
SPB1 AG4 P17,1,4,17,1,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,2,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,3,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,4,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,5,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,6,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,7,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,8,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,9,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,10,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,11,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,12,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,13,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,14,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,15,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,16,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,17,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,18,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,19,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,20,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,21,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,22,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,23,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,24,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,25,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,26,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,27,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,28,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,29,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,30,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,31,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,32,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,33,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,34,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,35,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,36,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,37,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,38,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,39,EEA1-488 + ConA-594 + Tfn-647,None
SPB1 AG4 P17,1,4,17,40,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,1,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,2,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,3,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,4,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,5,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,6,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,7,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,8,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,9,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,10,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,11,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,12,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,13,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,14,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,15,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,16,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,17,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,18,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,19,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,20,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,21,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,22,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,23,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,24,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,25,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,26,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,27,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,28,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,29,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,30,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,31,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,32,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,33,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,34,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,35,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,36,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,37,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,38,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,39,EEA1-488 + ConA-594 + Tfn-647,None
SPB2 AG3 P14,2,3,14,40,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,1,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,2,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,3,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,4,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,5,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,6,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,7,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,8,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,9,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,10,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,11,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,12,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,13,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,14,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,15,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,16,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,17,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,18,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,19,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,20,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,21,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,22,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,23,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,24,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,25,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,26,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,27,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,28,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,29,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,30,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,31,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,32,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,33,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,34,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,35,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,36,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,37,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,38,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,39,EEA1-488 + ConA-594 + Tfn-647,None
SPB3 AG2 P11,3,2,11,40,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,1,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,2,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,3,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,4,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,5,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,6,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,7,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,8,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,9,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,10,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,11,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,12,EEA1-488 + ConA-594 + Tfn-647,None
SPB4 AG1 P9,4,1,9,13,EEA1-488 + ConA-594 + Tfn-647,None

,2,3,4,5,6,7
0,SPB2 AG5 P21 Phalloidin-647 + ConA-594,SPB3 AG4 P18 Phalloidin-647 + ConA-594,SPB4 AG3 P15 Phalloidin-647 + ConA-594,SPB5 AG2 P13 Phalloidin-647 + ConA-594,SPB6 AG1 P10 Phalloidin-647 + ConA-594,SPB7 AG0 P8 Phalloidin-647 + ConA-594
1,SPB2 AG5 P21 LAMP1-488 + MitoRed,SPB3 AG4 P18 LAMP1-488 + MitoRed,SPB4 AG3 P15 LAMP1-488 + MitoRed,SPB5 AG2 P13 LAMP1-488 + MitoRed,SPB6 AG1 P10 LAMP1-488 + MitoRed,SPB7 AG0 P8 LAMP1-488 + MitoRed
2,SPB2 AG5 P21 LAMP1-488 + MitoRed,SPB3 AG4 P18 LAMP1-488 + MitoRed,SPB4 AG3 P15 LAMP1-488 + MitoRed,SPB5 AG2 P13 LAMP1-488 + MitoRed,SPB6 AG1 P10 LAMP1-488 + MitoRed,SPB7 AG0 P8 LAMP1-488 + MitoRed
3,SPB2 AG5 P21 LAMP1-488 + MitoRed,SPB3 AG4 P18 LAMP1-488 + MitoRed,SPB4 AG3 P15 LAMP1-488 + MitoRed,SPB5 AG2 P13 LAMP1-488 + MitoRed,SPB6 AG1 P10 LAMP1-488 + MitoRed,SPB7 AG0 P8 LAMP1-488 + MitoRed
4,SPB2 AG5 P21 LAMP1-488 + MitoRed,SPB3 AG4 P18 LAMP1-488 + MitoRed,SPB4 AG3 P15 LAMP1-488 + MitoRed,SPB5 AG2 P13 LAMP1-488 + MitoRed,SPB6 AG1 P10 LAMP1-488 + MitoRed,SPB7 AG0 P8 LAMP1-488 + MitoRed
5,SPB2 AG5 P21 LAMP1-488 + MitoRed,SPB3 AG4 P18 LAMP1-488 + MitoRed,SPB4 AG3 P15 LAMP1-488 + MitoRed,SPB5 AG2 P13 LAMP1-488 + MitoRed,SPB6 AG1 P10 LAMP1-488 + MitoRed,SPB7 AG0 P8 LAMP1-488 + MitoRed
6,SPB2 AG5 P21 LAMP1-488 + MitoRed,SPB3 AG4 P18 LAMP1-488 + MitoRed,SPB4 AG3 P15 LAMP1-488 + MitoRed,SPB5 AG2 P13 LAMP1-488 + MitoRed,SPB6 AG1 P10 LAMP1-488 + MitoRed,SPB7 AG0 P8 LAMP1-488 + MitoRed
7,SPB2 AG5 P21 Phalloidin-647 + WGA-647 + ConA-594,SPB3 AG4 P18 Phalloidin-647 + WGA-647 + ConA-594,SPB4 AG3 P15 Phalloidin-647 + WGA-647 + ConA-594,SPB5 AG2 P13 Phalloidin-647 + WGA-647 + ConA-594,SPB6 AG1 P10 Phalloidin-647 + WGA-647 + ConA-594,SPB7 AG0 P8 Phalloidin-647 + WGA-647 + ConA-594

Exporting oct18plate.csv to /Users/allielas/HTP_fibroblasts_mitolyso/plate_metadata/20241018_rep03_metadata
Index(['Metadata_Well', 'Metadata_WellRow', 'Metadata_WellColumn',
       'Metadata_Field', 'TimepointName', 'SerialPassage_BatchNumber',
       'AgeGroup', 'PassageNumber', 'Staining', 'Drug'],
      dtype='object')
SPB2 AG5 P21,2,5,21,1,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,2,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,3,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,4,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,5,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,6,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,7,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,8,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,9,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,10,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,11,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,12,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,13,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,14,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,15,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,16,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,17,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,18,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,19,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,20,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,21,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,22,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,23,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,24,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,25,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,26,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,27,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,28,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,29,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,30,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,31,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,32,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,33,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,34,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,35,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,36,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,37,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,38,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,39,Phalloidin-647 + ConA-594 ,None
SPB2 AG5 P21,2,5,21,40,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,1,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,2,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,3,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,4,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,5,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,6,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,7,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,8,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,9,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,10,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,11,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,12,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,13,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,14,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,15,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,16,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,17,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,18,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,19,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,20,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,21,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,22,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,23,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,24,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,25,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,26,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,27,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,28,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,29,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,30,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,31,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,32,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,33,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,34,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,35,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,36,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,37,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,38,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,39,Phalloidin-647 + ConA-594 ,None
SPB3 AG4 P18,3,4,18,40,Phalloidin-647 + ConA-594 ,None
SPB4 AG3 P15,4,3,15,1,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,2,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,3,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,4,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,5,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,6,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,7,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,8,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,9,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,10,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,11,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,12,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,13,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,14,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,15,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,16,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,17,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,18,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,19,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,20,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,21,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,22,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,23,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,24,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,25,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,26,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,27,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,28,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,29,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,30,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,31,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,32,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,33,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,34,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,35,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,36,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,37,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,38,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,39,Phalloidin-647 + ConA-594  ,None
SPB4 AG3 P15,4,3,15,40,Phalloidin-647 + ConA-594  ,None
SPB5 AG2 P13,5,2,13,1,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,2,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,3,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,4,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,5,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,6,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,7,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,8,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,9,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,10,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,11,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,12,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,13,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,14,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,15,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,16,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,17,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,18,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,19,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,20,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,21,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,22,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,23,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,24,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,25,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,26,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,27,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,28,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,29,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,30,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,31,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,32,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,33,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,34,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,35,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,36,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,37,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,38,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,39,Phalloidin-647 + ConA-594 ,None
SPB5 AG2 P13,5,2,13,40,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,1,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,2,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,3,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,4,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,5,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,6,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,7,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,8,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,9,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,10,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,11,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,12,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,13,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,14,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,15,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,16,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,17,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,18,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,19,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,20,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,21,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,22,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,23,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,24,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,25,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,26,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,27,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,28,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,29,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,30,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,31,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,32,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,33,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,34,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,35,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,36,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,37,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,38,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,39,Phalloidin-647 + ConA-594 ,None
SPB6 AG1 P10,6,1,10,40,Phalloidin-647 + ConA-594 ,None
SPB7 AG0 P8,7,0,8,1,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,2,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,3,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,4,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,5,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,6,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,7,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,8,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,9,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,10,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,11,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,12,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,13,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,14,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,15,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,16,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,17,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,18,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,19,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,20,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,21,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,22,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,23,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,24,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,25,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,26,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,27,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,28,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,29,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,30,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,31,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,32,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,33,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,34,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,35,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,36,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,37,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,38,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,39,Phalloidin-647 + ConA-594  ,None
SPB7 AG0 P8,7,0,8,40,Phalloidin-647 + ConA-594  ,None
SPB2 AG5 P21,2,5,21,1,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,2,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,3,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,4,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,5,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,6,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,7,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,8,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,9,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,10,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,11,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,12,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,13,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,14,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,15,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,16,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,17,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,18,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,19,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,20,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,21,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,22,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,23,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,24,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,25,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,26,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,27,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,28,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,29,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,30,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,31,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,32,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,33,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,34,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,35,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,36,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,37,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,38,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,39,LAMP1-488 + MitoRed ,None
SPB2 AG5 P21,2,5,21,40,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,1,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,2,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,3,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,4,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,5,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,6,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,7,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,8,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,9,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,10,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,11,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,12,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,13,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,14,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,15,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,16,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,17,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,18,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,19,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,20,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,21,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,22,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,23,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,24,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,25,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,26,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,27,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,28,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,29,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,30,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,31,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,32,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,33,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,34,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,35,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,36,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,37,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,38,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,39,LAMP1-488 + MitoRed ,None
SPB3 AG4 P18,3,4,18,40,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,1,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,2,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,3,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,4,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,5,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,6,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,7,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,8,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,9,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,10,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,11,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,12,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,13,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,14,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,15,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,16,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,17,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,18,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,19,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,20,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,21,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,22,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,23,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,24,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,25,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,26,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,27,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,28,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,29,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,30,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,31,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,32,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,33,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,34,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,35,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,36,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,37,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,38,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,39,LAMP1-488 + MitoRed ,None
SPB4 AG3 P15,4,3,15,40,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,1,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,2,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,3,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,4,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,5,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,6,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,7,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,8,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,9,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,10,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,11,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,12,LAMP1-488 + MitoRed ,None
SPB5 AG2 P13,5,2,13,13,LAMP1-488 + MitoRed ,None