In [15]:
import argparse
import sys
import re
from pathlib import Path
import numpy as np
import pandas as pd
from typing import Dict, List, Tuple, Union
from openpyxl import load_workbook

In [26]:
def drop_bad_reads(df, times=[], images=[]):
    df = df.copy()
    
    if times and "Elapsed" in df.columns:
    # keep rows where Elapsed is NOT in the times list using Series.isin
        df = df[~df["Elapsed"].isin(times)]    
    if images:
        cols = df.columns.astype(str)
        cols_to_drop = []
        for col in cols:
            if ", Image" in col:
                m = re.search(r'Image\s*(\d+)$', col)
                if m:
                    try:
                        num = int(m.group(1))
                        if num in images:
                            cols_to_drop.append(col)
                    except ValueError:
                        pass
        if cols_to_drop:
            df = df.drop(columns=cols_to_drop)
           
    return df.reset_index(drop=True)

def make_average_column_for_well(df, num_reads_per_well = 9):
    df = df.copy()
    new_averages = {}
    cols = df.columns.astype(str)
    #only use numeric cols
    numeric_cols = cols[3:]
    #print(f"len {len(numeric_cols)}, reads used: {num_reads_per_well}, remainder: {len(numeric_cols) % num_reads_per_well}")
    
    if len(numeric_cols) % num_reads_per_well == 0: #make sure the number won't go out of range
        for i in range(0, len(numeric_cols), num_reads_per_well):
            cols_to_avg = [numeric_cols[i] for i in range(i,i+num_reads_per_well)]
            split_header = cols_to_avg[0].split(",")
            well_name = split_header[0]
            new_averages[well_name] = df[cols_to_avg].mean(axis=1)
        header_df = df[cols[:3]]
        
        new_df = pd.DataFrame(new_averages)
        return pd.concat([header_df,new_df], axis=1)
    else:
        return pd.DataFrame()

def make_technical_rep_average_columns(df, num_to_avg=2):
    df = df.copy()
    new_averages = {}
    cols = df.columns.astype(str)
    numeric_cols = cols[3:]
    
    if len(numeric_cols) % num_to_avg == 0: #make sure the number won't go out of range
        for i in range(0, len(numeric_cols), num_to_avg):
            cols_to_avg = [numeric_cols[i] for i in range(i,i+num_to_avg)]
            split_header = cols_to_avg[0].split("(")
            well_name = split_header[0]
            new_averages[well_name] = df[cols_to_avg].mean(axis=1)
        header_df = df[cols[:3]]
        
        new_avg_df = pd.DataFrame(new_averages)
        return pd.concat([header_df,new_avg_df], axis=1)
    else:
        return pd.DataFrame()

In [29]:
def make_average_excel_with_exclusions(
input,
output,
inplace=False,
input_sheet = "Reformatted",
output_sheet="Averages",
overwrite=False,
time_rows_to_drop = [0,2],
images_to_drop = [5],
display_table=False
):
    inp = Path(input)
    if not inp.exists():
        print(f"Input file does not exist: {inp}", file=sys.stderr)
        sys.exit(2)

    if inplace and output:
        print("Cannot use --inplace and --output together.", file=sys.stderr)
        sys.exit(2)

    if input_sheet is not None:
        # allow numeric index if user provides digits
        try:
            sheet_name = int(input_sheet)
        except ValueError:
            sheet_name = input_sheet
    else:
        sheet_name = "Sheet1"

    df = pd.read_excel(inp, sheet_name=sheet_name)
    
    # apply replacements
    drop_df = drop_bad_reads(df,time_rows_to_drop,images_to_drop)
    
    number_images_dropped = len(images_to_drop)
    increment = int(9-number_images_dropped)
    out_df = make_average_column_for_well(drop_df, increment)
    # avg the two wells per lineage/group
    out_df_avg = make_technical_rep_average_columns(out_df)
    if display_table:
        display(df)
        display(drop_df)
        display(out_df)
        display(out_df_avg)

    # determine output path
    if inplace:
        out_path = inp
    elif output:
        out_path = Path(output)
    else:
        out_path = inp.with_name(inp.stem + "_editded" + inp.suffix)

    if Path.exists(out_path):
        try:
            with pd.ExcelWriter(out_path, engine="openpyxl", mode="a") as writer:
                out_df.to_excel(writer, sheet_name=output_sheet)
                out_df_avg.to_excel(writer, sheet_name="Mean_"+output_sheet)
        except ValueError:
            if overwrite:
                with pd.ExcelWriter(out_path, engine="openpyxl", mode="w") as writer:
                    out_df.to_excel(writer, sheet_name=output_sheet)
                    out_df_avg.to_excel(writer, sheet_name="Mean_"+output_sheet)
            else:
                ValueError("Overwrite is disabled and sheet exists")
    else:
        # write back to excel
        out_df.to_excel(out_path, sheet_name=output_sheet, index=False)
    print(f"Wrote replaced data to: {out_path}")

In [ ]:
for i in range(1,8):
    plate = i
    input= f"/Users/allielas/HTP_fibroblasts_mitolyso/proliferation_growth_curves/Incucyte_sheets/r{plate}.xlsx"
    output= f"/Users/allielas/HTP_fibroblasts_mitolyso/proliferation_growth_curves/Incucyte_sheets/processed/r{plate}_processed.xlsx"
    make_average_excel_with_exclusions(input,output,display_table=True, overwrite=True)

/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Plate_Number,Vessel_Name,Elapsed,"P20 LIN1-0B-b1 (A1), Image 1","P20 LIN1-0B-b1 (A1), Image 2","P20 LIN1-0B-b1 (A1), Image 3","P20 LIN1-0B-b1 (A1), Image 4","P20 LIN1-0B-b1 (A1), Image 5","P20 LIN1-0B-b1 (A1), Image 6","P20 LIN1-0B-b1 (A1), Image 7",...,"P10 LIN5-0B-b3 (C3), Image 9","P10 LIN5-0B-b3 (C4), Image 1","P10 LIN5-0B-b3 (C4), Image 2","P10 LIN5-0B-b3 (C4), Image 3","P10 LIN5-0B-b3 (C4), Image 4","P10 LIN5-0B-b3 (C4), Image 5","P10 LIN5-0B-b3 (C4), Image 6","P10 LIN5-0B-b3 (C4), Image 7","P10 LIN5-0B-b3 (C4), Image 8","P10 LIN5-0B-b3 (C4), Image 9"
0,1.0,AS_MRC-5_20240313,0,1.590103e+01,19.931510,20.285450,20.816760,47.851630,21.158760,26.945550,...,17.59704,17.47712,24.42150,33.82525,26.85103,35.82420,23.74823,26.88886,25.71194,20.37663
1,1.0,AS_MRC-5_20240313,4,1.370022e+01,17.716070,17.296350,18.042100,49.066320,21.104470,25.140340,...,15.45249,14.79670,23.98847,32.30291,24.50298,36.44600,25.45489,23.20039,21.77953,18.32537
2,1.0,AS_MRC-5_20240313,8,1.463772e+01,18.375150,17.046340,19.791510,48.511180,20.220990,26.844000,...,18.82457,16.54188,25.78643,31.80896,26.68330,39.44445,29.67746,28.86678,23.64510,22.01076
3,1.0,AS_MRC-5_20240313,12,1.313210e+01,18.823890,19.819710,19.826740,52.072350,22.608780,27.270460,...,21.14353,18.09188,28.42391,37.00899,29.36483,47.95085,32.72959,30.47305,28.26028,23.69120
4,1.0,AS_MRC-5_20240313,16,1.318421e+01,20.718420,18.322290,20.089190,54.867390,26.392390,28.844040,...,22.26146,18.22026,29.39931,40.33483,33.08198,49.10907,36.21591,30.77803,33.11140,24.87578
5,1.0,AS_MRC-5_20240313,20,1.547025e+01,22.952910,21.085960,23.228260,61.578620,29.727380,32.613770,...,24.01517,22.72577,34.75934,46.19578,36.71526,63.43374,48.07835,38.70916,38.56288,31.00169
6,1.0,AS_MRC-5_20240313,24,1.639737e+01,25.823860,25.148330,25.560530,67.732600,35.175650,34.817380,...,29.80222,27.30830,40.11378,55.10899,44.07670,69.36155,53.26055,43.06381,42.44953,36.12196
7,1.0,AS_MRC-5_20240313,28,1.962740e+01,27.449330,28.997550,28.801150,70.922130,41.234420,41.416970,...,37.20976,30.22542,46.41178,62.42372,53.79835,76.57376,62.98090,50.15310,52.16469,42.12447
8,1.0,AS_MRC-5_20240313,32,2.261706e+01,30.780090,35.398410,33.435170,79.347760,47.933570,51.082280,...,45.47373,38.78162,57.61432,74.12410,66.96979,89.05362,72.18811,60.29761,62.47507,51.56707
9,1.0,AS_MRC-5_20240313,36,2.671288e+01,34.064960,38.748420,37.972370,81.647250,52.899430,57.348590,...,56.28858,44.38347,67.17063,81.80172,76.67517,95.69930,85.92998,70.13753,71.94984,62.81667
10,1.0,AS_MRC-5_20240313,40,2.963847e+01,37.437440,42.312270,40.760070,87.008580,59.686130,63.014300,...,66.73042,52.52240,72.74024,87.57976,83.77704,96.90976,91.83469,75.79231,80.37989,73.81337
11,1.0,AS_MRC-5_20240313,44,3.233160e+01,40.864090,50.696430,47.396190,89.951510,65.071010,70.047120,...,70.58887,61.80875,84.18870,93.57176,91.87151,99.10272,95.91721,86.64191,87.55087,82.25087
12,1.0,AS_MRC-5_20240313,48,4.629753e+01,59.146160,67.078780,61.639250,96.140660,80.062410,82.528880,...,91.95988,81.14018,95.21348,99.11414,98.29367,99.92898,99.75217,97.25101,97.77644,96.22910
13,1.0,AS_MRC-5_20240313,52,4.080782e+01,59.494030,67.916640,61.055310,94.652730,82.587610,85.340560,...,94.69582,85.68816,96.80226,98.96005,98.36401,99.92542,99.61054,97.77036,98.11680,96.42687
14,1.0,AS_MRC-5_20240313,56,4.453494e+01,63.642990,71.403990,64.586010,94.809330,84.223940,85.663650,...,96.63243,90.13999,98.28036,98.68020,98.93547,99.94585,99.80577,98.33151,98.22613,97.70938
15,1.0,AS_MRC-5_20240313,60,4.835589e+01,67.300380,73.563290,63.860830,94.459680,87.233940,87.012050,...,98.29095,91.38719,98.40868,99.14629,99.01845,99.91457,99.83160,98.60358,98.61007,97.72413
16,1.0,AS_MRC-5_20240313,64,5.218668e+01,71.478230,80.353330,73.799100,95.698210,89.541630,90.201870,...,98.56731,92.27074,99.22032,99.37193,98.84697,99.80140,99.76193,98.68034,99.23015,98.48141
17,1.0,AS_MRC-5_20240313,68,5.708294e+01,75.952380,80.094720,73.927540,94.636630,91.474060,90.970270,...,98.85899,94.98743,98.70145,99.46842,99.06448,99.81567,99.77026,98.97514,98.81071,98.12712
18,1.0,AS_MRC-5_20240313,72,7.839454e+01,91.920680,92.085750,88.786260,99.198390,98.050490,97.349620,...,99.95922,99.72102,99.98804,99.96162,99.97849,99.99323,100.00000,99.98517,99.99857,99.92713
19,NaN,NaN,slope,7.736505e-01,0.995884,1.115366,0.977022,0.822047,1.238010,1.170861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,z.test,2.973968e-07,0.204308,0.921290,0.119008,0.000022,0.999898,0.992941,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,mean,1.039958e+00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,stdev,1.600116e-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,z.score,-1.664300e+00,-0.275444,0.471266,-0.393320,-1.361846,1.237735,0.818085,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,sem,5.333721e-02,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,95 ci,1.144499e+00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,q3,1.163392e+00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,q1,8.995343e-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,1.5*iqr,3.957872e-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,min,-5.037471e-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,max,1.559180e+00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Plate_Number,Vessel_Name,Elapsed,"P20 LIN1-0B-b1 (A1), Image 1","P20 LIN1-0B-b1 (A1), Image 2","P20 LIN1-0B-b1 (A1), Image 3","P20 LIN1-0B-b1 (A1), Image 4","P20 LIN1-0B-b1 (A1), Image 6","P20 LIN1-0B-b1 (A1), Image 7","P20 LIN1-0B-b1 (A1), Image 8",...,"P10 LIN5-0B-b3 (C3), Image 8","P10 LIN5-0B-b3 (C3), Image 9","P10 LIN5-0B-b3 (C4), Image 1","P10 LIN5-0B-b3 (C4), Image 2","P10 LIN5-0B-b3 (C4), Image 3","P10 LIN5-0B-b3 (C4), Image 4","P10 LIN5-0B-b3 (C4), Image 6","P10 LIN5-0B-b3 (C4), Image 7","P10 LIN5-0B-b3 (C4), Image 8","P10 LIN5-0B-b3 (C4), Image 9"
0,1.0,AS_MRC-5_20240313,4,1.370022e+01,17.716070,17.296350,18.042100,21.104470,25.140340,30.419580,...,19.36441,15.45249,14.79670,23.98847,32.30291,24.50298,25.45489,23.20039,21.77953,18.32537
1,1.0,AS_MRC-5_20240313,8,1.463772e+01,18.375150,17.046340,19.791510,20.220990,26.844000,31.502880,...,22.44311,18.82457,16.54188,25.78643,31.80896,26.68330,29.67746,28.86678,23.64510,22.01076
2,1.0,AS_MRC-5_20240313,12,1.313210e+01,18.823890,19.819710,19.826740,22.608780,27.270460,34.557330,...,24.51787,21.14353,18.09188,28.42391,37.00899,29.36483,32.72959,30.47305,28.26028,23.69120
3,1.0,AS_MRC-5_20240313,16,1.318421e+01,20.718420,18.322290,20.089190,26.392390,28.844040,35.515190,...,29.55665,22.26146,18.22026,29.39931,40.33483,33.08198,36.21591,30.77803,33.11140,24.87578
4,1.0,AS_MRC-5_20240313,20,1.547025e+01,22.952910,21.085960,23.228260,29.727380,32.613770,40.579310,...,36.07504,24.01517,22.72577,34.75934,46.19578,36.71526,48.07835,38.70916,38.56288,31.00169
5,1.0,AS_MRC-5_20240313,24,1.639737e+01,25.823860,25.148330,25.560530,35.175650,34.817380,44.017220,...,40.30909,29.80222,27.30830,40.11378,55.10899,44.07670,53.26055,43.06381,42.44953,36.12196
6,1.0,AS_MRC-5_20240313,28,1.962740e+01,27.449330,28.997550,28.801150,41.234420,41.416970,51.995800,...,50.45570,37.20976,30.22542,46.41178,62.42372,53.79835,62.98090,50.15310,52.16469,42.12447
7,1.0,AS_MRC-5_20240313,32,2.261706e+01,30.780090,35.398410,33.435170,47.933570,51.082280,59.191030,...,62.12774,45.47373,38.78162,57.61432,74.12410,66.96979,72.18811,60.29761,62.47507,51.56707
8,1.0,AS_MRC-5_20240313,36,2.671288e+01,34.064960,38.748420,37.972370,52.899430,57.348590,66.310570,...,69.15783,56.28858,44.38347,67.17063,81.80172,76.67517,85.92998,70.13753,71.94984,62.81667
9,1.0,AS_MRC-5_20240313,40,2.963847e+01,37.437440,42.312270,40.760070,59.686130,63.014300,74.004520,...,79.96462,66.73042,52.52240,72.74024,87.57976,83.77704,91.83469,75.79231,80.37989,73.81337
10,1.0,AS_MRC-5_20240313,44,3.233160e+01,40.864090,50.696430,47.396190,65.071010,70.047120,77.387860,...,88.22484,70.58887,61.80875,84.18870,93.57176,91.87151,95.91721,86.64191,87.55087,82.25087
11,1.0,AS_MRC-5_20240313,48,4.629753e+01,59.146160,67.078780,61.639250,80.062410,82.528880,89.629520,...,98.05315,91.95988,81.14018,95.21348,99.11414,98.29367,99.75217,97.25101,97.77644,96.22910
12,1.0,AS_MRC-5_20240313,52,4.080782e+01,59.494030,67.916640,61.055310,82.587610,85.340560,89.286150,...,98.36020,94.69582,85.68816,96.80226,98.96005,98.36401,99.61054,97.77036,98.11680,96.42687
13,1.0,AS_MRC-5_20240313,56,4.453494e+01,63.642990,71.403990,64.586010,84.223940,85.663650,89.867580,...,99.00800,96.63243,90.13999,98.28036,98.68020,98.93547,99.80577,98.33151,98.22613,97.70938
14,1.0,AS_MRC-5_20240313,60,4.835589e+01,67.300380,73.563290,63.860830,87.233940,87.012050,90.309010,...,99.21929,98.29095,91.38719,98.40868,99.14629,99.01845,99.83160,98.60358,98.61007,97.72413
15,1.0,AS_MRC-5_20240313,64,5.218668e+01,71.478230,80.353330,73.799100,89.541630,90.201870,90.860260,...,99.65430,98.56731,92.27074,99.22032,99.37193,98.84697,99.76193,98.68034,99.23015,98.48141
16,1.0,AS_MRC-5_20240313,68,5.708294e+01,75.952380,80.094720,73.927540,91.474060,90.970270,93.195060,...,99.60376,98.85899,94.98743,98.70145,99.46842,99.06448,99.77026,98.97514,98.81071,98.12712
17,1.0,AS_MRC-5_20240313,72,7.839454e+01,91.920680,92.085750,88.786260,98.050490,97.349620,98.366000,...,99.99767,99.95922,99.72102,99.98804,99.96162,99.97849,100.00000,99.98517,99.99857,99.92713
18,NaN,NaN,slope,7.736505e-01,0.995884,1.115366,0.977022,1.238010,1.170861,1.110857,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,z.test,2.973968e-07,0.204308,0.921290,0.119008,0.999898,0.992941,0.908119,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,mean,1.039958e+00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,stdev,1.600116e-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,z.score,-1.664300e+00,-0.275444,0.471266,-0.393320,1.237735,0.818085,0.443087,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,sem,5.333721e-02,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,95 ci,1.144499e+00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,q3,1.163392e+00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,q1,8.995343e-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,1.5*iqr,3.957872e-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,min,-5.037471e-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,max,1.559180e+00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Plate_Number,Vessel_Name,Elapsed,P20 LIN1-0B-b1 (A1),P20 LIN1-0B-b1 (B1),P17 LIN2-0A-b1 (A2),P17 LIN2-0A-b1 (B2),P14 LIN3-0A-b2 (A3),P14 LIN3-0A-b2 (B3),P12 LIN4-0B-b2 (A4),P12 LIN4-0B-b2 (B4),C1,C2,P10 LIN5-0B-b3 (C3),P10 LIN5-0B-b3 (C4)
0,1.0,AS_MRC-5_20240313,4,20.021759,18.021316,32.152679,12.916889,24.541841,21.079869,31.901086,13.265894,17.032940,31.826758,23.107985,23.043905
1,1.0,AS_MRC-5_20240313,8,20.756479,18.137957,33.343212,13.346433,27.592312,23.780141,33.973711,14.791917,17.545873,33.877419,26.193512,25.627584
2,1.0,AS_MRC-5_20240313,12,21.789315,19.331816,36.524350,15.537637,30.519455,25.993291,38.555700,17.217079,18.373919,37.354992,29.424637,28.505466
3,1.0,AS_MRC-5_20240313,16,22.848472,19.108665,39.675745,16.425696,33.762156,29.882112,45.497210,19.649744,18.930658,39.147137,32.338301,30.752187
4,1.0,AS_MRC-5_20240313,20,26.154750,20.556685,45.249935,16.947764,39.445140,34.300853,51.767805,22.553123,20.447750,42.600436,37.975759,37.093529
5,1.0,AS_MRC-5_20240313,24,29.246491,24.936691,52.857083,20.113686,45.959105,40.732365,61.928095,26.423706,23.120259,50.172835,44.369518,42.687952
6,1.0,AS_MRC-5_20240313,28,33.809222,27.444049,60.777354,23.747234,54.751840,47.699571,73.547412,31.269147,26.146615,56.825667,52.091890,50.035304
7,1.0,AS_MRC-5_20240313,32,39.736738,33.445327,71.599707,28.412880,65.659705,58.334918,84.467848,39.207499,30.513419,67.968046,63.236524,60.502211
8,1.0,AS_MRC-5_20240313,36,44.803481,37.575611,79.109641,32.345991,74.719066,67.555896,92.100022,47.515235,35.786423,73.734844,72.091574,70.108126
9,1.0,AS_MRC-5_20240313,40,49.592753,40.155701,85.044359,35.844299,81.312952,74.686950,95.162323,54.903931,38.123386,76.472599,80.979512,77.304963
10,1.0,AS_MRC-5_20240313,44,54.725425,43.626581,87.565016,41.848492,88.162400,83.107931,97.029971,63.094212,42.564671,82.431465,87.208435,85.475198
11,1.0,AS_MRC-5_20240313,48,69.596251,65.015557,96.184489,56.996436,97.402355,95.319519,99.685874,82.680721,60.561911,95.469514,97.238544,95.596274
12,1.0,AS_MRC-5_20240313,52,69.662931,61.440826,94.818240,60.194635,97.062490,95.646327,99.502870,85.718444,58.122771,92.248771,97.917205,96.467381
13,1.0,AS_MRC-5_20240313,56,72.199131,63.085925,94.186836,63.983348,97.867779,97.177270,99.480835,90.006176,62.480022,92.810319,98.500240,97.513601
14,1.0,AS_MRC-5_20240313,60,74.206666,64.632780,94.463690,70.982978,98.245432,97.782133,99.500696,92.933932,65.709592,93.109706,98.951619,97.841249
15,1.0,AS_MRC-5_20240313,64,78.546320,68.295199,94.929059,77.811739,98.337091,98.264490,99.425429,95.272595,70.045436,93.030278,99.099139,98.232974
16,1.0,AS_MRC-5_20240313,68,80.420623,69.549985,95.291855,82.655761,98.440594,98.615127,99.276620,96.294230,71.924130,93.278762,99.149928,98.488126
17,1.0,AS_MRC-5_20240313,72,92.446566,92.882135,99.222124,95.139839,99.877602,99.884301,99.965915,99.616055,92.873069,99.388517,99.974724,99.945005
18,NaN,NaN,slope,1.067197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,z.test,0.641340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,mean,1.039958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,stdev,0.160012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,z.score,0.170231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,sem,0.053337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,95 ci,1.144499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,q3,1.163392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,q1,0.899534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,1.5*iqr,0.395787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,min,-0.503747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,max,1.559180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Plate_Number,Vessel_Name,Elapsed,P20 LIN1-0B-b1,P17 LIN2-0A-b1,P14 LIN3-0A-b2,P12 LIN4-0B-b2,C1,P10 LIN5-0B-b3
0,1.0,AS_MRC-5_20240313,4,19.021538,22.534784,22.810855,22.583490,24.429849,23.075945
1,1.0,AS_MRC-5_20240313,8,19.447218,23.344823,25.686227,24.382814,25.711646,25.910548
2,1.0,AS_MRC-5_20240313,12,20.560566,26.030993,28.256373,27.886389,27.864456,28.965052
3,1.0,AS_MRC-5_20240313,16,20.978569,28.050721,31.822134,32.573477,29.038898,31.545244
4,1.0,AS_MRC-5_20240313,20,23.355718,31.098849,36.872996,37.160464,31.524093,37.534644
5,1.0,AS_MRC-5_20240313,24,27.091591,36.485384,43.345735,44.175901,36.646547,43.528735
6,1.0,AS_MRC-5_20240313,28,30.626636,42.262294,51.225706,52.408280,41.486141,51.063597
7,1.0,AS_MRC-5_20240313,32,36.591032,50.006294,61.997311,61.837673,49.240733,61.869367
8,1.0,AS_MRC-5_20240313,36,41.189546,55.727816,71.137481,69.807629,54.760633,71.099850
9,1.0,AS_MRC-5_20240313,40,44.874227,60.444329,77.999951,75.033127,57.297992,79.142237
10,1.0,AS_MRC-5_20240313,44,49.176003,64.706754,85.635166,80.062092,62.498068,86.341816
11,1.0,AS_MRC-5_20240313,48,67.305904,76.590463,96.360937,91.183298,78.015713,96.417409
12,1.0,AS_MRC-5_20240313,52,65.551879,77.506438,96.354409,92.610657,75.185771,97.192293
13,1.0,AS_MRC-5_20240313,56,67.642528,79.085092,97.522524,94.743506,77.645171,98.006921
14,1.0,AS_MRC-5_20240313,60,69.419723,82.723334,98.013782,96.217314,79.409649,98.396434
15,1.0,AS_MRC-5_20240313,64,73.420759,86.370399,98.300791,97.349012,81.537857,98.666056
16,1.0,AS_MRC-5_20240313,68,74.985304,88.973808,98.527861,97.785425,82.601446,98.819027
17,1.0,AS_MRC-5_20240313,72,92.664351,97.180981,99.880952,99.790985,96.130793,99.959864
18,NaN,NaN,slope,1.067197,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,z.test,0.641340,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,mean,1.039958,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,stdev,0.160012,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,z.score,0.170231,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,sem,0.053337,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,95 ci,1.144499,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,q3,1.163392,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,q1,0.899534,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,1.5*iqr,0.395787,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,min,-0.503747,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,max,1.559180,NaN,NaN,NaN,NaN,NaN

Wrote replaced data to: /Users/allielas/HTP_fibroblasts_mitolyso/proliferation_growth_curves/Incucyte_sheets/r1_processed.xlsx

/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Plate_Number,Vessel_Name,Elapsed,"P23 LIN1-0B-b1 (A1), Image 1","P23 LIN1-0B-b1 (A1), Image 2","P23 LIN1-0B-b1 (A1), Image 3","P23 LIN1-0B-b1 (A1), Image 4","P23 LIN1-0B-b1 (A1), Image 5","P23 LIN1-0B-b1 (A1), Image 6","P23 LIN1-0B-b1 (A1), Image 7",...,"P13 LIN5-0B-b3 (C3), Image 9","P13 LIN5-0B-b3 (C4), Image 1","P13 LIN5-0B-b3 (C4), Image 2","P13 LIN5-0B-b3 (C4), Image 3","P13 LIN5-0B-b3 (C4), Image 4","P13 LIN5-0B-b3 (C4), Image 5","P13 LIN5-0B-b3 (C4), Image 6","P13 LIN5-0B-b3 (C4), Image 7","P13 LIN5-0B-b3 (C4), Image 8","P13 LIN5-0B-b3 (C4), Image 9"
0,2,AS_MRC-5_20240326,0,15.64508,12.01923,22.59595,20.63824,18.46687,10.033460,25.28334,...,27.13321,27.36219,27.45439,42.86734,24.77935,35.32397,25.86115,39.61599,31.06370,20.35375
1,2,AS_MRC-5_20240326,2,12.87492,11.76498,19.09323,18.29190,16.59576,10.657780,22.65666,...,24.43653,23.97133,25.21621,39.49239,21.80029,32.49297,19.54416,33.71510,28.07727,17.49918
2,2,AS_MRC-5_20240326,4,14.20407,13.71094,20.96939,19.70211,20.70415,10.387620,25.04583,...,26.54823,26.37928,26.33945,41.86824,24.14690,34.91101,23.39707,35.31687,29.58466,17.73396
3,2,AS_MRC-5_20240326,6,10.50487,10.70183,16.76580,15.62343,15.46834,9.592301,20.73822,...,20.30745,20.50699,19.42403,32.17412,20.41589,27.11456,16.74941,27.01984,22.89608,13.49746
4,2,AS_MRC-5_20240326,8,13.22600,13.04783,20.14409,18.10274,20.85200,10.725320,21.78431,...,24.27290,25.11132,23.89026,37.37994,23.10130,33.11216,22.54227,33.94709,27.31007,18.58856
5,2,AS_MRC-5_20240326,10,10.38981,11.10754,16.23921,15.09076,16.49776,8.126912,19.01743,...,21.37600,21.81900,21.46737,36.03987,20.26518,28.41278,20.02745,31.38822,24.27263,15.00471
6,2,AS_MRC-5_20240326,12,13.33820,12.61582,18.22614,17.81988,18.25107,9.745411,21.42694,...,27.26822,28.48851,26.17857,44.62146,24.75688,37.85313,25.29467,36.89658,31.12045,19.64421
7,2,AS_MRC-5_20240326,14,11.04492,10.94692,15.18862,14.71338,15.22242,8.692430,19.90863,...,22.19884,22.41539,22.45889,39.43325,21.35359,32.18579,20.93470,33.45908,28.30132,16.88859
8,2,AS_MRC-5_20240326,16,13.96395,13.38505,19.59394,20.14095,19.59681,10.528850,23.16140,...,31.81135,31.62020,31.81033,50.63203,29.33894,44.03246,29.67937,44.16283,36.86045,24.06372
9,2,AS_MRC-5_20240326,18,11.48588,11.46033,16.75816,15.28375,17.05747,8.755054,21.14114,...,24.88561,25.49859,24.55618,46.04916,23.60208,37.02046,22.58570,35.03005,29.08100,15.43488
10,2,AS_MRC-5_20240326,20,14.60391,12.71539,21.75631,20.27589,22.80410,11.802200,25.92828,...,33.95876,34.00835,32.10815,53.98266,31.58046,49.08544,31.25252,46.48075,37.20177,24.53131
11,2,AS_MRC-5_20240326,22,19.75941,15.70927,25.03640,25.89516,29.94742,15.508900,30.87863,...,42.40938,42.72453,41.65271,66.05017,38.60516,61.48840,40.08741,56.46341,45.83397,30.48179
12,2,AS_MRC-5_20240326,24,19.57680,16.01822,24.24579,24.91483,29.09344,16.826990,32.40269,...,44.86013,44.51739,44.74718,68.97747,40.48767,65.09977,40.69603,61.58374,50.11478,32.41388
13,2,AS_MRC-5_20240326,26,16.89706,14.28861,20.73106,22.39073,24.96169,13.899630,28.75403,...,41.24727,41.61133,43.12923,68.86275,40.31230,61.61837,38.53502,59.59859,47.48396,31.76136
14,2,AS_MRC-5_20240326,28,17.79891,15.95758,24.50270,25.10605,27.83025,15.535880,32.95059,...,47.51174,48.25230,48.81473,75.67942,45.11759,69.14964,45.29454,66.00749,54.13352,34.53904
15,2,AS_MRC-5_20240326,30,16.05585,14.64727,21.66084,23.19957,24.34352,14.568540,30.37436,...,42.46974,45.98312,44.41407,72.29062,42.97633,66.54570,41.78239,62.97209,49.45059,29.73025
16,2,AS_MRC-5_20240326,32,20.22352,17.89608,28.27148,28.32358,30.44976,19.354850,38.14705,...,52.92784,54.18768,54.97433,80.82379,54.49628,76.46477,51.96787,71.97429,59.62617,37.55012
17,2,AS_MRC-5_20240326,34,16.89774,15.46206,24.54074,25.08372,26.95046,16.607090,31.44470,...,51.45760,52.35091,51.58878,77.71013,51.69717,72.49181,50.28777,71.33891,56.83847,35.03127
18,2,AS_MRC-5_20240326,36,21.69205,21.08446,32.02736,31.06486,34.75572,21.030240,41.45535,...,62.84439,65.15037,64.58978,89.73551,62.92709,84.79765,62.65618,83.00795,68.03260,45.93265
19,2,AS_MRC-5_20240326,38,19.23623,18.90987,26.37190,26.76586,28.85940,17.616910,34.97631,...,59.00657,62.43048,62.79132,86.48492,59.53500,82.22409,59.35826,81.59541,66.92628,42.83292
20,2,AS_MRC-5_20240326,40,23.16734,23.36798,30.58484,34.06120,36.03754,23.597370,44.23309,...,72.21304,73.62066,71.53040,93.95623,71.99184,90.62916,72.99258,90.05524,77.08089,51.91277
21,2,AS_MRC-5_20240326,42,18.24287,18.21583,25.60956,26.50876,31.69820,19.633690,38.39120,...,66.77871,69.98170,68.33028,89.43509,67.98609,87.01383,66.35278,88.82607,75.13747,48.69987
22,2,AS_MRC-5_20240326,44,26.93974,26.03741,32.31104,35.43733,41.15542,26.223780,48.41121,...,79.28294,82.69859,79.77033,96.53156,78.39803,94.94789,80.86435,95.85760,84.29789,59.77593
23,2,AS_MRC-5_20240326,46,19.90064,19.24129,26.21230,28.79732,36.12605,19.886090,38.22340,...,73.39864,78.31396,76.76197,93.33212,76.27028,93.28658,74.83958,93.55202,81.44810,57.96868
24,2,AS_MRC-5_20240326,48,27.07093,27.00072,32.88475,38.76113,45.05798,30.143340,50.65861,...,86.96992,89.72246,90.01324,98.89866,88.61198,98.23418,89.62672,98.77191,93.05733,71.23606
25,2,AS_MRC-5_20240326,50,21.80077,20.31544,26.19065,31.17413,37.98992,24.338260,41.41731,...,82.65173,84.75264,86.64650,96.21134,83.39174,94.03532,83.77192,96.23347,87.64668,67.25285
26,2,AS_MRC-5_20240326,52,30.29406,26.85130,34.53009,41.37893,48.23672,32.116340,58.55140,...,94.02555,95.42915,95.68591,99.35683,95.14019,99.15401,95.54243,99.68040,97.29130,81.17139
27,2,AS_MRC-5_20240326,54,22.10726,22.66792,27.01007,33.00973,39.56341,25.083930,46.46703,...,90.95592,93.25632,92.24581,96.73808,92.07332,97.76489,92.94150,98.15525,94.64625,77.53674
28,2,AS_MRC-5_20240326,56,32.92641,32.06157,41.73077,45.88717,55.93313,35.710160,63.28009,...,98.62988,98.64414,98.54450,99.83855,98.72643,99.70403,98.11516,99.86614,99.43995,92.39516
29,2,AS_MRC-5_20240326,58,24.38838,25.71972,30.79498,36.17010,44.69590,28.174310,51.60676,...,95.59434,96.13021,95.65887,98.82697,95.43193,98.88835,95.68011,98.94128,98.76740,88.51173
30,2,AS_MRC-5_20240326,60,32.63836,34.95848,41.71363,47.83469,57.25148,39.424160,66.43882,...,99.49403,99.40388,99.06742,99.89107,99.60821,99.95404,99.47423,99.90466,99.87981,96.93229
31,2,AS_MRC-5_20240326,62,26.79005,27.60748,32.64908,35.78015,46.27636,30.408450,53.94682,...,97.24842,98.30548,97.99114,99.30344,98.01498,99.41051,98.68846,99.67978,99.13332,95.09853
32,2,AS_MRC-5_20240326,64,34.62207,37.94614,43.85619,52.15533,57.10241,41.808000,67.52165,...,99.79895,99.76725,99.56232,99.81240,99.81042,99.94202,99.74321,99.99631,99.89128,99.13768
33,2,AS_MRC-5_20240326,66,31.99608,38.59033,43.67167,52.26973,59.97569,40.563740,67.40957,...,99.74807,99.79102,99.63949,99.86710,99.67459,99.82352,99.71236,100.00000,99.88301,99.00719
34,2,AS_MRC-5_20240326,68,36.45289,39.92508,47.15111,53.50067,61.69361,43.597440,68.96798,...,99.76903,99.94666,99.61757,99.83303,99.89967,99.93205,99.87120,99.98087,99.90117,99.62241
35,2,AS_MRC-5_20240326,70,29.71359,35.53315,42.05849,46.79503,54.22606,37.820690,61.33385,...,98.84000,99.40743,99.48003,99.07315,99.63914,99.70388,99.59797,99.95636,99.76139,99.28983
36,2,AS_MRC-5_20240326,72,33.11025,37.40234,40.86982,50.50884,58.33343,41.053120,66.20431,...,99.28028,99.84395,99.72417,99.38305,99.63177,99.85686,99.79411,99.97036,99.83951,99.49409

,Plate_Number,Vessel_Name,Elapsed,"P23 LIN1-0B-b1 (A1), Image 1","P23 LIN1-0B-b1 (A1), Image 2","P23 LIN1-0B-b1 (A1), Image 3","P23 LIN1-0B-b1 (A1), Image 4","P23 LIN1-0B-b1 (A1), Image 6","P23 LIN1-0B-b1 (A1), Image 7","P23 LIN1-0B-b1 (A1), Image 8",...,"P13 LIN5-0B-b3 (C3), Image 8","P13 LIN5-0B-b3 (C3), Image 9","P13 LIN5-0B-b3 (C4), Image 1","P13 LIN5-0B-b3 (C4), Image 2","P13 LIN5-0B-b3 (C4), Image 3","P13 LIN5-0B-b3 (C4), Image 4","P13 LIN5-0B-b3 (C4), Image 6","P13 LIN5-0B-b3 (C4), Image 7","P13 LIN5-0B-b3 (C4), Image 8","P13 LIN5-0B-b3 (C4), Image 9"
0,2,AS_MRC-5_20240326,4,14.20407,13.71094,20.96939,19.70211,10.387620,25.04583,20.70251,...,21.37689,26.54823,26.37928,26.33945,41.86824,24.14690,23.39707,35.31687,29.58466,17.73396
1,2,AS_MRC-5_20240326,6,10.50487,10.70183,16.76580,15.62343,9.592301,20.73822,16.39566,...,16.51394,20.30745,20.50699,19.42403,32.17412,20.41589,16.74941,27.01984,22.89608,13.49746
2,2,AS_MRC-5_20240326,8,13.22600,13.04783,20.14409,18.10274,10.725320,21.78431,18.37713,...,20.84449,24.27290,25.11132,23.89026,37.37994,23.10130,22.54227,33.94709,27.31007,18.58856
3,2,AS_MRC-5_20240326,10,10.38981,11.10754,16.23921,15.09076,8.126912,19.01743,15.59338,...,19.53623,21.37600,21.81900,21.46737,36.03987,20.26518,20.02745,31.38822,24.27263,15.00471
4,2,AS_MRC-5_20240326,12,13.33820,12.61582,18.22614,17.81988,9.745411,21.42694,17.29622,...,22.30796,27.26822,28.48851,26.17857,44.62146,24.75688,25.29467,36.89658,31.12045,19.64421
5,2,AS_MRC-5_20240326,14,11.04492,10.94692,15.18862,14.71338,8.692430,19.90863,16.03201,...,16.94712,22.19884,22.41539,22.45889,39.43325,21.35359,20.93470,33.45908,28.30132,16.88859
6,2,AS_MRC-5_20240326,16,13.96395,13.38505,19.59394,20.14095,10.528850,23.16140,19.65076,...,28.40124,31.81135,31.62020,31.81033,50.63203,29.33894,29.67937,44.16283,36.86045,24.06372
7,2,AS_MRC-5_20240326,18,11.48588,11.46033,16.75816,15.28375,8.755054,21.14114,15.89488,...,20.56770,24.88561,25.49859,24.55618,46.04916,23.60208,22.58570,35.03005,29.08100,15.43488
8,2,AS_MRC-5_20240326,20,14.60391,12.71539,21.75631,20.27589,11.802200,25.92828,20.56039,...,29.31080,33.95876,34.00835,32.10815,53.98266,31.58046,31.25252,46.48075,37.20177,24.53131
9,2,AS_MRC-5_20240326,22,19.75941,15.70927,25.03640,25.89516,15.508900,30.87863,24.52073,...,36.40303,42.40938,42.72453,41.65271,66.05017,38.60516,40.08741,56.46341,45.83397,30.48179
10,2,AS_MRC-5_20240326,24,19.57680,16.01822,24.24579,24.91483,16.826990,32.40269,24.80660,...,38.08723,44.86013,44.51739,44.74718,68.97747,40.48767,40.69603,61.58374,50.11478,32.41388
11,2,AS_MRC-5_20240326,26,16.89706,14.28861,20.73106,22.39073,13.899630,28.75403,20.48159,...,35.07061,41.24727,41.61133,43.12923,68.86275,40.31230,38.53502,59.59859,47.48396,31.76136
12,2,AS_MRC-5_20240326,28,17.79891,15.95758,24.50270,25.10605,15.535880,32.95059,22.78819,...,39.95356,47.51174,48.25230,48.81473,75.67942,45.11759,45.29454,66.00749,54.13352,34.53904
13,2,AS_MRC-5_20240326,30,16.05585,14.64727,21.66084,23.19957,14.568540,30.37436,22.08759,...,36.79837,42.46974,45.98312,44.41407,72.29062,42.97633,41.78239,62.97209,49.45059,29.73025
14,2,AS_MRC-5_20240326,32,20.22352,17.89608,28.27148,28.32358,19.354850,38.14705,27.12140,...,45.04644,52.92784,54.18768,54.97433,80.82379,54.49628,51.96787,71.97429,59.62617,37.55012
15,2,AS_MRC-5_20240326,34,16.89774,15.46206,24.54074,25.08372,16.607090,31.44470,23.19002,...,39.55249,51.45760,52.35091,51.58878,77.71013,51.69717,50.28777,71.33891,56.83847,35.03127
16,2,AS_MRC-5_20240326,36,21.69205,21.08446,32.02736,31.06486,21.030240,41.45535,29.24989,...,52.53632,62.84439,65.15037,64.58978,89.73551,62.92709,62.65618,83.00795,68.03260,45.93265
17,2,AS_MRC-5_20240326,38,19.23623,18.90987,26.37190,26.76586,17.616910,34.97631,25.90445,...,48.35268,59.00657,62.43048,62.79132,86.48492,59.53500,59.35826,81.59541,66.92628,42.83292
18,2,AS_MRC-5_20240326,40,23.16734,23.36798,30.58484,34.06120,23.597370,44.23309,32.25401,...,61.34396,72.21304,73.62066,71.53040,93.95623,71.99184,72.99258,90.05524,77.08089,51.91277
19,2,AS_MRC-5_20240326,42,18.24287,18.21583,25.60956,26.50876,19.633690,38.39120,25.91715,...,55.89187,66.77871,69.98170,68.33028,89.43509,67.98609,66.35278,88.82607,75.13747,48.69987
20,2,AS_MRC-5_20240326,44,26.93974,26.03741,32.31104,35.43733,26.223780,48.41121,33.89245,...,70.03735,79.28294,82.69859,79.77033,96.53156,78.39803,80.86435,95.85760,84.29789,59.77593
21,2,AS_MRC-5_20240326,46,19.90064,19.24129,26.21230,28.79732,19.886090,38.22340,27.94102,...,64.72778,73.39864,78.31396,76.76197,93.33212,76.27028,74.83958,93.55202,81.44810,57.96868
22,2,AS_MRC-5_20240326,48,27.07093,27.00072,32.88475,38.76113,30.143340,50.65861,37.11033,...,80.59590,86.96992,89.72246,90.01324,98.89866,88.61198,89.62672,98.77191,93.05733,71.23606
23,2,AS_MRC-5_20240326,50,21.80077,20.31544,26.19065,31.17413,24.338260,41.41731,29.39323,...,70.79416,82.65173,84.75264,86.64650,96.21134,83.39174,83.77192,96.23347,87.64668,67.25285
24,2,AS_MRC-5_20240326,52,30.29406,26.85130,34.53009,41.37893,32.116340,58.55140,43.15068,...,89.38100,94.02555,95.42915,95.68591,99.35683,95.14019,95.54243,99.68040,97.29130,81.17139
25,2,AS_MRC-5_20240326,54,22.10726,22.66792,27.01007,33.00973,25.083930,46.46703,33.02707,...,85.18507,90.95592,93.25632,92.24581,96.73808,92.07332,92.94150,98.15525,94.64625,77.53674
26,2,AS_MRC-5_20240326,56,32.92641,32.06157,41.73077,45.88717,35.710160,63.28009,46.85547,...,97.05651,98.62988,98.64414,98.54450,99.83855,98.72643,98.11516,99.86614,99.43995,92.39516
27,2,AS_MRC-5_20240326,58,24.38838,25.71972,30.79498,36.17010,28.174310,51.60676,37.29718,...,92.16012,95.59434,96.13021,95.65887,98.82697,95.43193,95.68011,98.94128,98.76740,88.51173
28,2,AS_MRC-5_20240326,60,32.63836,34.95848,41.71363,47.83469,39.424160,66.43882,52.54166,...,99.02671,99.49403,99.40388,99.06742,99.89107,99.60821,99.47423,99.90466,99.87981,96.93229
29,2,AS_MRC-5_20240326,62,26.79005,27.60748,32.64908,35.78015,30.408450,53.94682,41.52016,...,96.90948,97.24842,98.30548,97.99114,99.30344,98.01498,98.68846,99.67978,99.13332,95.09853
30,2,AS_MRC-5_20240326,64,34.62207,37.94614,43.85619,52.15533,41.808000,67.52165,53.78291,...,99.50728,99.79895,99.76725,99.56232,99.81240,99.81042,99.74321,99.99631,99.89128,99.13768
31,2,AS_MRC-5_20240326,66,31.99608,38.59033,43.67167,52.26973,40.563740,67.40957,52.49065,...,99.48358,99.74807,99.79102,99.63949,99.86710,99.67459,99.71236,100.00000,99.88301,99.00719
32,2,AS_MRC-5_20240326,68,36.45289,39.92508,47.15111,53.50067,43.597440,68.96798,54.53350,...,99.71822,99.76903,99.94666,99.61757,99.83303,99.89967,99.87120,99.98087,99.90117,99.62241
33,2,AS_MRC-5_20240326,70,29.71359,35.53315,42.05849,46.79503,37.820690,61.33385,45.93108,...,99.35738,98.84000,99.40743,99.48003,99.07315,99.63914,99.59797,99.95636,99.76139,99.28983
34,2,AS_MRC-5_20240326,72,33.11025,37.40234,40.86982,50.50884,41.053120,66.20431,50.44287,...,99.37841,99.28028,99.84395,99.72417,99.38305,99.63177,99.79411,99.97036,99.83951,99.49409

,Plate_Number,Vessel_Name,Elapsed,P23 LIN1-0B-b1 (A1),P23 LIN1-0B-b1 (B1),P20 LIN2-0A-b1 (A2),P20 LIN2-0A-b1 (B2),P13 LIN5-0B-b3 LIN3-0A-b2 (A3),P13 LIN5-0B-b3 LIN3-0A-b2 (B3),P15 LIN4-0B-b2 (A4),P15 LIN4-0B-b2 (B4),P11 LIN6-0C-b1 (C1),P11 LIN6-0C-b1 (C2),P13 LIN5-0B-b3 (C3),P13 LIN5-0B-b3 (C4)
0,2,AS_MRC-5_20240326,4,18.146674,15.402626,20.085594,39.923559,22.406209,22.661626,24.026647,26.941794,34.155594,25.123666,27.361941,28.095804
1,2,AS_MRC-5_20240326,6,14.618054,11.631131,15.855191,31.374411,16.931485,16.920201,19.227506,21.175790,25.768940,19.013134,20.948262,21.585477
2,2,AS_MRC-5_20240326,8,16.781484,14.590220,19.773811,40.015499,20.209620,21.910893,24.515988,27.119219,32.464016,24.024484,25.982256,26.483851
3,2,AS_MRC-5_20240326,10,13.849552,10.345645,16.335614,31.971461,17.451334,16.882050,20.398350,21.849142,24.981099,19.515363,23.079364,23.785554
4,2,AS_MRC-5_20240326,12,16.024119,13.171967,19.089951,38.381973,20.905504,21.112409,25.285541,27.067196,33.506961,24.645780,28.573808,29.625166
5,2,AS_MRC-5_20240326,14,14.046134,9.908276,15.886093,30.198605,17.330059,16.189886,21.757446,21.243511,27.011433,19.908665,23.700513,25.655601
6,2,AS_MRC-5_20240326,16,17.677069,14.110996,21.848409,43.365092,24.554178,24.308661,29.948456,30.559660,39.224528,30.059763,33.833279,34.770984
7,2,AS_MRC-5_20240326,18,14.753579,10.492370,17.194727,32.596911,18.590984,17.238367,23.224183,23.506186,29.730537,22.305076,26.565018,27.729705
8,2,AS_MRC-5_20240326,20,18.539046,15.477593,23.278270,46.558289,25.696356,25.087871,32.506837,32.997601,41.942744,30.942473,35.761794,36.393246
9,2,AS_MRC-5_20240326,22,22.905100,20.907706,29.895496,59.142749,32.725814,33.245345,40.775369,43.196909,51.757929,38.829616,43.436421,45.237394
10,2,AS_MRC-5_20240326,24,23.269904,20.964225,30.850199,59.754661,34.022886,34.370284,43.516360,45.467913,55.122066,40.864356,45.882416,47.942267
11,2,AS_MRC-5_20240326,26,20.165896,17.050071,27.586266,53.012156,31.665525,30.636866,39.801995,41.695154,52.189214,37.574675,44.360710,46.411818
12,2,AS_MRC-5_20240326,28,22.793993,20.495013,31.423467,59.923759,36.466549,36.116190,44.887291,47.766644,59.280866,42.973811,49.826715,52.229829
13,2,AS_MRC-5_20240326,30,20.996672,16.285639,28.343385,50.924549,32.754911,29.754178,40.288484,42.136280,52.222787,38.541983,46.143890,48.699932
14,2,AS_MRC-5_20240326,32,26.236698,22.916547,36.097631,65.803673,41.409588,40.158880,50.851570,54.432634,66.676117,48.837780,55.728439,58.200066
15,2,AS_MRC-5_20240326,34,22.508331,17.446544,31.510579,54.542816,36.818697,34.953226,46.367860,48.714787,59.753858,43.405540,53.326165,55.855426
16,2,AS_MRC-5_20240326,36,28.863790,25.822847,42.344156,72.223986,47.987752,46.494585,58.267949,62.956146,73.941735,56.141553,64.730955,67.754016
17,2,AS_MRC-5_20240326,38,24.620941,18.984016,34.150816,60.124169,43.013531,39.904824,52.889715,56.032407,66.925385,50.707076,61.714836,65.244324
18,2,AS_MRC-5_20240326,40,30.768485,27.508598,46.264785,75.568895,54.829853,52.254696,64.555305,69.661435,81.286896,62.495067,73.871649,75.392576
19,2,AS_MRC-5_20240326,42,25.098741,18.374512,38.058149,61.008995,48.521451,42.891177,58.594125,62.708275,71.767636,54.642655,69.778605,71.843669
20,2,AS_MRC-5_20240326,44,33.365854,29.072151,50.498685,78.827662,62.203869,57.467525,71.125204,77.502860,86.899246,68.984636,81.261198,82.274285
21,2,AS_MRC-5_20240326,46,26.311410,18.858060,39.580785,61.947171,53.943511,47.474065,64.617122,67.531569,77.093220,61.635562,77.381356,79.060839
22,2,AS_MRC-5_20240326,48,35.323289,31.376570,56.464320,83.016537,71.589591,65.647617,80.293991,85.241168,93.038834,77.891892,89.579654,89.992295
23,2,AS_MRC-5_20240326,50,28.312372,19.342715,42.632490,63.868859,59.512015,53.278312,71.505926,73.505021,83.363289,68.736961,85.727688,85.738392
24,2,AS_MRC-5_20240326,52,38.688484,34.272195,62.248437,84.524520,80.043465,75.378100,87.701932,91.206571,96.174831,86.688923,95.531766,94.912200
25,2,AS_MRC-5_20240326,54,30.454757,21.276070,49.438023,68.538506,71.414075,62.730413,81.773819,81.393894,88.751744,78.971935,92.735888,92.199159
26,2,AS_MRC-5_20240326,56,43.268052,38.848579,69.770413,89.381639,88.301202,84.567250,93.606773,95.818934,98.370998,94.050989,98.703300,98.196254
27,2,AS_MRC-5_20240326,58,33.952503,24.692990,55.587865,72.052863,79.675870,72.577864,88.644640,88.478395,92.670731,87.776633,96.533542,95.993562
28,2,AS_MRC-5_20240326,60,45.544364,41.873761,73.885726,90.823840,92.803977,90.314025,97.132610,97.584815,99.125925,97.435917,99.550042,99.270196
29,2,AS_MRC-5_20240326,62,36.166975,26.696070,58.776761,75.450026,84.279185,79.670289,92.656661,91.391141,95.609835,92.112989,98.324389,98.276891
30,2,AS_MRC-5_20240326,64,47.999212,42.591312,76.512431,90.781041,95.049394,92.878651,97.891954,97.900141,99.283417,98.470718,99.786990,99.715109
31,2,AS_MRC-5_20240326,66,47.333241,39.661224,73.439797,89.166034,94.423534,92.618164,97.920191,97.556845,98.835741,98.229660,99.741679,99.696845
32,2,AS_MRC-5_20240326,68,49.977139,42.612174,77.102544,90.515387,95.684085,94.390940,98.461756,97.891752,99.149984,98.742551,99.806135,99.834072
33,2,AS_MRC-5_20240326,70,43.428303,31.944186,67.488788,80.625082,91.396044,88.067161,97.026804,95.800973,97.069830,96.713849,99.454385,99.525663
34,2,AS_MRC-5_20240326,72,46.312879,35.720683,70.155393,85.196562,93.975315,91.628929,97.880648,96.863506,98.238121,97.656675,99.606138,99.710126

,Plate_Number,Vessel_Name,Elapsed,P23 LIN1-0B-b1,P20 LIN2-0A-b1,P13 LIN5-0B-b3 LIN3-0A-b2,P15 LIN4-0B-b2,P11 LIN6-0C-b1,P13 LIN5-0B-b3
0,2,AS_MRC-5_20240326,4,16.774650,30.004576,22.533917,25.484221,29.639630,27.728873
1,2,AS_MRC-5_20240326,6,13.124593,23.614801,16.925843,20.201648,22.391037,21.266870
2,2,AS_MRC-5_20240326,8,15.685852,29.894655,21.060256,25.817603,28.244250,26.233054
3,2,AS_MRC-5_20240326,10,12.097598,24.153537,17.166692,21.123746,22.248231,23.432459
4,2,AS_MRC-5_20240326,12,14.598043,28.735962,21.008956,26.176369,29.076371,29.099487
5,2,AS_MRC-5_20240326,14,11.977205,23.042349,16.759972,21.500479,23.460049,24.678057
6,2,AS_MRC-5_20240326,16,15.894032,32.606751,24.431419,30.254058,34.642145,34.302131
7,2,AS_MRC-5_20240326,18,12.622975,24.895819,17.914676,23.365184,26.017807,27.147361
8,2,AS_MRC-5_20240326,20,17.008319,34.918279,25.392114,32.752219,36.442608,36.077520
9,2,AS_MRC-5_20240326,22,21.906403,44.519123,32.985579,41.986139,45.293773,44.336908
10,2,AS_MRC-5_20240326,24,22.117064,45.302430,34.196585,44.492136,47.993211,46.912342
11,2,AS_MRC-5_20240326,26,18.607984,40.299211,31.151196,40.748574,44.881944,45.386264
12,2,AS_MRC-5_20240326,28,21.644503,45.673613,36.291369,46.326968,51.127339,51.028272
13,2,AS_MRC-5_20240326,30,18.641156,39.633967,31.254544,41.212382,45.382385,47.421911
14,2,AS_MRC-5_20240326,32,24.576622,50.950652,40.784234,52.642102,57.756949,56.964253
15,2,AS_MRC-5_20240326,34,19.977438,43.026697,35.885962,47.541324,51.579699,54.590796
16,2,AS_MRC-5_20240326,36,27.343319,57.284071,47.241169,60.612048,65.041644,66.242486
17,2,AS_MRC-5_20240326,38,21.802479,47.137493,41.459177,54.461061,58.816231,63.479580
18,2,AS_MRC-5_20240326,40,29.138541,60.916840,53.542274,67.108370,71.890982,74.632113
19,2,AS_MRC-5_20240326,42,21.736627,49.533572,45.706314,60.651200,63.205146,70.811137
20,2,AS_MRC-5_20240326,44,31.219002,64.663174,59.835697,74.314032,77.941941,81.767741
21,2,AS_MRC-5_20240326,46,22.584735,50.763978,50.708788,66.074346,69.364391,78.221097
22,2,AS_MRC-5_20240326,48,33.349929,69.740429,68.618604,82.767579,85.465363,89.785974
23,2,AS_MRC-5_20240326,50,23.827544,53.250674,56.395164,72.505474,76.050125,85.733040
24,2,AS_MRC-5_20240326,52,36.480339,73.386479,77.710782,89.454252,91.431877,95.221983
25,2,AS_MRC-5_20240326,54,25.865414,58.988264,67.072244,81.583856,83.861839,92.467523
26,2,AS_MRC-5_20240326,56,41.058316,79.576026,86.434226,94.712853,96.210993,98.449777
27,2,AS_MRC-5_20240326,58,29.322746,63.820364,76.126867,88.561518,90.223682,96.263553
28,2,AS_MRC-5_20240326,60,43.709063,82.354783,91.559001,97.358712,98.280921,99.410119
29,2,AS_MRC-5_20240326,62,31.431522,67.113394,81.974737,92.023901,93.861412,98.300640
30,2,AS_MRC-5_20240326,64,45.295262,83.646736,93.964022,97.896048,98.877068,99.751049
31,2,AS_MRC-5_20240326,66,43.497232,81.302916,93.520849,97.738518,98.532701,99.719262
32,2,AS_MRC-5_20240326,68,46.294656,83.808966,95.037512,98.176754,98.946268,99.820104
33,2,AS_MRC-5_20240326,70,37.686244,74.056935,89.731603,96.413888,96.891839,99.490024
34,2,AS_MRC-5_20240326,72,41.016781,77.675978,92.802122,97.372077,97.947398,99.658132

Wrote replaced data to: /Users/allielas/HTP_fibroblasts_mitolyso/proliferation_growth_curves/Incucyte_sheets/r2_processed.xlsx

/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Plate_Number,Vessel_Name,Elapsed,"P25 LIN2-0A-b1-s1 (A1), Image 1","P25 LIN2-0A-b1-s1 (A1), Image 2","P25 LIN2-0A-b1-s1 (A1), Image 3","P25 LIN2-0A-b1-s1 (A1), Image 4","P25 LIN2-0A-b1-s1 (A1), Image 5","P25 LIN2-0A-b1-s1 (A1), Image 6","P25 LIN2-0A-b1-s1 (A1), Image 7",...,"P13 LIN7-0C-b3 (C3), Image 9","P13 LIN7-0C-b3 (C4), Image 1","P13 LIN7-0C-b3 (C4), Image 2","P13 LIN7-0C-b3 (C4), Image 3","P13 LIN7-0C-b3 (C4), Image 4","P13 LIN7-0C-b3 (C4), Image 5","P13 LIN7-0C-b3 (C4), Image 6","P13 LIN7-0C-b3 (C4), Image 7","P13 LIN7-0C-b3 (C4), Image 8","P13 LIN7-0C-b3 (C4), Image 9"
0,3,AS_MRC-5_20241018,0,7.686571,9.283421,16.20991,17.03200,67.20608,12.16271,17.81714,...,20.01946,27.12891,31.77413,38.45559,28.91041,61.56542,24.35444,39.46009,19.87714,18.79862
1,3,AS_MRC-5_20241018,2,6.275403,7.571911,14.99761,15.04814,66.52883,12.71471,15.56763,...,19.11542,24.99747,31.61830,37.41593,27.69640,63.89141,23.33541,39.22633,18.52102,17.70863
2,3,AS_MRC-5_20241018,4,7.289321,7.919922,13.88071,15.39684,68.21241,11.55717,16.42892,...,19.59660,26.12715,34.85290,40.25179,29.26361,68.26054,24.03975,43.03363,19.30261,19.34727
3,3,AS_MRC-5_20241018,6,6.383441,6.536073,13.53283,15.41815,66.73944,12.34641,15.45257,...,19.97125,25.19087,33.29969,40.64433,28.78913,64.38572,23.53044,42.37032,18.47369,18.68819
4,3,AS_MRC-5_20241018,8,6.946296,8.295794,14.81200,16.14818,68.91574,14.28609,15.97888,...,23.01751,28.05965,38.96819,48.14104,33.61819,78.30645,27.04935,48.96860,21.78417,20.76650
5,3,AS_MRC-5_20241018,10,6.174947,6.929837,14.00609,14.19894,65.76514,11.74409,16.13438,...,23.30699,27.86051,39.97780,50.84838,34.41064,78.63998,26.70401,48.09058,23.25488,20.90513
6,3,AS_MRC-5_20241018,12,6.377022,8.782030,15.17940,17.25012,70.52454,12.06540,18.48708,...,27.66614,35.56203,46.91631,59.09644,40.32561,84.67247,33.10690,57.09422,27.56446,25.00744
7,3,AS_MRC-5_20241018,14,6.558198,9.290115,10.87433,16.38631,68.45136,13.71387,17.84480,...,28.28589,33.97919,47.54255,59.33191,39.99911,86.21352,33.09939,58.03178,26.46560,25.25978
8,3,AS_MRC-5_20241018,16,8.347695,11.087120,17.21338,18.78155,73.60010,16.33509,19.02200,...,32.42434,38.12116,51.74176,64.75661,46.64205,89.91006,34.48358,63.73456,30.64896,28.03465
9,3,AS_MRC-5_20241018,18,8.425208,10.077440,13.43941,18.42821,72.44946,15.67725,19.82934,...,30.99418,37.22793,53.56533,65.38004,45.25834,90.62609,37.53394,66.08699,30.14758,28.56090
10,3,AS_MRC-5_20241018,20,8.068522,11.523500,14.38709,20.32629,77.74892,15.86211,21.91065,...,37.52500,45.36018,59.04086,74.56573,52.89308,94.58712,44.42840,73.88453,34.61414,31.73815
11,3,AS_MRC-5_20241018,22,8.374330,10.600480,13.25837,18.50306,74.56621,16.02969,19.99481,...,37.96479,43.12636,60.08509,76.35045,55.17859,95.05279,45.38065,76.94335,35.88724,30.45632
12,3,AS_MRC-5_20241018,24,9.144447,11.966440,17.33842,22.50785,77.66403,17.42843,24.71495,...,45.25513,51.65632,70.08836,85.25308,63.28015,97.11825,54.80189,83.19943,41.71444,38.96955
13,3,AS_MRC-5_20241018,26,8.593409,10.654360,16.06473,21.36029,77.04182,19.20659,22.63638,...,45.97847,53.77724,73.37807,88.10355,65.52113,97.62196,56.41144,85.96905,42.07775,39.75688
14,3,AS_MRC-5_20241018,28,9.758862,12.981520,14.53712,24.25795,81.26311,19.65984,26.67859,...,53.23358,61.05093,79.85570,93.02543,74.49580,98.93049,64.26067,90.82967,48.64052,46.41232
15,3,AS_MRC-5_20241018,30,10.685370,12.816730,18.09413,23.03650,81.10529,20.82898,25.51696,...,54.40532,60.24912,81.49632,92.92395,76.54447,98.77785,67.51919,92.33985,50.93081,46.73979
16,3,AS_MRC-5_20241018,32,12.957960,15.317560,21.57725,27.45636,85.66986,24.33772,28.49514,...,63.25919,72.16817,88.49171,97.01363,85.27542,99.57461,77.09428,96.67005,61.39327,55.06999
17,3,AS_MRC-5_20241018,34,11.635230,14.812750,20.80126,27.15998,84.41850,25.53001,28.46256,...,64.50379,73.05903,90.96549,98.14815,87.15874,99.46671,79.11768,96.64212,61.09491,56.69013
18,3,AS_MRC-5_20241018,36,14.341260,17.491400,24.86341,30.37409,88.37153,28.19479,33.61355,...,73.10397,82.00728,94.72813,99.28014,92.52150,99.92112,87.63194,98.61320,70.47653,65.82639
19,3,AS_MRC-5_20241018,38,13.419470,17.156020,23.78462,28.33896,87.97816,25.05442,32.79754,...,75.47987,82.24104,95.01440,99.59599,93.67719,99.79144,90.04923,99.00991,73.32625,67.41702
20,3,AS_MRC-5_20241018,40,15.285930,19.232890,30.51170,30.59666,90.49361,29.65021,34.99105,...,82.44891,87.01704,98.26977,99.76084,97.18053,99.76896,94.06222,99.67603,79.21397,74.91669
21,3,AS_MRC-5_20241018,42,13.351930,17.045040,26.02197,30.62098,90.83498,27.66568,32.06902,...,82.91022,87.41505,98.95808,99.57966,98.20346,99.72144,95.39943,99.68449,80.63504,75.02827
22,3,AS_MRC-5_20241018,44,14.560620,18.740100,27.39415,33.37610,93.40895,30.08796,36.57575,...,89.76712,92.23530,99.20666,99.90733,99.41795,99.94093,97.21140,99.90658,88.23275,82.46695
23,3,AS_MRC-5_20241018,46,14.159400,17.443590,29.83030,32.92866,93.12561,28.89321,36.67088,...,90.44579,93.17117,99.36952,99.80038,99.39507,99.83207,97.99831,99.82258,89.81076,81.54365
24,3,AS_MRC-5_20241018,48,15.392810,20.058530,30.91203,37.00933,95.28244,32.38943,39.79219,...,95.85793,96.97462,99.79737,99.94209,99.89640,99.96906,99.30896,99.88969,93.18496,88.43490
25,3,AS_MRC-5_20241018,50,15.079690,18.099390,28.29798,35.18090,94.57202,30.29413,38.34967,...,94.35655,95.38372,99.85782,99.81909,99.82941,99.96612,98.98253,99.96729,93.34796,87.53039
26,3,AS_MRC-5_20241018,52,17.005640,21.770040,33.15969,41.35558,96.11916,34.11816,42.11661,...,98.20114,97.96327,99.96400,99.95942,99.96838,99.99741,99.58881,99.98544,96.91700,93.15381
27,3,AS_MRC-5_20241018,54,16.602930,19.669200,30.84080,39.27830,95.48370,34.94086,42.77808,...,97.71947,97.40774,99.89224,99.90376,99.85713,99.96477,99.34522,99.95642,95.89310,91.52548
28,3,AS_MRC-5_20241018,56,19.392820,23.870800,37.23230,44.74323,97.72344,40.91311,50.34268,...,99.18816,99.29243,99.98128,99.98128,99.96755,99.99863,99.91517,99.99891,98.81618,96.69662
29,3,AS_MRC-5_20241018,58,18.707320,24.201610,32.73547,43.57900,97.41470,35.92036,48.54772,...,98.91068,99.11883,99.93504,99.92747,99.94522,99.99119,99.65588,99.98450,98.38525,95.41241
30,3,AS_MRC-5_20241018,60,21.211140,27.256200,38.44645,49.48495,98.90516,45.36679,54.51582,...,99.60309,99.78092,99.99849,99.97828,99.98307,100.00000,99.96059,99.98825,99.32467,98.01272
31,3,AS_MRC-5_20241018,62,20.266060,24.724040,37.69155,48.34121,98.58883,43.05664,51.55266,...,99.60911,99.74589,99.98436,99.97337,99.96851,99.99686,99.80400,99.99070,99.21040,97.63521
32,3,AS_MRC-5_20241018,64,20.487600,27.670180,41.23784,50.27200,98.90993,45.72723,57.09680,...,99.66625,99.82837,100.00000,99.98566,99.95567,99.99747,99.85221,99.99651,99.57399,98.66559
33,3,AS_MRC-5_20241018,66,20.745120,26.720930,35.58567,49.62139,98.19376,43.52273,56.70413,...,99.47416,99.62549,99.99323,99.92611,99.92412,99.99884,99.63478,99.99023,99.40395,98.08662
34,3,AS_MRC-5_20241018,68,30.393970,38.810230,54.77280,61.71526,99.68961,55.57549,68.96075,...,99.98367,99.98573,100.00000,99.99795,100.00000,100.00000,99.96477,100.00000,99.97883,99.48726
35,3,AS_MRC-5_20241018,70,29.111250,33.933220,51.86913,60.60902,99.73530,53.76809,66.95114,...,99.96906,99.99343,99.99924,99.99808,100.00000,100.00000,99.95766,100.00000,99.98511,99.49929
36,3,AS_MRC-5_20241018,72,30.321170,34.258090,54.43755,62.15950,99.70696,54.13953,67.09810,...,99.95097,99.97329,99.99597,99.97916,100.00000,100.00000,99.96469,100.00000,99.95082,99.71112

,Plate_Number,Vessel_Name,Elapsed,"P25 LIN2-0A-b1-s1 (A1), Image 1","P25 LIN2-0A-b1-s1 (A1), Image 2","P25 LIN2-0A-b1-s1 (A1), Image 3","P25 LIN2-0A-b1-s1 (A1), Image 4","P25 LIN2-0A-b1-s1 (A1), Image 6","P25 LIN2-0A-b1-s1 (A1), Image 7","P25 LIN2-0A-b1-s1 (A1), Image 8",...,"P13 LIN7-0C-b3 (C3), Image 8","P13 LIN7-0C-b3 (C3), Image 9","P13 LIN7-0C-b3 (C4), Image 1","P13 LIN7-0C-b3 (C4), Image 2","P13 LIN7-0C-b3 (C4), Image 3","P13 LIN7-0C-b3 (C4), Image 4","P13 LIN7-0C-b3 (C4), Image 6","P13 LIN7-0C-b3 (C4), Image 7","P13 LIN7-0C-b3 (C4), Image 8","P13 LIN7-0C-b3 (C4), Image 9"
0,3,AS_MRC-5_20241018,4,7.289321,7.919922,13.88071,15.39684,11.55717,16.42892,18.34134,...,27.96971,19.59660,26.12715,34.85290,40.25179,29.26361,24.03975,43.03363,19.30261,19.34727
1,3,AS_MRC-5_20241018,6,6.383441,6.536073,13.53283,15.41815,12.34641,15.45257,16.66002,...,27.46934,19.97125,25.19087,33.29969,40.64433,28.78913,23.53044,42.37032,18.47369,18.68819
2,3,AS_MRC-5_20241018,8,6.946296,8.295794,14.81200,16.14818,14.28609,15.97888,16.63250,...,31.19011,23.01751,28.05965,38.96819,48.14104,33.61819,27.04935,48.96860,21.78417,20.76650
3,3,AS_MRC-5_20241018,10,6.174947,6.929837,14.00609,14.19894,11.74409,16.13438,16.18683,...,30.77551,23.30699,27.86051,39.97780,50.84838,34.41064,26.70401,48.09058,23.25488,20.90513
4,3,AS_MRC-5_20241018,12,6.377022,8.782030,15.17940,17.25012,12.06540,18.48708,18.35172,...,37.36710,27.66614,35.56203,46.91631,59.09644,40.32561,33.10690,57.09422,27.56446,25.00744
5,3,AS_MRC-5_20241018,14,6.558198,9.290115,10.87433,16.38631,13.71387,17.84480,17.71969,...,36.62915,28.28589,33.97919,47.54255,59.33191,39.99911,33.09939,58.03178,26.46560,25.25978
6,3,AS_MRC-5_20241018,16,8.347695,11.087120,17.21338,18.78155,16.33509,19.02200,21.15132,...,40.38530,32.42434,38.12116,51.74176,64.75661,46.64205,34.48358,63.73456,30.64896,28.03465
7,3,AS_MRC-5_20241018,18,8.425208,10.077440,13.43941,18.42821,15.67725,19.82934,20.52059,...,42.60530,30.99418,37.22793,53.56533,65.38004,45.25834,37.53394,66.08699,30.14758,28.56090
8,3,AS_MRC-5_20241018,20,8.068522,11.523500,14.38709,20.32629,15.86211,21.91065,22.12672,...,48.66307,37.52500,45.36018,59.04086,74.56573,52.89308,44.42840,73.88453,34.61414,31.73815
9,3,AS_MRC-5_20241018,22,8.374330,10.600480,13.25837,18.50306,16.02969,19.99481,21.92772,...,48.95269,37.96479,43.12636,60.08509,76.35045,55.17859,45.38065,76.94335,35.88724,30.45632
10,3,AS_MRC-5_20241018,24,9.144447,11.966440,17.33842,22.50785,17.42843,24.71495,24.48221,...,58.31539,45.25513,51.65632,70.08836,85.25308,63.28015,54.80189,83.19943,41.71444,38.96955
11,3,AS_MRC-5_20241018,26,8.593409,10.654360,16.06473,21.36029,19.20659,22.63638,24.64263,...,60.26169,45.97847,53.77724,73.37807,88.10355,65.52113,56.41144,85.96905,42.07775,39.75688
12,3,AS_MRC-5_20241018,28,9.758862,12.981520,14.53712,24.25795,19.65984,26.67859,28.27278,...,66.60142,53.23358,61.05093,79.85570,93.02543,74.49580,64.26067,90.82967,48.64052,46.41232
13,3,AS_MRC-5_20241018,30,10.685370,12.816730,18.09413,23.03650,20.82898,25.51696,27.24957,...,68.15477,54.40532,60.24912,81.49632,92.92395,76.54447,67.51919,92.33985,50.93081,46.73979
14,3,AS_MRC-5_20241018,32,12.957960,15.317560,21.57725,27.45636,24.33772,28.49514,30.46814,...,78.54977,63.25919,72.16817,88.49171,97.01363,85.27542,77.09428,96.67005,61.39327,55.06999
15,3,AS_MRC-5_20241018,34,11.635230,14.812750,20.80126,27.15998,25.53001,28.46256,30.16656,...,82.68185,64.50379,73.05903,90.96549,98.14815,87.15874,79.11768,96.64212,61.09491,56.69013
16,3,AS_MRC-5_20241018,36,14.341260,17.491400,24.86341,30.37409,28.19479,33.61355,33.64716,...,88.45812,73.10397,82.00728,94.72813,99.28014,92.52150,87.63194,98.61320,70.47653,65.82639
17,3,AS_MRC-5_20241018,38,13.419470,17.156020,23.78462,28.33896,25.05442,32.79754,34.27018,...,90.78323,75.47987,82.24104,95.01440,99.59599,93.67719,90.04923,99.00991,73.32625,67.41702
18,3,AS_MRC-5_20241018,40,15.285930,19.232890,30.51170,30.59666,29.65021,34.99105,37.13826,...,94.96701,82.44891,87.01704,98.26977,99.76084,97.18053,94.06222,99.67603,79.21397,74.91669
19,3,AS_MRC-5_20241018,42,13.351930,17.045040,26.02197,30.62098,27.66568,32.06902,36.69614,...,94.95834,82.91022,87.41505,98.95808,99.57966,98.20346,95.39943,99.68449,80.63504,75.02827
20,3,AS_MRC-5_20241018,44,14.560620,18.740100,27.39415,33.37610,30.08796,36.57575,40.67376,...,97.84720,89.76712,92.23530,99.20666,99.90733,99.41795,97.21140,99.90658,88.23275,82.46695
21,3,AS_MRC-5_20241018,46,14.159400,17.443590,29.83030,32.92866,28.89321,36.67088,39.01073,...,96.78171,90.44579,93.17117,99.36952,99.80038,99.39507,97.99831,99.82258,89.81076,81.54365
22,3,AS_MRC-5_20241018,48,15.392810,20.058530,30.91203,37.00933,32.38943,39.79219,44.13823,...,98.74870,95.85793,96.97462,99.79737,99.94209,99.89640,99.30896,99.88969,93.18496,88.43490
23,3,AS_MRC-5_20241018,50,15.079690,18.099390,28.29798,35.18090,30.29413,38.34967,40.63442,...,98.78755,94.35655,95.38372,99.85782,99.81909,99.82941,98.98253,99.96729,93.34796,87.53039
24,3,AS_MRC-5_20241018,52,17.005640,21.770040,33.15969,41.35558,34.11816,42.11661,46.77925,...,99.67404,98.20114,97.96327,99.96400,99.95942,99.96838,99.58881,99.98544,96.91700,93.15381
25,3,AS_MRC-5_20241018,54,16.602930,19.669200,30.84080,39.27830,34.94086,42.77808,45.67048,...,99.51828,97.71947,97.40774,99.89224,99.90376,99.85713,99.34522,99.95642,95.89310,91.52548
26,3,AS_MRC-5_20241018,56,19.392820,23.870800,37.23230,44.74323,40.91311,50.34268,52.39264,...,99.94687,99.18816,99.29243,99.98128,99.98128,99.96755,99.91517,99.99891,98.81618,96.69662
27,3,AS_MRC-5_20241018,58,18.707320,24.201610,32.73547,43.57900,35.92036,48.54772,49.86759,...,99.69740,98.91068,99.11883,99.93504,99.92747,99.94522,99.65588,99.98450,98.38525,95.41241
28,3,AS_MRC-5_20241018,60,21.211140,27.256200,38.44645,49.48495,45.36679,54.51582,56.11983,...,99.92775,99.60309,99.78092,99.99849,99.97828,99.98307,99.96059,99.98825,99.32467,98.01272
29,3,AS_MRC-5_20241018,62,20.266060,24.724040,37.69155,48.34121,43.05664,51.55266,56.50335,...,99.82434,99.60911,99.74589,99.98436,99.97337,99.96851,99.80400,99.99070,99.21040,97.63521
30,3,AS_MRC-5_20241018,64,20.487600,27.670180,41.23784,50.27200,45.72723,57.09680,59.85665,...,99.92562,99.66625,99.82837,100.00000,99.98566,99.95567,99.85221,99.99651,99.57399,98.66559
31,3,AS_MRC-5_20241018,66,20.745120,26.720930,35.58567,49.62139,43.52273,56.70413,58.33642,...,99.86663,99.47416,99.62549,99.99323,99.92611,99.92412,99.63478,99.99023,99.40395,98.08662
32,3,AS_MRC-5_20241018,68,30.393970,38.810230,54.77280,61.71526,55.57549,68.96075,71.34205,...,100.00000,99.98367,99.98573,100.00000,99.99795,100.00000,99.96477,100.00000,99.97883,99.48726
33,3,AS_MRC-5_20241018,70,29.111250,33.933220,51.86913,60.60902,53.76809,66.95114,69.22768,...,99.99268,99.96906,99.99343,99.99924,99.99808,100.00000,99.95766,100.00000,99.98511,99.49929
34,3,AS_MRC-5_20241018,72,30.321170,34.258090,54.43755,62.15950,54.13953,67.09810,70.83253,...,99.99119,99.95097,99.97329,99.99597,99.97916,100.00000,99.96469,100.00000,99.95082,99.71112

,Plate_Number,Vessel_Name,Elapsed,P25 LIN2-0A-b1-s1 (A1),P25 LIN2-0A-b1-s1 (A2),P22 LIN3-0A-b2-s1 (A3),P22 LIN3-0A-b2-s1 (A4),P20 LIN4-0B-b2A-s1 (B1),P20 LIN4-0B-b2A-s1 (B2),P18 LIN5-0B-b3-s1 (B3),P18 LIN5-0B-b3-s1 (B4),P16 LIN6-0C-b1-s1 (C1),P16 LIN6-0C-b1-s1 (C2),P13 LIN7-0C-b3 (C3),P13 LIN7-0C-b3 (C4)
0,3,AS_MRC-5_20241018,4,13.476364,14.819957,41.995990,45.932332,47.487715,45.846449,45.030465,40.514723,33.295649,29.910598,29.567332,29.527339
1,3,AS_MRC-5_20241018,6,12.699059,13.160411,40.368556,43.868251,45.056695,44.723607,43.398787,38.425366,29.842484,26.310112,29.025289,28.873332
2,3,AS_MRC-5_20241018,8,13.657927,15.279727,44.803421,49.110241,52.621761,51.200570,49.108592,44.237236,35.734501,31.490144,34.458056,33.419461
3,3,AS_MRC-5_20241018,10,12.707322,14.705955,43.441092,46.821117,50.997628,49.688401,48.593766,44.515459,33.412717,29.802889,34.512162,34.006491
4,3,AS_MRC-5_20241018,12,14.313948,16.855295,48.808091,53.071934,59.454847,58.532213,57.152479,50.976986,39.758344,36.946039,40.973496,40.584176
5,3,AS_MRC-5_20241018,14,13.664610,16.245596,47.125173,51.609890,58.886980,58.630702,57.045376,51.665393,37.333675,34.906047,41.275589,40.463664
6,3,AS_MRC-5_20241018,16,16.095703,17.450644,51.626185,56.779791,64.721884,64.446661,63.518493,56.845845,42.856813,39.474517,45.783021,44.770416
7,3,AS_MRC-5_20241018,18,15.440470,16.311872,50.999066,54.388390,64.468410,64.533944,61.931124,55.944925,40.423725,38.866727,46.563085,45.470131
8,3,AS_MRC-5_20241018,20,16.535644,18.637841,56.278176,60.972635,71.978860,72.285238,71.378932,63.294964,47.024829,44.059754,53.763042,52.065634
9,3,AS_MRC-5_20241018,22,15.681468,17.443247,55.913464,59.837927,70.851124,71.826911,70.488377,63.020391,43.865693,42.164661,54.285459,52.926006
10,3,AS_MRC-5_20241018,24,18.225812,20.137554,64.104295,68.189784,80.502539,81.283961,80.469051,72.498270,54.167231,50.918311,62.728645,61.120402
11,3,AS_MRC-5_20241018,26,17.710370,19.023137,64.270666,68.057335,80.523619,82.179192,80.426670,73.134439,52.768133,50.381420,64.428076,63.124389
12,3,AS_MRC-5_20241018,28,19.694395,22.453039,71.165865,76.248134,88.202729,89.297596,88.379874,81.081999,61.780474,59.296786,71.594275,69.821380
13,3,AS_MRC-5_20241018,30,19.828289,21.323096,71.151346,76.106612,87.662701,89.252753,88.167440,81.239240,60.649187,57.898555,72.249344,71.092937
14,3,AS_MRC-5_20241018,32,23.032271,25.184983,81.184691,85.031471,94.252370,95.115461,94.279181,89.673854,73.880638,68.969050,80.770619,79.147065
15,3,AS_MRC-5_20241018,34,22.521726,23.698643,80.940973,84.125326,93.993250,95.360351,94.055512,90.231706,71.941222,67.461370,82.440531,80.359531
16,3,AS_MRC-5_20241018,36,25.923711,28.243398,88.085319,91.561566,97.505895,98.141094,97.774454,95.423007,81.921249,76.582521,88.711319,86.385639
17,3,AS_MRC-5_20241018,38,24.848700,27.037429,88.167685,90.972241,97.452772,98.238334,97.501940,95.299114,80.653349,76.449374,89.479785,87.541379
18,3,AS_MRC-5_20241018,40,27.926040,30.013204,92.283030,95.011220,98.960009,99.298355,98.957173,97.660505,88.158391,83.331371,93.303270,91.262136
19,3,AS_MRC-5_20241018,42,26.087680,29.941661,91.993026,93.334256,98.708041,98.958010,98.327579,97.461199,85.476642,81.541492,93.321419,91.862935
20,3,AS_MRC-5_20241018,44,28.519100,32.962851,95.711489,96.768950,99.468060,99.672676,99.318329,98.995515,92.007575,88.209857,96.556086,94.823115
21,3,AS_MRC-5_20241018,46,28.040976,30.873706,94.610886,96.024523,99.168560,99.203240,98.973835,98.461346,88.950301,87.125186,96.464765,95.113930
22,3,AS_MRC-5_20241018,48,31.147803,35.702412,97.319862,98.374837,99.662963,99.747045,99.603779,99.442023,95.070361,92.938474,98.453457,97.178624
23,3,AS_MRC-5_20241018,50,29.343328,34.399271,96.689176,97.465636,99.315219,99.506220,99.189004,99.095489,91.708981,90.863459,97.930739,96.839776
24,3,AS_MRC-5_20241018,52,33.597583,39.083462,98.543286,99.074103,99.844104,99.813741,99.756249,99.732565,96.995110,96.219215,99.384389,98.437516
25,3,AS_MRC-5_20241018,54,32.488347,37.479446,97.838448,98.237496,99.579816,99.529363,99.402271,99.394097,95.143685,94.751120,99.123845,97.972636
26,3,AS_MRC-5_20241018,56,38.078635,44.151969,99.355386,99.662810,99.937254,99.916648,99.873716,99.898615,98.681079,98.394617,99.755096,99.331177
27,3,AS_MRC-5_20241018,58,35.866385,41.211081,98.883685,99.241936,99.780765,99.707614,99.608197,99.735559,97.126530,97.410441,99.633448,99.045575
28,3,AS_MRC-5_20241018,60,41.375843,46.846536,99.585552,99.802961,99.957723,99.905436,99.890890,99.928753,99.096897,99.255580,99.897466,99.628374
29,3,AS_MRC-5_20241018,62,39.615484,45.494006,99.241896,99.563511,99.870430,99.790120,99.721143,99.834364,97.823219,98.666948,99.816919,99.539055
30,3,AS_MRC-5_20241018,64,42.653413,49.913148,99.655816,99.831489,99.959054,99.913686,99.872530,99.921604,99.040321,99.279695,99.904165,99.732250
31,3,AS_MRC-5_20241018,66,41.138025,47.317705,99.429601,99.541438,99.756249,99.760460,99.681725,99.762205,97.669184,98.568162,99.740670,99.573066
32,3,AS_MRC-5_20241018,68,53.903969,61.623595,99.971390,99.985401,99.994175,99.995155,99.993100,99.996154,99.943382,99.964664,99.995037,99.926817
33,3,AS_MRC-5_20241018,70,51.490473,61.113229,99.935823,99.954185,99.984735,99.978815,99.971328,99.983124,99.796446,99.888305,99.987699,99.929101
34,3,AS_MRC-5_20241018,72,52.734535,62.177672,99.903307,99.936350,99.977590,99.979031,99.971982,99.970263,99.758635,99.849490,99.974773,99.946881

,Plate_Number,Vessel_Name,Elapsed,P25 LIN2-0A-b1-s1,P22 LIN3-0A-b2-s1,P20 LIN4-0B-b2A-s1,P18 LIN5-0B-b3-s1,P16 LIN6-0C-b1-s1,P13 LIN7-0C-b3
0,3,AS_MRC-5_20241018,4,14.148161,43.964161,46.667082,42.772594,31.603123,29.547336
1,3,AS_MRC-5_20241018,6,12.929735,42.118404,44.890151,40.912077,28.076298,28.949311
2,3,AS_MRC-5_20241018,8,14.468827,46.956831,51.911166,46.672914,33.612323,33.938759
3,3,AS_MRC-5_20241018,10,13.706638,45.131105,50.343014,46.554613,31.607803,34.259327
4,3,AS_MRC-5_20241018,12,15.584621,50.940012,58.993530,54.064733,38.352191,40.778836
5,3,AS_MRC-5_20241018,14,14.955103,49.367531,58.758841,54.355384,36.119861,40.869626
6,3,AS_MRC-5_20241018,16,16.773173,54.202988,64.584272,60.182169,41.165665,45.276719
7,3,AS_MRC-5_20241018,18,15.876171,52.693728,64.501177,58.938024,39.645226,46.016608
8,3,AS_MRC-5_20241018,20,17.586743,58.625406,72.132049,67.336948,45.542291,52.914338
9,3,AS_MRC-5_20241018,22,16.562357,57.875696,71.339017,66.754384,43.015177,53.605733
10,3,AS_MRC-5_20241018,24,19.181683,66.147039,80.893250,76.483661,52.542771,61.924524
11,3,AS_MRC-5_20241018,26,18.366754,66.164001,81.351406,76.780554,51.574776,63.776232
12,3,AS_MRC-5_20241018,28,21.073717,73.706999,88.750163,84.730936,60.538630,70.707828
13,3,AS_MRC-5_20241018,30,20.575692,73.628979,88.457727,84.703340,59.273871,71.671141
14,3,AS_MRC-5_20241018,32,24.108627,83.108081,94.683916,91.976517,71.424844,79.958842
15,3,AS_MRC-5_20241018,34,23.110184,82.533149,94.676801,92.143609,69.701296,81.400031
16,3,AS_MRC-5_20241018,36,27.083554,89.823442,97.823494,96.598731,79.251885,87.548479
17,3,AS_MRC-5_20241018,38,25.943064,89.569963,97.845553,96.400527,78.551361,88.510582
18,3,AS_MRC-5_20241018,40,28.969622,93.647125,99.129182,98.308839,85.744881,92.282703
19,3,AS_MRC-5_20241018,42,28.014671,92.663641,98.833026,97.894389,83.509067,92.592177
20,3,AS_MRC-5_20241018,44,30.740976,96.240219,99.570368,99.156922,90.108716,95.689601
21,3,AS_MRC-5_20241018,46,29.457341,95.317704,99.185900,98.717591,88.037744,95.789347
22,3,AS_MRC-5_20241018,48,33.425107,97.847350,99.705004,99.522901,94.004417,97.816041
23,3,AS_MRC-5_20241018,50,31.871299,97.077406,99.410719,99.142246,91.286220,97.385257
24,3,AS_MRC-5_20241018,52,36.340522,98.808694,99.828922,99.744407,96.607162,98.910953
25,3,AS_MRC-5_20241018,54,34.983897,98.037972,99.554589,99.398184,94.947402,98.548241
26,3,AS_MRC-5_20241018,56,41.115302,99.509098,99.926951,99.886166,98.537848,99.543137
27,3,AS_MRC-5_20241018,58,38.538733,99.062811,99.744189,99.671878,97.268486,99.339511
28,3,AS_MRC-5_20241018,60,44.111189,99.694257,99.931579,99.909821,99.176239,99.762920
29,3,AS_MRC-5_20241018,62,42.554745,99.402704,99.830275,99.777753,98.245083,99.677987
30,3,AS_MRC-5_20241018,64,46.283280,99.743652,99.936370,99.897067,99.160008,99.818207
31,3,AS_MRC-5_20241018,66,44.227865,99.485519,99.758354,99.721965,98.118673,99.656868
32,3,AS_MRC-5_20241018,68,57.763782,99.978396,99.994665,99.994627,99.954023,99.960927
33,3,AS_MRC-5_20241018,70,56.301851,99.945004,99.981775,99.977226,99.842376,99.958400
34,3,AS_MRC-5_20241018,72,57.456104,99.919829,99.978311,99.971123,99.804063,99.960827

Wrote replaced data to: /Users/allielas/HTP_fibroblasts_mitolyso/proliferation_growth_curves/Incucyte_sheets/r3_processed.xlsx

/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Plate_Number,Vessel_Name,Elapsed,"P11 LIN10-0C-b4 (A1), Image 1","P11 LIN10-0C-b4 (A1), Image 2","P11 LIN10-0C-b4 (A1), Image 3","P11 LIN10-0C-b4 (A1), Image 4","P11 LIN10-0C-b4 (A1), Image 5","P11 LIN10-0C-b4 (A1), Image 6","P11 LIN10-0C-b4 (A1), Image 7",...,"P24 LIN3-0A-b2-s2-ss1 (C3), Image 9","P24 LIN3-0A-b2-s2-ss1 (C4), Image 1","P24 LIN3-0A-b2-s2-ss1 (C4), Image 2","P24 LIN3-0A-b2-s2-ss1 (C4), Image 3","P24 LIN3-0A-b2-s2-ss1 (C4), Image 4","P24 LIN3-0A-b2-s2-ss1 (C4), Image 5","P24 LIN3-0A-b2-s2-ss1 (C4), Image 6","P24 LIN3-0A-b2-s2-ss1 (C4), Image 7","P24 LIN3-0A-b2-s2-ss1 (C4), Image 8","P24 LIN3-0A-b2-s2-ss1 (C4), Image 9"
0,4,AS_MRC-5_20241112,0,35.07854,38.18079,46.77454,36.23026,67.49235,42.50075,40.58457,...,5.508632,20.96495,13.20791,17.05017,18.44699,55.76212,31.49086,18.94682,17.51659,16.63666
1,4,AS_MRC-5_20241112,2,37.17643,41.03938,52.54295,39.29319,76.87103,46.62683,46.64308,...,6.073740,22.57006,16.40666,17.47384,20.03742,61.97027,33.87109,20.92828,17.96247,16.88272
2,4,AS_MRC-5_20241112,4,41.61358,45.01700,59.41139,43.45928,81.10030,47.63638,53.40566,...,6.869401,24.69467,17.77371,19.24081,22.50007,63.58855,33.66484,22.06738,19.26150,18.88351
3,4,AS_MRC-5_20241112,6,43.42022,48.57708,63.37713,47.80909,85.91182,52.49208,56.23353,...,7.504167,25.77497,18.16652,20.69254,23.45157,68.73245,36.40577,23.18824,20.88130,18.75307
4,4,AS_MRC-5_20241112,8,45.20227,51.22828,68.21733,51.08876,87.60059,56.66712,61.86229,...,8.295114,28.05616,20.07321,22.91534,24.85352,70.62635,37.94014,24.89538,22.84002,21.88552
5,4,AS_MRC-5_20241112,10,49.02617,54.91722,69.97520,56.28128,88.96252,61.26679,64.64707,...,7.551492,31.02444,20.75175,24.72383,28.03028,73.76707,41.25232,26.18519,23.42070,23.23897
6,4,AS_MRC-5_20241112,12,54.47231,57.63357,74.09391,60.36768,92.53613,65.38379,68.45313,...,8.135858,31.71643,20.53472,24.59018,30.30778,78.14152,39.93061,27.71532,24.64646,24.44104
7,4,AS_MRC-5_20241112,14,61.02402,64.07466,80.25909,65.32943,95.51450,68.04298,74.09309,...,9.016471,31.47782,23.03978,25.52516,31.57144,80.90888,44.98176,28.77246,25.35723,26.34322
8,4,AS_MRC-5_20241112,16,62.39811,71.00251,86.27042,73.66354,97.95338,74.34604,82.27929,...,9.479961,32.77870,24.39699,27.05823,32.74762,83.71577,46.76204,30.06050,27.20470,30.11965
9,4,AS_MRC-5_20241112,18,68.21405,75.83212,91.07250,76.48779,99.04447,81.92034,87.03828,...,9.293256,36.59180,26.63154,29.28144,35.67144,87.47746,47.98589,32.69722,30.99343,30.36146
10,4,AS_MRC-5_20241112,20,74.34523,78.76570,94.14438,82.56222,99.43619,87.13812,90.61694,...,9.436460,38.14392,27.94143,33.59977,39.00452,88.89395,52.86166,34.83350,32.16599,31.67559
11,4,AS_MRC-5_20241112,22,79.57270,84.51192,97.12514,86.87213,99.74575,91.17857,93.67843,...,9.440901,40.49934,30.05778,35.32110,42.71198,92.37318,54.11276,37.10534,34.86021,35.43330
12,4,AS_MRC-5_20241112,24,85.64787,90.01147,98.59750,89.28307,99.93628,94.46999,95.69062,...,9.671383,44.32698,31.63851,39.28963,44.14978,93.71313,54.36489,38.47649,36.06226,36.12598
13,4,AS_MRC-5_20241112,26,88.39830,92.52253,99.11009,92.63071,99.97356,96.75296,97.66806,...,10.194770,47.09763,35.14443,43.62237,47.36854,95.23827,57.62428,40.23533,41.05311,38.79439
14,4,AS_MRC-5_20241112,28,92.48435,95.10995,99.53255,95.49197,99.93102,97.39838,98.56574,...,9.431407,48.93138,36.63864,47.27128,49.35259,96.40707,61.26168,44.86696,41.96466,39.98825
15,4,AS_MRC-5_20241112,30,95.60109,97.40453,99.85666,97.67708,99.99412,98.77451,99.32992,...,9.045222,52.50553,39.66735,50.80453,51.10138,96.90934,65.49674,48.38710,44.35834,44.48057
16,4,AS_MRC-5_20241112,32,97.33193,98.96498,99.91348,99.18514,99.99767,99.35949,99.82339,...,9.248115,55.96925,44.59592,51.87965,54.75585,98.19704,72.58448,50.80077,48.29928,46.54795
17,4,AS_MRC-5_20241112,34,98.61028,99.53145,99.99023,99.63328,99.99911,99.73045,99.89134,...,8.857148,60.84059,46.49291,56.42591,58.85442,98.83092,73.29572,56.64206,52.25505,51.37019
18,4,AS_MRC-5_20241112,36,99.46623,99.84148,99.99493,99.77190,100.00000,99.92966,99.99003,...,8.913350,67.16824,52.01309,62.00496,64.34918,99.44663,77.81188,59.01442,55.92992,53.08743
19,4,AS_MRC-5_20241112,38,99.60911,99.91388,99.98013,99.87789,100.00000,99.92378,99.97752,...,8.441392,71.31938,56.77905,63.92161,68.28732,99.48672,82.56945,63.42301,59.13358,57.44311
20,4,AS_MRC-5_20241112,40,99.75468,99.89954,99.94865,99.85494,100.00000,99.93806,99.96004,...,8.893753,77.11128,58.87238,68.55113,73.50750,99.70123,86.07346,68.17362,63.61717,61.49960
21,4,AS_MRC-5_20241112,42,99.83276,99.97650,100.00000,99.98558,100.00000,99.96072,99.99577,...,8.767961,81.09328,63.73463,71.09047,77.96329,99.77833,88.83242,72.06451,67.34047,65.48370
22,4,AS_MRC-5_20241112,44,99.78201,99.99624,99.99741,99.99194,100.00000,99.98866,100.00000,...,8.849432,83.19131,66.78110,75.91148,81.19235,99.93745,92.01943,76.72810,72.36021,68.75621
23,4,AS_MRC-5_20241112,46,99.86914,99.99680,100.00000,99.97459,100.00000,99.98729,99.99857,...,8.492884,87.50156,72.24193,80.06903,84.85611,99.97672,93.77335,80.17332,74.54511,72.94627
24,4,AS_MRC-5_20241112,48,99.92904,99.95233,100.00000,99.99378,100.00000,99.99823,99.95466,...,8.570668,90.68003,74.35499,81.34431,87.92005,99.99275,95.72142,84.38606,79.23473,76.23006
25,4,AS_MRC-5_20241112,50,99.92337,99.99699,99.99823,100.00000,100.00000,100.00000,99.99493,...,8.014368,93.01668,77.83530,86.44716,90.17469,99.99487,96.38433,87.98876,83.23461,80.43590
26,4,AS_MRC-5_20241112,52,99.92392,99.99357,100.00000,99.99105,100.00000,99.99719,100.00000,...,7.824176,94.79000,80.97881,88.50742,92.18531,99.98388,97.60265,89.36250,87.21768,84.12369
27,4,AS_MRC-5_20241112,54,99.89960,99.96749,99.99686,100.00000,100.00000,99.99590,99.98067,...,8.233650,96.19066,84.27412,91.43459,94.37342,99.99132,97.98315,91.81838,89.44554,86.46792
28,4,AS_MRC-5_20241112,56,99.95274,100.00000,100.00000,100.00000,100.00000,100.00000,99.99515,...,7.614866,96.99396,87.62824,93.24642,96.56673,99.98005,99.19409,95.19913,92.07809,87.81667
29,4,AS_MRC-5_20241112,58,99.92167,100.00000,100.00000,99.97876,100.00000,100.00000,100.00000,...,7.600319,98.29893,89.41856,95.25704,98.08491,99.99392,99.43120,96.03809,93.28780,91.32170
30,4,AS_MRC-5_20241112,60,99.92931,100.00000,100.00000,100.00000,100.00000,100.00000,99.97678,...,7.724062,98.30740,90.68639,96.50062,97.39680,100.00000,99.78455,97.23065,95.40421,93.21896
31,4,AS_MRC-5_20241112,62,99.86082,100.00000,99.97903,100.00000,100.00000,99.99241,99.99945,...,8.003646,98.66661,92.43314,97.21938,98.29859,100.00000,99.85727,98.13947,95.79381,94.58601
32,4,AS_MRC-5_20241112,64,99.96770,99.99521,99.98108,99.99870,100.00000,100.00000,100.00000,...,8.207496,99.17839,94.89258,97.85764,99.17517,100.00000,99.79663,98.84300,97.14966,95.68578
33,4,AS_MRC-5_20241112,66,99.95075,99.96236,99.98579,100.00000,100.00000,100.00000,100.00000,...,7.144204,99.26258,96.16696,98.08797,99.28083,100.00000,99.92521,98.94763,98.09591,96.52528
34,4,AS_MRC-5_20241112,68,99.95179,99.99733,99.97924,100.00000,100.00000,100.00000,100.00000,...,7.421397,99.36817,96.64048,98.73245,99.31046,100.00000,99.89394,99.40170,98.04714,96.09702
35,4,AS_MRC-5_20241112,70,99.94229,99.98470,99.95847,99.97876,100.00000,99.96973,100.00000,...,7.329340,99.59257,97.84042,99.04126,99.44301,100.00000,99.95171,99.58991,98.42357,97.97161
36,4,AS_MRC-5_20241112,72,99.99371,100.00000,99.95636,100.00000,100.00000,99.96865,100.00000,...,6.880326,99.60984,98.05923,99.47019,99.53868,100.00000,99.91825,99.38517,98.49841,98.16050

,Plate_Number,Vessel_Name,Elapsed,"P11 LIN10-0C-b4 (A1), Image 1","P11 LIN10-0C-b4 (A1), Image 2","P11 LIN10-0C-b4 (A1), Image 3","P11 LIN10-0C-b4 (A1), Image 4","P11 LIN10-0C-b4 (A1), Image 6","P11 LIN10-0C-b4 (A1), Image 7","P11 LIN10-0C-b4 (A1), Image 8",...,"P24 LIN3-0A-b2-s2-ss1 (C3), Image 8","P24 LIN3-0A-b2-s2-ss1 (C3), Image 9","P24 LIN3-0A-b2-s2-ss1 (C4), Image 1","P24 LIN3-0A-b2-s2-ss1 (C4), Image 2","P24 LIN3-0A-b2-s2-ss1 (C4), Image 3","P24 LIN3-0A-b2-s2-ss1 (C4), Image 4","P24 LIN3-0A-b2-s2-ss1 (C4), Image 6","P24 LIN3-0A-b2-s2-ss1 (C4), Image 7","P24 LIN3-0A-b2-s2-ss1 (C4), Image 8","P24 LIN3-0A-b2-s2-ss1 (C4), Image 9"
0,4,AS_MRC-5_20241112,4,41.61358,45.01700,59.41139,43.45928,47.63638,53.40566,58.35343,...,3.753551,6.869401,24.69467,17.77371,19.24081,22.50007,33.66484,22.06738,19.26150,18.88351
1,4,AS_MRC-5_20241112,6,43.42022,48.57708,63.37713,47.80909,52.49208,56.23353,64.25658,...,3.841373,7.504167,25.77497,18.16652,20.69254,23.45157,36.40577,23.18824,20.88130,18.75307
2,4,AS_MRC-5_20241112,8,45.20227,51.22828,68.21733,51.08876,56.66712,61.86229,67.44884,...,3.754575,8.295114,28.05616,20.07321,22.91534,24.85352,37.94014,24.89538,22.84002,21.88552
3,4,AS_MRC-5_20241112,10,49.02617,54.91722,69.97520,56.28128,61.26679,64.64707,72.89363,...,3.491109,7.551492,31.02444,20.75175,24.72383,28.03028,41.25232,26.18519,23.42070,23.23897
4,4,AS_MRC-5_20241112,12,54.47231,57.63357,74.09391,60.36768,65.38379,68.45313,79.34884,...,3.258987,8.135858,31.71643,20.53472,24.59018,30.30778,39.93061,27.71532,24.64646,24.44104
5,4,AS_MRC-5_20241112,14,61.02402,64.07466,80.25909,65.32943,68.04298,74.09309,83.26546,...,3.147810,9.016471,31.47782,23.03978,25.52516,31.57144,44.98176,28.77246,25.35723,26.34322
6,4,AS_MRC-5_20241112,16,62.39811,71.00251,86.27042,73.66354,74.34604,82.27929,88.74399,...,3.163107,9.479961,32.77870,24.39699,27.05823,32.74762,46.76204,30.06050,27.20470,30.11965
7,4,AS_MRC-5_20241112,18,68.21405,75.83212,91.07250,76.48779,81.92034,87.03828,92.59643,...,3.229827,9.293256,36.59180,26.63154,29.28144,35.67144,47.98589,32.69722,30.99343,30.36146
8,4,AS_MRC-5_20241112,20,74.34523,78.76570,94.14438,82.56222,87.13812,90.61694,95.35429,...,3.253456,9.436460,38.14392,27.94143,33.59977,39.00452,52.86166,34.83350,32.16599,31.67559
9,4,AS_MRC-5_20241112,22,79.57270,84.51192,97.12514,86.87213,91.17857,93.67843,98.04790,...,3.412643,9.440901,40.49934,30.05778,35.32110,42.71198,54.11276,37.10534,34.86021,35.43330
10,4,AS_MRC-5_20241112,24,85.64787,90.01147,98.59750,89.28307,94.46999,95.69062,98.90009,...,3.347082,9.671383,44.32698,31.63851,39.28963,44.14978,54.36489,38.47649,36.06226,36.12598
11,4,AS_MRC-5_20241112,26,88.39830,92.52253,99.11009,92.63071,96.75296,97.66806,99.61244,...,3.456280,10.194770,47.09763,35.14443,43.62237,47.36854,57.62428,40.23533,41.05311,38.79439
12,4,AS_MRC-5_20241112,28,92.48435,95.10995,99.53255,95.49197,97.39838,98.56574,99.80167,...,3.583643,9.431407,48.93138,36.63864,47.27128,49.35259,61.26168,44.86696,41.96466,39.98825
13,4,AS_MRC-5_20241112,30,95.60109,97.40453,99.85666,97.67708,98.77451,99.32992,99.87550,...,3.492064,9.045222,52.50553,39.66735,50.80453,51.10138,65.49674,48.38710,44.35834,44.48057
14,4,AS_MRC-5_20241112,32,97.33193,98.96498,99.91348,99.18514,99.35949,99.82339,99.95957,...,3.370711,9.248115,55.96925,44.59592,51.87965,54.75585,72.58448,50.80077,48.29928,46.54795
15,4,AS_MRC-5_20241112,34,98.61028,99.53145,99.99023,99.63328,99.73045,99.89134,99.98845,...,3.530307,8.857148,60.84059,46.49291,56.42591,58.85442,73.29572,56.64206,52.25505,51.37019
16,4,AS_MRC-5_20241112,36,99.46623,99.84148,99.99493,99.77190,99.92966,99.99003,99.99290,...,3.575448,8.913350,67.16824,52.01309,62.00496,64.34918,77.81188,59.01442,55.92992,53.08743
17,4,AS_MRC-5_20241112,38,99.60911,99.91388,99.98013,99.87789,99.92378,99.97752,99.98457,...,3.412301,8.441392,71.31938,56.77905,63.92161,68.28732,82.56945,63.42301,59.13358,57.44311
18,4,AS_MRC-5_20241112,40,99.75468,99.89954,99.94865,99.85494,99.93806,99.96004,100.00000,...,3.261036,8.893753,77.11128,58.87238,68.55113,73.50750,86.07346,68.17362,63.61717,61.49960
19,4,AS_MRC-5_20241112,42,99.83276,99.97650,100.00000,99.98558,99.96072,99.99577,100.00000,...,3.378292,8.767961,81.09328,63.73463,71.09047,77.96329,88.83242,72.06451,67.34047,65.48370
20,4,AS_MRC-5_20241112,44,99.78201,99.99624,99.99741,99.99194,99.98866,100.00000,99.99760,...,3.625368,8.849432,83.19131,66.78110,75.91148,81.19235,92.01943,76.72810,72.36021,68.75621
21,4,AS_MRC-5_20241112,46,99.86914,99.99680,100.00000,99.97459,99.98729,99.99857,100.00000,...,3.291425,8.492884,87.50156,72.24193,80.06903,84.85611,93.77335,80.17332,74.54511,72.94627
22,4,AS_MRC-5_20241112,48,99.92904,99.95233,100.00000,99.99378,99.99823,99.95466,100.00000,...,3.225047,8.570668,90.68003,74.35499,81.34431,87.92005,95.72142,84.38606,79.23473,76.23006
23,4,AS_MRC-5_20241112,50,99.92337,99.99699,99.99823,100.00000,100.00000,99.99493,100.00000,...,3.462153,8.014368,93.01668,77.83530,86.44716,90.17469,96.38433,87.98876,83.23461,80.43590
24,4,AS_MRC-5_20241112,52,99.92392,99.99357,100.00000,99.99105,99.99719,100.00000,100.00000,...,3.318742,7.824176,94.79000,80.97881,88.50742,92.18531,97.60265,89.36250,87.21768,84.12369
25,4,AS_MRC-5_20241112,54,99.89960,99.96749,99.99686,100.00000,99.99590,99.98067,100.00000,...,3.341961,8.233650,96.19066,84.27412,91.43459,94.37342,97.98315,91.81838,89.44554,86.46792
26,4,AS_MRC-5_20241112,56,99.95274,100.00000,100.00000,100.00000,100.00000,99.99515,100.00000,...,3.454914,7.614866,96.99396,87.62824,93.24642,96.56673,99.19409,95.19913,92.07809,87.81667
27,4,AS_MRC-5_20241112,58,99.92167,100.00000,100.00000,99.97876,100.00000,100.00000,100.00000,...,3.357530,7.600319,98.29893,89.41856,95.25704,98.08491,99.43120,96.03809,93.28780,91.32170
28,4,AS_MRC-5_20241112,60,99.92931,100.00000,100.00000,100.00000,100.00000,99.97678,100.00000,...,3.491382,7.724062,98.30740,90.68639,96.50062,97.39680,99.78455,97.23065,95.40421,93.21896
29,4,AS_MRC-5_20241112,62,99.86082,100.00000,99.97903,100.00000,99.99241,99.99945,100.00000,...,3.406154,8.003646,98.66661,92.43314,97.21938,98.29859,99.85727,98.13947,95.79381,94.58601
30,4,AS_MRC-5_20241112,64,99.96770,99.99521,99.98108,99.99870,100.00000,100.00000,100.00000,...,3.163106,8.207496,99.17839,94.89258,97.85764,99.17517,99.79663,98.84300,97.14966,95.68578
31,4,AS_MRC-5_20241112,66,99.95075,99.96236,99.98579,100.00000,100.00000,100.00000,100.00000,...,3.541643,7.144204,99.26258,96.16696,98.08797,99.28083,99.92521,98.94763,98.09591,96.52528
32,4,AS_MRC-5_20241112,68,99.95179,99.99733,99.97924,100.00000,100.00000,100.00000,100.00000,...,3.453549,7.421397,99.36817,96.64048,98.73245,99.31046,99.89394,99.40170,98.04714,96.09702
33,4,AS_MRC-5_20241112,70,99.94229,99.98470,99.95847,99.97876,99.96973,100.00000,99.99604,...,3.559468,7.329340,99.59257,97.84042,99.04126,99.44301,99.95171,99.58991,98.42357,97.97161
34,4,AS_MRC-5_20241112,72,99.99371,100.00000,99.95636,100.00000,99.96865,100.00000,100.00000,...,3.432583,6.880326,99.60984,98.05923,99.47019,99.53868,99.91825,99.38517,98.49841,98.16050

,Plate_Number,Vessel_Name,Elapsed,P11 LIN10-0C-b4 (A1),P11 LIN10-0C-b4 (A2),P15 LIN9-0C-b2-s1 (A3),P15 LIN9-0C-b2-s1 (A4),P16 LIN8-0B-b2B-s1 (B1),P16 LIN8-0B-b2B-s1 (B2),P20 LIN7-0C-b3 (B3),P20 LIN7-0C-b3 (B4),P23 LIN6-0C-b1-s1 (C1),P23 LIN6-0C-b1-s1 (C2),P24 LIN3-0A-b2-s2-ss1 (C3),P24 LIN3-0A-b2-s2-ss1 (C4)
0,4,AS_MRC-5_20241112,4,50.335194,54.729835,40.105578,71.557365,49.279927,62.332316,43.417495,38.717594,28.023544,10.906016,6.017127,22.260811
1,4,AS_MRC-5_20241112,6,54.313646,58.578980,44.558359,77.743275,53.626915,67.914805,47.305369,41.968935,28.924285,10.912719,6.024306,23.414248
2,4,AS_MRC-5_20241112,8,57.765434,61.696383,48.375188,80.829347,58.148571,71.773108,51.138009,45.696925,30.711864,11.273500,6.240405,25.432411
3,4,AS_MRC-5_20241112,10,61.642916,65.191186,51.613928,84.098231,62.006130,75.701224,55.032475,49.106066,32.622318,12.162530,6.250999,27.328435
4,4,AS_MRC-5_20241112,12,66.042690,69.026780,54.172701,87.052495,64.693351,78.603305,57.783636,51.601541,34.753203,12.748759,6.430365,27.985318
5,4,AS_MRC-5_20241112,14,71.285275,73.531719,57.684808,90.910767,67.440359,82.063580,61.383564,55.785689,36.379861,13.441649,6.690461,29.633609
6,4,AS_MRC-5_20241112,16,77.479488,78.977260,62.539189,94.287710,72.343355,87.085051,65.028390,59.776010,38.477941,13.314678,6.818232,31.391054
7,4,AS_MRC-5_20241112,18,82.489044,83.788110,67.986091,96.623754,77.248121,90.407514,69.861074,64.373566,40.007799,14.420095,6.902282,33.776778
8,4,AS_MRC-5_20241112,20,86.754021,87.672321,72.334049,98.144554,81.596744,93.415114,73.444763,68.337416,42.367888,14.427952,7.062340,36.278298
9,4,AS_MRC-5_20241112,22,90.615394,90.831394,77.123130,99.153380,85.782691,95.452286,76.678704,71.505789,44.705994,16.701224,7.176446,38.762726
10,4,AS_MRC-5_20241112,24,93.541406,93.999999,80.687346,99.607945,88.754479,97.158967,80.135009,75.473724,46.710371,16.825958,7.209575,40.554315
11,4,AS_MRC-5_20241112,26,95.496276,95.974382,84.003394,99.786921,91.319830,98.204188,83.778804,77.448183,49.880197,17.834430,7.331236,43.867510
12,4,AS_MRC-5_20241112,28,97.103558,97.713796,87.658825,99.892300,93.716079,98.986499,86.585134,81.144840,52.009429,18.509041,7.680997,46.284430
13,4,AS_MRC-5_20241112,30,98.466479,98.736295,91.307649,99.965765,95.893158,99.325192,89.762934,84.185008,54.935817,18.944286,7.211546,49.600192
14,4,AS_MRC-5_20241112,32,99.266379,99.365521,94.016548,99.963769,97.509282,99.711021,92.206451,86.901673,57.950771,19.792777,7.216917,53.179144
15,4,AS_MRC-5_20241112,34,99.640461,99.699155,96.008443,99.987074,98.419361,99.860886,94.685900,89.940434,59.852909,21.446736,7.064430,57.022106
16,4,AS_MRC-5_20241112,36,99.850580,99.846844,97.784973,99.984803,99.185533,99.911901,96.440098,92.240515,64.303666,22.290550,7.137980,61.422390
17,4,AS_MRC-5_20241112,38,99.907121,99.930200,98.675048,99.994073,99.559375,99.939381,97.374656,93.743064,66.954543,23.031799,7.075768,65.359564
18,4,AS_MRC-5_20241112,40,99.919147,99.954279,99.267924,99.991604,99.781218,99.967600,98.206298,95.213257,69.952469,24.445373,6.840820,69.675767
19,4,AS_MRC-5_20241112,42,99.966901,99.982345,99.518956,99.991871,99.897447,99.986184,98.849110,96.582136,72.940986,25.666315,6.914413,73.450346
20,4,AS_MRC-5_20241112,44,99.965648,99.994785,99.691894,99.996402,99.948179,99.981207,99.236376,97.260603,75.466380,26.730059,7.550860,77.117524
21,4,AS_MRC-5_20241112,46,99.978299,99.988098,99.824643,99.989600,99.960480,99.996112,99.401962,97.746639,78.583299,27.678215,6.723744,80.763335
22,4,AS_MRC-5_20241112,48,99.978060,99.975510,99.880951,99.996232,99.969810,99.997343,99.521642,98.549879,81.536263,28.904379,6.673934,83.733956
23,4,AS_MRC-5_20241112,50,99.986287,99.995413,99.915341,99.995866,99.982685,99.996662,99.643344,98.559098,84.228386,31.029378,6.763830,86.939679
24,4,AS_MRC-5_20241112,52,99.975530,99.998223,99.924185,99.998675,99.990003,99.994398,99.704994,98.859780,86.341496,32.215729,6.629485,89.346007
25,4,AS_MRC-5_20241112,54,99.967960,99.991213,99.927437,100.000000,99.994372,99.988985,99.824489,99.117824,88.757635,34.077381,6.355911,91.498473
26,4,AS_MRC-5_20241112,56,99.993486,99.989250,99.964501,99.997771,99.986245,99.983496,99.837006,99.221886,90.863902,35.641262,6.302576,93.590416
27,4,AS_MRC-5_20241112,58,99.985095,99.994330,99.947095,99.996166,99.989786,99.994364,99.858421,99.438823,92.193274,37.493223,6.531419,95.142279
28,4,AS_MRC-5_20241112,60,99.988261,99.994227,99.980071,99.998395,99.992375,99.996865,99.845166,99.431901,93.729337,40.047475,6.591421,96.066198
29,4,AS_MRC-5_20241112,62,99.978964,99.995610,99.970757,99.997744,99.987321,99.995158,99.839869,99.455521,94.389559,42.089894,6.625976,96.874285
30,4,AS_MRC-5_20241112,64,99.992836,99.989260,99.964009,100.000000,99.994656,99.998214,99.833084,99.431881,95.783346,43.615680,6.670374,97.822356
31,4,AS_MRC-5_20241112,66,99.987363,99.984489,99.965865,99.998675,99.996369,99.994276,99.843164,99.373746,96.564938,46.026524,6.358720,98.286546
32,4,AS_MRC-5_20241112,68,99.991045,99.987081,99.974042,99.999076,99.997029,99.989285,99.863654,99.377021,97.050189,47.503498,6.535756,98.436420
33,4,AS_MRC-5_20241112,70,99.978749,99.988006,99.983896,99.997302,99.994287,99.992683,99.841948,99.585569,97.544285,50.556132,6.462351,98.981758
34,4,AS_MRC-5_20241112,72,99.989840,99.998275,99.980807,100.000000,99.986929,99.994362,99.888929,99.607390,97.943219,52.371075,6.700789,99.080034

,Plate_Number,Vessel_Name,Elapsed,P11 LIN10-0C-b4,P15 LIN9-0C-b2-s1,P16 LIN8-0B-b2B-s1,P20 LIN7-0C-b3,P23 LIN6-0C-b1-s1,P24 LIN3-0A-b2-s2-ss1
0,4,AS_MRC-5_20241112,4,52.532514,55.831471,55.806122,41.067544,19.464780,14.138969
1,4,AS_MRC-5_20241112,6,56.446313,61.150817,60.770860,44.637152,19.918502,14.719277
2,4,AS_MRC-5_20241112,8,59.730908,64.602268,64.960839,48.417467,20.992682,15.836408
3,4,AS_MRC-5_20241112,10,63.417051,67.856079,68.853677,52.069271,22.392424,16.789717
4,4,AS_MRC-5_20241112,12,67.534735,70.612598,71.648328,54.692589,23.750981,17.207841
5,4,AS_MRC-5_20241112,14,72.408497,74.297787,74.751969,58.584626,24.910755,18.162035
6,4,AS_MRC-5_20241112,16,78.228374,78.413449,79.714203,62.402200,25.896309,19.104643
7,4,AS_MRC-5_20241112,18,83.138577,82.304922,83.827818,67.117320,27.213947,20.339530
8,4,AS_MRC-5_20241112,20,87.213171,85.239301,87.505929,70.891089,28.397920,21.670319
9,4,AS_MRC-5_20241112,22,90.723394,88.138255,90.617489,74.092246,30.703609,22.969586
10,4,AS_MRC-5_20241112,24,93.770702,90.147646,92.956723,77.804366,31.768164,23.881945
11,4,AS_MRC-5_20241112,26,95.735329,91.895158,94.762009,80.613493,33.857314,25.599373
12,4,AS_MRC-5_20241112,28,97.408677,93.775563,96.351289,83.864987,35.259235,26.982713
13,4,AS_MRC-5_20241112,30,98.601387,95.636707,97.609175,86.973971,36.940052,28.405869
14,4,AS_MRC-5_20241112,32,99.315950,96.990158,98.610152,89.554062,38.871774,30.198030
15,4,AS_MRC-5_20241112,34,99.669808,97.997758,99.140124,92.313167,40.649822,32.043268
16,4,AS_MRC-5_20241112,36,99.848712,98.884888,99.548717,94.340306,43.297108,34.280185
17,4,AS_MRC-5_20241112,38,99.918661,99.334560,99.749378,95.558860,44.993171,36.217666
18,4,AS_MRC-5_20241112,40,99.936713,99.629764,99.874409,96.709778,47.198921,38.258294
19,4,AS_MRC-5_20241112,42,99.974623,99.755414,99.941816,97.715623,49.303651,40.182379
20,4,AS_MRC-5_20241112,44,99.980216,99.844148,99.964693,98.248489,51.098219,42.334192
21,4,AS_MRC-5_20241112,46,99.983198,99.907121,99.978296,98.574301,53.130757,43.743540
22,4,AS_MRC-5_20241112,48,99.976785,99.938592,99.983576,99.035761,55.220321,45.203945
23,4,AS_MRC-5_20241112,50,99.990850,99.955604,99.989674,99.101221,57.628882,46.851754
24,4,AS_MRC-5_20241112,52,99.986876,99.961430,99.992200,99.282387,59.278613,47.987746
25,4,AS_MRC-5_20241112,54,99.979586,99.963719,99.991679,99.471156,61.417508,48.927192
26,4,AS_MRC-5_20241112,56,99.991368,99.981136,99.984871,99.529446,63.252582,49.946496
27,4,AS_MRC-5_20241112,58,99.989712,99.971631,99.992075,99.648622,64.843248,50.836849
28,4,AS_MRC-5_20241112,60,99.991244,99.989233,99.994620,99.638534,66.888406,51.328809
29,4,AS_MRC-5_20241112,62,99.987287,99.984251,99.991239,99.647695,68.239726,51.750131
30,4,AS_MRC-5_20241112,64,99.991048,99.982004,99.996435,99.632483,69.699513,52.246365
31,4,AS_MRC-5_20241112,66,99.985926,99.982270,99.995323,99.608455,71.295731,52.322633
32,4,AS_MRC-5_20241112,68,99.989063,99.986559,99.993157,99.620338,72.276843,52.486088
33,4,AS_MRC-5_20241112,70,99.983377,99.990599,99.993485,99.713758,74.050209,52.722054
34,4,AS_MRC-5_20241112,72,99.994057,99.990404,99.990646,99.748159,75.157147,52.890411

Wrote replaced data to: /Users/allielas/HTP_fibroblasts_mitolyso/proliferation_growth_curves/Incucyte_sheets/r4_processed.xlsx

/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Plate_Number,Vessel_Name,Elapsed,"Doxo_P17 LIN13-0C-b2-s3 (A1), Image 1","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 2","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 3","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 4","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 5","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 6","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 7",...,"P11 LIN11-0C-b5 (B3), Image 9","P11 LIN11-0C-b5 (B4), Image 1","P11 LIN11-0C-b5 (B4), Image 2","P11 LIN11-0C-b5 (B4), Image 3","P11 LIN11-0C-b5 (B4), Image 4","P11 LIN11-0C-b5 (B4), Image 5","P11 LIN11-0C-b5 (B4), Image 6","P11 LIN11-0C-b5 (B4), Image 7","P11 LIN11-0C-b5 (B4), Image 8","P11 LIN11-0C-b5 (B4), Image 9"
0,5,20250328_AS_MRC5_Confluence_Rep5,0,16.95941,12.20751,7.518369,12.25476,95.70564,11.95811,14.08961,...,23.34995,37.89827,28.58972,17.96697,27.13245,31.83832,27.26126,32.29519,23.21965,17.24855
1,5,20250328_AS_MRC5_Confluence_Rep5,2,19.22947,12.51844,7.495492,13.62639,97.65619,12.72679,15.23540,...,25.53308,39.59230,30.65191,20.78016,28.97720,38.30747,28.18720,34.85194,24.62528,18.50463
2,5,20250328_AS_MRC5_Confluence_Rep5,4,19.03634,13.10977,6.484990,13.02522,97.72317,13.53884,15.19265,...,27.76429,42.31513,32.72304,21.97054,30.43931,40.52488,28.99188,36.03030,26.74279,21.37524
3,5,20250328_AS_MRC5_Confluence_Rep5,6,18.50258,14.53323,7.975101,14.00964,97.77971,12.65277,14.90200,...,28.71141,44.85030,34.54846,23.56131,32.32804,41.99745,29.74377,38.98716,27.59881,22.72952
4,5,20250328_AS_MRC5_Confluence_Rep5,8,18.09386,13.54226,7.403913,14.26136,98.07030,12.29601,14.78843,...,31.18875,51.01098,37.82288,25.40018,34.56307,47.34866,32.32272,41.08453,29.58766,24.33040
5,5,20250328_AS_MRC5_Confluence_Rep5,10,18.89034,13.47888,7.710813,14.58554,98.19282,13.75191,14.65567,...,33.42042,53.92714,40.54264,28.78858,38.29456,50.61551,35.11418,44.52995,32.26808,26.26174
6,5,20250328_AS_MRC5_Confluence_Rep5,12,18.15115,13.87340,8.059918,14.17149,97.78539,12.06130,13.47028,...,37.49624,56.68611,43.29963,30.86866,41.04349,52.49863,36.90737,47.52288,34.44309,27.78368
7,5,20250328_AS_MRC5_Confluence_Rep5,14,18.64702,13.60925,7.840225,13.71101,97.61657,13.22866,14.65219,...,40.14054,57.60277,46.56558,32.09988,42.63194,54.49717,39.38483,49.93622,36.76675,29.44021
8,5,20250328_AS_MRC5_Confluence_Rep5,16,18.17000,13.83229,8.262607,15.31913,97.49917,13.24068,14.43339,...,42.40937,61.60075,48.88815,33.18660,45.43016,57.29097,41.03106,52.36225,39.02754,30.54210
9,5,20250328_AS_MRC5_Confluence_Rep5,18,18.19985,13.08518,7.983023,14.81630,97.35986,14.71379,15.07444,...,45.62036,63.45026,51.81538,36.54789,50.36980,61.94753,45.35307,55.21074,40.14505,32.31398
10,5,20250328_AS_MRC5_Confluence_Rep5,20,19.35915,14.42922,8.117898,14.83152,97.55532,12.99812,14.20974,...,48.75676,71.12024,56.52001,38.92960,52.06115,64.67849,47.90305,58.98389,42.86570,34.66592
11,5,20250328_AS_MRC5_Confluence_Rep5,22,19.58281,14.61231,8.399393,14.10743,97.40384,15.35423,14.31128,...,50.98127,76.69204,58.99427,41.40611,57.31636,71.82747,50.66434,63.07821,45.74117,38.25127
12,5,20250328_AS_MRC5_Confluence_Rep5,24,20.65334,14.17395,8.706566,14.50694,97.32687,15.71480,14.29510,...,56.51688,79.49108,66.49850,45.53990,61.47515,77.73205,55.16014,68.98546,50.82386,41.63667
13,5,20250328_AS_MRC5_Confluence_Rep5,26,20.79190,14.41481,7.476371,14.97903,97.25517,14.41413,14.40914,...,62.00195,82.30851,69.68121,47.92989,66.66507,78.56917,60.70210,73.98109,55.76144,45.63523
14,5,20250328_AS_MRC5_Confluence_Rep5,28,21.11246,15.55118,8.381021,14.87230,96.84290,14.41311,14.66763,...,67.30038,85.34875,75.95041,50.59474,71.68132,84.70013,64.97309,79.29885,60.72129,49.06038
15,5,20250328_AS_MRC5_Confluence_Rep5,30,20.86408,14.46699,8.633495,14.84675,97.10828,15.97472,13.65432,...,72.67188,90.58163,79.21342,54.31668,76.98249,86.97504,69.22318,82.81577,67.73936,52.65168
16,5,20250328_AS_MRC5_Confluence_Rep5,32,19.68729,14.49273,7.304482,14.39112,97.06812,15.47852,15.06925,...,76.00327,93.97762,82.88099,59.19491,82.37011,91.16327,73.92085,87.45670,73.08750,57.57756
17,5,20250328_AS_MRC5_Confluence_Rep5,34,20.11807,15.13652,7.434986,14.41488,97.22449,15.16834,15.40381,...,80.81170,96.22998,88.11789,64.72519,84.64201,93.94476,78.24812,91.35905,78.49787,63.59266
18,5,20250328_AS_MRC5_Confluence_Rep5,36,19.96196,14.60767,6.850141,13.88849,97.57505,15.51792,15.60813,...,86.42421,97.46769,91.86202,68.06824,89.06038,96.44517,83.75211,94.13229,84.36824,68.01635
19,5,20250328_AS_MRC5_Confluence_Rep5,38,20.79552,14.09985,6.829312,13.90106,97.82342,14.37001,15.25063,...,90.41766,98.64374,95.45699,73.94675,92.60489,98.27018,88.32523,96.69109,88.15963,74.01428
20,5,20250328_AS_MRC5_Confluence_Rep5,40,19.66510,14.27441,7.081647,14.63792,97.46333,14.44131,15.31277,...,93.81747,99.38496,97.52862,79.53104,94.58744,99.20549,91.84754,98.47308,92.59827,79.38087
21,5,20250328_AS_MRC5_Confluence_Rep5,42,19.32194,14.39699,6.979347,13.95480,97.85388,16.77782,15.79887,...,96.86428,99.63799,98.45300,83.69891,96.89356,99.60023,95.52755,99.42785,95.63108,84.84464
22,5,20250328_AS_MRC5_Confluence_Rep5,44,19.31975,14.34700,7.560711,14.53972,97.49835,16.29466,16.31952,...,97.74905,99.83815,99.47102,87.77056,98.86527,99.70900,97.40282,99.76923,97.56432,89.39630
23,5,20250328_AS_MRC5_Confluence_Rep5,46,20.88922,15.43091,7.904078,14.44459,97.87382,15.50815,16.69129,...,99.08299,99.94912,99.48569,89.96524,99.45968,99.86233,98.24969,99.97029,98.69079,92.91882
24,5,20250328_AS_MRC5_Confluence_Rep5,48,19.75121,15.32459,7.114019,14.34577,97.58611,15.98824,16.51927,...,99.64214,99.98573,99.82755,92.77904,99.76589,99.95595,98.97878,99.95404,99.24101,95.58914
25,5,20250328_AS_MRC5_Confluence_Rep5,50,19.47115,15.83390,6.391158,13.96204,97.54781,17.51427,16.54529,...,99.71610,99.95430,99.92904,94.30451,99.87953,99.96101,99.24879,99.96674,99.56670,96.87233
26,5,20250328_AS_MRC5_Confluence_Rep5,52,20.16124,15.03394,6.348408,16.10147,97.63194,18.19097,15.62322,...,99.75654,99.99795,99.96400,95.81895,99.94126,99.98504,99.63853,99.98941,99.72178,98.41319
27,5,20250328_AS_MRC5_Confluence_Rep5,54,20.08209,16.22575,6.233406,15.14655,97.68438,19.31900,16.75870,...,99.95950,100.00000,100.00000,97.14071,99.91566,99.97691,99.59564,99.99795,99.82776,99.11536
28,5,20250328_AS_MRC5_Confluence_Rep5,56,19.79349,15.43501,5.880066,14.60111,97.77692,20.29447,16.34540,...,99.95068,99.99378,99.98804,98.11488,99.99160,99.99741,99.79218,100.00000,99.88152,99.50523
29,5,20250328_AS_MRC5_Confluence_Rep5,58,20.53731,15.75694,6.368758,15.31748,98.40601,20.46527,16.74381,...,99.96394,99.99945,99.97581,98.37016,99.98422,100.00000,99.70750,100.00000,99.98190,99.66558
30,5,20250328_AS_MRC5_Confluence_Rep5,60,20.95996,15.19073,6.217561,14.82838,98.41790,19.83917,14.76398,...,100.00000,99.99780,99.99631,98.67815,100.00000,99.98422,99.83288,100.00000,99.95738,99.71352
31,5,20250328_AS_MRC5_Confluence_Rep5,62,21.21927,15.07908,5.926436,16.15098,98.42083,19.25842,16.27144,...,99.98531,100.00000,99.99719,99.16378,99.99597,99.99323,99.85516,100.00000,99.91435,99.87093
32,5,20250328_AS_MRC5_Confluence_Rep5,64,21.51934,15.17489,6.020473,15.10292,98.52183,19.66442,15.90049,...,99.98798,100.00000,99.98470,99.24940,100.00000,99.99823,99.90022,100.00000,99.94045,99.84579
33,5,20250328_AS_MRC5_Confluence_Rep5,66,22.28577,15.30990,6.556011,15.38898,98.48515,18.43381,16.54133,...,99.99378,100.00000,100.00000,99.58383,99.99487,99.98648,99.88137,100.00000,99.99009,99.97493
34,5,20250328_AS_MRC5_Confluence_Rep5,68,21.98215,14.55590,7.050848,15.30287,98.43694,16.80931,15.83438,...,99.96497,100.00000,100.00000,99.71898,100.00000,99.91026,99.90664,100.00000,99.96830,99.88916
35,5,20250328_AS_MRC5_Confluence_Rep5,70,22.47057,13.60884,6.339939,15.92972,98.02495,19.59572,16.18526,...,100.00000,100.00000,100.00000,99.80625,100.00000,99.99849,99.93129,100.00000,99.98853,99.95479
36,5,20250328_AS_MRC5_Confluence_Rep5,72,22.53517,15.93920,6.971495,17.68958,98.19096,18.34332,16.28053,...,100.00000,100.00000,100.00000,99.70518,100.00000,99.99023,99.93867,100.00000,99.98497,99.98380

,Plate_Number,Vessel_Name,Elapsed,"Doxo_P17 LIN13-0C-b2-s3 (A1), Image 1","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 2","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 3","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 4","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 6","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 7","Doxo_P17 LIN13-0C-b2-s3 (A1), Image 8",...,"P11 LIN11-0C-b5 (B3), Image 8","P11 LIN11-0C-b5 (B3), Image 9","P11 LIN11-0C-b5 (B4), Image 1","P11 LIN11-0C-b5 (B4), Image 2","P11 LIN11-0C-b5 (B4), Image 3","P11 LIN11-0C-b5 (B4), Image 4","P11 LIN11-0C-b5 (B4), Image 6","P11 LIN11-0C-b5 (B4), Image 7","P11 LIN11-0C-b5 (B4), Image 8","P11 LIN11-0C-b5 (B4), Image 9"
0,5,20250328_AS_MRC5_Confluence_Rep5,4,19.03634,13.10977,6.484990,13.02522,13.53884,15.19265,32.95380,...,26.69040,27.76429,42.31513,32.72304,21.97054,30.43931,28.99188,36.03030,26.74279,21.37524
1,5,20250328_AS_MRC5_Confluence_Rep5,6,18.50258,14.53323,7.975101,14.00964,12.65277,14.90200,31.70625,...,25.61790,28.71141,44.85030,34.54846,23.56131,32.32804,29.74377,38.98716,27.59881,22.72952
2,5,20250328_AS_MRC5_Confluence_Rep5,8,18.09386,13.54226,7.403913,14.26136,12.29601,14.78843,31.07886,...,27.58332,31.18875,51.01098,37.82288,25.40018,34.56307,32.32272,41.08453,29.58766,24.33040
3,5,20250328_AS_MRC5_Confluence_Rep5,10,18.89034,13.47888,7.710813,14.58554,13.75191,14.65567,31.81340,...,30.84120,33.42042,53.92714,40.54264,28.78858,38.29456,35.11418,44.52995,32.26808,26.26174
4,5,20250328_AS_MRC5_Confluence_Rep5,12,18.15115,13.87340,8.059918,14.17149,12.06130,13.47028,32.27422,...,33.89170,37.49624,56.68611,43.29963,30.86866,41.04349,36.90737,47.52288,34.44309,27.78368
5,5,20250328_AS_MRC5_Confluence_Rep5,14,18.64702,13.60925,7.840225,13.71101,13.22866,14.65219,31.32867,...,36.22186,40.14054,57.60277,46.56558,32.09988,42.63194,39.38483,49.93622,36.76675,29.44021
6,5,20250328_AS_MRC5_Confluence_Rep5,16,18.17000,13.83229,8.262607,15.31913,13.24068,14.43339,31.42045,...,38.69612,42.40937,61.60075,48.88815,33.18660,45.43016,41.03106,52.36225,39.02754,30.54210
7,5,20250328_AS_MRC5_Confluence_Rep5,18,18.19985,13.08518,7.983023,14.81630,14.71379,15.07444,31.76676,...,38.45832,45.62036,63.45026,51.81538,36.54789,50.36980,45.35307,55.21074,40.14505,32.31398
8,5,20250328_AS_MRC5_Confluence_Rep5,20,19.35915,14.42922,8.117898,14.83152,12.99812,14.20974,31.13144,...,41.32997,48.75676,71.12024,56.52001,38.92960,52.06115,47.90305,58.98389,42.86570,34.66592
9,5,20250328_AS_MRC5_Confluence_Rep5,22,19.58281,14.61231,8.399393,14.10743,15.35423,14.31128,30.14956,...,45.48248,50.98127,76.69204,58.99427,41.40611,57.31636,50.66434,63.07821,45.74117,38.25127
10,5,20250328_AS_MRC5_Confluence_Rep5,24,20.65334,14.17395,8.706566,14.50694,15.71480,14.29510,29.72868,...,50.23505,56.51688,79.49108,66.49850,45.53990,61.47515,55.16014,68.98546,50.82386,41.63667
11,5,20250328_AS_MRC5_Confluence_Rep5,26,20.79190,14.41481,7.476371,14.97903,14.41413,14.40914,28.17240,...,55.46136,62.00195,82.30851,69.68121,47.92989,66.66507,60.70210,73.98109,55.76144,45.63523
12,5,20250328_AS_MRC5_Confluence_Rep5,28,21.11246,15.55118,8.381021,14.87230,14.41311,14.66763,28.67201,...,60.29713,67.30038,85.34875,75.95041,50.59474,71.68132,64.97309,79.29885,60.72129,49.06038
13,5,20250328_AS_MRC5_Confluence_Rep5,30,20.86408,14.46699,8.633495,14.84675,15.97472,13.65432,27.44386,...,64.47929,72.67188,90.58163,79.21342,54.31668,76.98249,69.22318,82.81577,67.73936,52.65168
14,5,20250328_AS_MRC5_Confluence_Rep5,32,19.68729,14.49273,7.304482,14.39112,15.47852,15.06925,27.92484,...,68.63451,76.00327,93.97762,82.88099,59.19491,82.37011,73.92085,87.45670,73.08750,57.57756
15,5,20250328_AS_MRC5_Confluence_Rep5,34,20.11807,15.13652,7.434986,14.41488,15.16834,15.40381,27.35468,...,73.80586,80.81170,96.22998,88.11789,64.72519,84.64201,78.24812,91.35905,78.49787,63.59266
16,5,20250328_AS_MRC5_Confluence_Rep5,36,19.96196,14.60767,6.850141,13.88849,15.51792,15.60813,27.88708,...,78.55769,86.42421,97.46769,91.86202,68.06824,89.06038,83.75211,94.13229,84.36824,68.01635
17,5,20250328_AS_MRC5_Confluence_Rep5,38,20.79552,14.09985,6.829312,13.90106,14.37001,15.25063,28.19363,...,83.15764,90.41766,98.64374,95.45699,73.94675,92.60489,88.32523,96.69109,88.15963,74.01428
18,5,20250328_AS_MRC5_Confluence_Rep5,40,19.66510,14.27441,7.081647,14.63792,14.44131,15.31277,28.19322,...,87.47562,93.81747,99.38496,97.52862,79.53104,94.58744,91.84754,98.47308,92.59827,79.38087
19,5,20250328_AS_MRC5_Confluence_Rep5,42,19.32194,14.39699,6.979347,13.95480,16.77782,15.79887,28.62598,...,90.37273,96.86428,99.63799,98.45300,83.69891,96.89356,95.52755,99.42785,95.63108,84.84464
20,5,20250328_AS_MRC5_Confluence_Rep5,44,19.31975,14.34700,7.560711,14.53972,16.29466,16.31952,28.57216,...,93.56554,97.74905,99.83815,99.47102,87.77056,98.86527,97.40282,99.76923,97.56432,89.39630
21,5,20250328_AS_MRC5_Confluence_Rep5,46,20.88922,15.43091,7.904078,14.44459,15.50815,16.69129,30.17851,...,95.23526,99.08299,99.94912,99.48569,89.96524,99.45968,98.24969,99.97029,98.69079,92.91882
22,5,20250328_AS_MRC5_Confluence_Rep5,48,19.75121,15.32459,7.114019,14.34577,15.98824,16.51927,29.31183,...,96.58162,99.64214,99.98573,99.82755,92.77904,99.76589,98.97878,99.95404,99.24101,95.58914
23,5,20250328_AS_MRC5_Confluence_Rep5,50,19.47115,15.83390,6.391158,13.96204,17.51427,16.54529,29.82552,...,98.01669,99.71610,99.95430,99.92904,94.30451,99.87953,99.24879,99.96674,99.56670,96.87233
24,5,20250328_AS_MRC5_Confluence_Rep5,52,20.16124,15.03394,6.348408,16.10147,18.19097,15.62322,31.12639,...,98.52012,99.75654,99.99795,99.96400,95.81895,99.94126,99.63853,99.98941,99.72178,98.41319
25,5,20250328_AS_MRC5_Confluence_Rep5,54,20.08209,16.22575,6.233406,15.14655,19.31900,16.75870,31.27601,...,99.34885,99.95950,100.00000,100.00000,97.14071,99.91566,99.59564,99.99795,99.82776,99.11536
26,5,20250328_AS_MRC5_Confluence_Rep5,56,19.79349,15.43501,5.880066,14.60111,20.29447,16.34540,30.48329,...,99.53316,99.95068,99.99378,99.98804,98.11488,99.99160,99.79218,100.00000,99.88152,99.50523
27,5,20250328_AS_MRC5_Confluence_Rep5,58,20.53731,15.75694,6.368758,15.31748,20.46527,16.74381,30.93115,...,99.64221,99.96394,99.99945,99.97581,98.37016,99.98422,99.70750,100.00000,99.98190,99.66558
28,5,20250328_AS_MRC5_Confluence_Rep5,60,20.95996,15.19073,6.217561,14.82838,19.83917,14.76398,29.61279,...,99.69118,100.00000,99.99780,99.99631,98.67815,100.00000,99.83288,100.00000,99.95738,99.71352
29,5,20250328_AS_MRC5_Confluence_Rep5,62,21.21927,15.07908,5.926436,16.15098,19.25842,16.27144,29.91436,...,99.86786,99.98531,100.00000,99.99719,99.16378,99.99597,99.85516,100.00000,99.91435,99.87093
30,5,20250328_AS_MRC5_Confluence_Rep5,64,21.51934,15.17489,6.020473,15.10292,19.66442,15.90049,29.58138,...,99.93075,99.98798,100.00000,99.98470,99.24940,100.00000,99.90022,100.00000,99.94045,99.84579
31,5,20250328_AS_MRC5_Confluence_Rep5,66,22.28577,15.30990,6.556011,15.38898,18.43381,16.54133,30.37129,...,99.94543,99.99378,100.00000,100.00000,99.58383,99.99487,99.88137,100.00000,99.99009,99.97493
32,5,20250328_AS_MRC5_Confluence_Rep5,68,21.98215,14.55590,7.050848,15.30287,16.80931,15.83438,32.02299,...,99.93819,99.96497,100.00000,100.00000,99.71898,100.00000,99.90664,100.00000,99.96830,99.88916
33,5,20250328_AS_MRC5_Confluence_Rep5,70,22.47057,13.60884,6.339939,15.92972,19.59572,16.18526,33.42254,...,99.92125,100.00000,100.00000,100.00000,99.80625,100.00000,99.93129,100.00000,99.98853,99.95479
34,5,20250328_AS_MRC5_Confluence_Rep5,72,22.53517,15.93920,6.971495,17.68958,18.34332,16.28053,34.78106,...,99.97350,100.00000,100.00000,100.00000,99.70518,100.00000,99.93867,100.00000,99.98497,99.98380

,Plate_Number,Vessel_Name,Elapsed,Doxo_P17 LIN13-0C-b2-s3 (A1),Doxo_P17 LIN13-0C-b2-s3 (A2),P33 LIN3-0A-b2-s1-ss1 (A3),P33 LIN3-0A-b2-s1-ss1 (A4),P32 LIN3-0A-b2-s1-ss1-sss1 (B1),P32 LIN3-0A-b2-s1-ss1-sss1 (B2),P29 LIN3-0A-b2-s1-ss2 (B3),...,P23 LIN7-0C-b3-s1 (C3),P23 LIN7-0C-b3-s1 (C4),P19 LIN8-0B-b2B-s1-ss1 (A1),P19 LIN8-0B-b2B-s1-ss1 (A2),P19 LIN8-0B-b2B-s1-ss2 (A3),P19 LIN8-0B-b2B-s1-ss2 (A4),P15 LIN6-0C-b1-s2 (B1),P15 LIN6-0C-b1-s2 (B2),P11 LIN11-0C-b5 (B3),P11 LIN11-0C-b5 (B4)
0,5,20250328_AS_MRC5_Confluence_Rep5,4,17.116689,15.607328,14.224698,18.344701,3.841450,3.771093,52.957676,...,15.889883,19.960828,12.985377,12.925888,8.796609,11.310747,23.689654,22.420576,26.992161,30.073529
1,5,20250328_AS_MRC5_Confluence_Rep5,6,17.134488,15.559293,13.727940,18.501742,4.369690,3.981848,55.952385,...,16.648136,20.483159,13.983855,13.942385,9.641557,12.462321,25.118179,23.681520,28.432309,31.793421
2,5,20250328_AS_MRC5_Confluence_Rep5,8,16.760227,15.325534,13.720832,18.272175,4.330815,3.996420,57.805136,...,16.777600,20.881483,15.366279,14.903204,10.244181,14.043634,27.444666,25.863260,31.106121,34.515303
3,5,20250328_AS_MRC5_Confluence_Rep5,10,17.022447,15.468418,13.987482,18.231616,4.371867,4.188309,58.929175,...,17.341000,21.412413,16.769172,16.027806,11.015164,15.060590,28.316306,27.342724,33.545944,37.465859
4,5,20250328_AS_MRC5_Confluence_Rep5,12,16.611411,15.280308,13.919881,18.175406,4.539240,4.187088,60.797186,...,17.806440,22.033749,17.849958,17.069185,11.880719,16.121109,30.293692,29.076334,36.791573,39.819364
5,5,20250328_AS_MRC5_Confluence_Rep5,14,16.682572,14.729840,13.350675,17.649266,4.695516,4.477428,62.389551,...,18.128225,22.879364,19.354100,18.858174,12.588572,16.795030,32.079516,31.402775,38.875209,41.803522
6,5,20250328_AS_MRC5_Confluence_Rep5,16,16.898252,15.073557,13.567251,17.538719,4.356962,4.463343,63.588351,...,19.107050,23.283799,20.280113,19.992334,13.689714,17.192869,33.486644,33.514744,40.550971,44.008576
7,5,20250328_AS_MRC5_Confluence_Rep5,18,16.849988,14.604696,13.345930,17.634968,4.527792,4.769611,64.739444,...,20.438129,23.961564,21.164773,21.257896,14.943376,18.517529,35.401421,35.466100,42.730104,46.900771
8,5,20250328_AS_MRC5_Confluence_Rep5,20,16.730700,15.229388,13.477058,17.126978,4.658587,4.559992,66.688963,...,21.338035,24.930401,22.364970,22.586219,15.890796,19.601059,37.126622,37.854999,46.021114,50.381195
9,5,20250328_AS_MRC5_Confluence_Rep5,22,16.785170,14.439508,13.294114,17.584731,4.789638,4.560180,68.510375,...,22.058490,25.344347,23.930380,23.994712,17.584978,21.415655,39.230076,40.383145,50.121326,54.017971
10,5,20250328_AS_MRC5_Confluence_Rep5,24,17.131739,14.803670,13.196295,17.490710,5.012463,4.938188,70.100514,...,22.692022,26.052100,25.736733,25.646544,18.173426,22.717446,41.808723,43.803306,54.597269,58.701345
11,5,20250328_AS_MRC5_Confluence_Rep5,26,16.784111,15.048826,13.233907,17.081169,5.112927,5.122838,72.429034,...,24.004716,26.941104,27.352250,27.140446,19.333984,24.234496,44.961600,47.011281,58.927661,62.833067
12,5,20250328_AS_MRC5_Confluence_Rep5,28,17.189089,15.255638,13.746108,17.297141,5.256441,5.438958,75.954969,...,24.893524,28.763031,29.014132,28.782669,20.235690,25.367740,48.259633,50.589101,63.694833,67.203604
13,5,20250328_AS_MRC5_Confluence_Rep5,30,16.968147,15.344450,13.502744,16.829081,5.657207,5.441801,78.861321,...,26.010995,29.796985,30.603024,30.457035,21.285065,26.302874,51.764826,54.660215,68.428645,71.690526
14,5,20250328_AS_MRC5_Confluence_Rep5,32,16.837603,14.782938,13.783395,17.635824,5.624300,5.842899,81.588108,...,27.257311,30.552105,33.045474,32.881532,22.442583,27.804647,55.211719,58.174849,72.518084,76.308280
15,5,20250328_AS_MRC5_Confluence_Rep5,34,16.914601,15.563323,13.346587,16.953919,6.032638,5.896755,84.698557,...,28.459473,32.015250,34.905057,34.273826,24.405945,29.603210,58.977665,62.682361,77.651210,80.676596
16,5,20250328_AS_MRC5_Confluence_Rep5,36,16.748951,15.454692,14.121485,16.526859,5.996384,6.126384,86.669250,...,29.682738,33.948622,36.842780,36.827381,26.058052,31.446266,62.258369,67.133196,82.778906,84.590915
17,5,20250328_AS_MRC5_Confluence_Rep5,38,16.722495,15.362507,14.140172,16.682076,6.227968,6.222641,88.698558,...,30.689030,34.807739,38.791749,38.562378,27.194448,33.807526,66.397504,71.592517,87.305879,88.480325
18,5,20250328_AS_MRC5_Confluence_Rep5,40,16.903928,15.422149,14.802729,17.736928,6.207899,6.341092,90.868521,...,31.858953,36.156549,40.621149,40.873382,29.447849,35.879356,70.341934,76.399424,91.062255,91.666477
19,5,20250328_AS_MRC5_Confluence_Rep5,42,17.254262,15.403045,14.386582,17.714450,6.636851,6.274644,93.272016,...,32.769815,37.580551,42.946095,43.508361,30.801710,37.840611,74.247736,80.457939,93.996955,94.264323
20,5,20250328_AS_MRC5_Confluence_Rep5,44,17.301109,15.450866,14.865425,17.648821,6.874521,6.347296,94.244566,...,34.122106,39.575722,45.218471,45.463644,33.414461,39.951571,78.264981,84.370122,95.911190,96.259709
21,5,20250328_AS_MRC5_Confluence_Rep5,46,17.801767,15.094121,14.841292,18.079928,7.117553,6.550028,95.591696,...,35.332023,40.878875,48.292489,48.353630,35.272054,42.393288,81.591230,88.219912,97.286619,97.336165
22,5,20250328_AS_MRC5_Confluence_Rep5,48,17.434619,15.260487,14.724180,17.766068,7.448543,6.803123,96.671376,...,36.565393,42.371304,51.599811,50.139870,37.368565,44.360076,84.347559,90.683860,98.303234,98.265147
23,5,20250328_AS_MRC5_Confluence_Rep5,50,17.572635,15.421270,15.112617,18.327313,7.074922,6.998538,97.340410,...,38.008576,44.072460,54.378485,53.295324,39.882059,47.226226,87.516530,93.006715,98.779759,98.715243
24,5,20250328_AS_MRC5_Confluence_Rep5,52,18.024817,15.523888,15.301975,18.133390,7.383957,6.823986,98.129544,...,39.943195,45.091978,57.438487,56.170891,42.279545,50.086984,89.883599,95.121297,99.309663,99.185634
25,5,20250328_AS_MRC5_Confluence_Rep5,54,18.359151,15.381542,14.928873,18.456629,7.811305,7.209473,98.501920,...,41.033450,47.435624,60.162520,58.734835,44.610849,53.047250,92.224576,96.448090,99.604173,99.449135
26,5,20250328_AS_MRC5_Confluence_Rep5,56,18.262689,15.740122,15.129130,18.211147,7.975631,7.410214,98.812967,...,42.038438,48.348440,62.932646,61.692907,47.109051,55.837879,93.719325,97.534469,99.779371,99.658404
27,5,20250328_AS_MRC5_Confluence_Rep5,58,18.771220,15.644965,14.764813,18.359734,7.952164,7.774162,99.240442,...,43.808628,49.760185,65.457127,64.559965,50.017464,58.797548,95.069844,98.120419,99.807611,99.710577
28,5,20250328_AS_MRC5_Confluence_Rep5,60,18.217479,15.040605,14.876937,18.186222,8.350992,7.716593,99.409074,...,45.394132,51.535463,67.518250,67.961772,52.660274,62.161281,96.389625,98.728630,99.872515,99.772005
29,5,20250328_AS_MRC5_Confluence_Rep5,62,18.644941,15.832903,15.381370,18.311621,8.052679,8.019072,99.448690,...,47.084831,52.722270,70.983185,70.286291,54.951638,65.138865,97.076206,99.137179,99.922962,99.849673
30,5,20250328_AS_MRC5_Confluence_Rep5,64,18.469820,15.232916,15.799774,18.335601,8.228650,8.201298,99.454491,...,48.692684,54.415252,73.202380,72.308630,57.813643,68.726934,97.613407,99.237455,99.951281,99.865070
31,5,20250328_AS_MRC5_Confluence_Rep5,66,18.902610,15.464642,15.883915,18.794414,8.411259,8.420563,99.588134,...,49.883476,56.103370,76.884192,75.303764,60.572803,71.901888,98.345285,99.534896,99.969016,99.928136
32,5,20250328_AS_MRC5_Confluence_Rep5,68,18.582021,15.785227,16.105897,19.261891,8.576975,8.481641,99.652351,...,51.157455,57.589791,78.795595,78.224940,62.308849,74.087391,98.625216,99.564929,99.965227,99.935385
33,5,20250328_AS_MRC5_Confluence_Rep5,70,19.103782,15.799329,16.240335,19.454789,8.479063,8.791520,99.687271,...,53.016446,59.014076,81.128055,80.855828,65.447665,77.024681,98.860377,99.656987,99.974491,99.960107
34,5,20250328_AS_MRC5_Confluence_Rep5,72,19.811192,15.884584,16.654222,19.635179,8.941607,9.099360,99.704005,...,54.329262,60.464429,83.631700,83.089954,67.935900,79.745823,99.191112,99.782737,99.972330,99.951577

,Plate_Number,Vessel_Name,Elapsed,Doxo_P17 LIN13-0C-b2-s3,P33 LIN3-0A-b2-s1-ss1,P32 LIN3-0A-b2-s1-ss1-sss1,P29 LIN3-0A-b2-s1-ss2,P27 LIN3-0A-b2-s2-ss1-sss1,P23 LIN7-0C-b3-s1,P19 LIN8-0B-b2B-s1-ss1,P19 LIN8-0B-b2B-s1-ss2,P15 LIN6-0C-b1-s2,P11 LIN11-0C-b5
0,5,20250328_AS_MRC5_Confluence_Rep5,4,16.362009,16.284700,3.806272,52.372839,30.993926,17.925355,12.955633,10.053678,23.055115,28.532845
1,5,20250328_AS_MRC5_Confluence_Rep5,6,16.346891,16.114841,4.175769,54.852666,32.826636,18.565648,13.963120,11.051939,24.399849,30.112865
2,5,20250328_AS_MRC5_Confluence_Rep5,8,16.042880,15.996504,4.163617,56.465019,34.763528,18.829541,15.134742,12.143908,26.653963,32.810712
3,5,20250328_AS_MRC5_Confluence_Rep5,10,16.245432,16.109549,4.280088,58.109648,35.688333,19.376706,16.398489,13.037877,27.829515,35.505901
4,5,20250328_AS_MRC5_Confluence_Rep5,12,15.945860,16.047643,4.363164,59.721334,37.803474,19.920094,17.459571,14.000914,29.685013,38.305468
5,5,20250328_AS_MRC5_Confluence_Rep5,14,15.706206,15.499971,4.586472,61.393689,39.651573,20.503794,19.106137,14.691801,31.741146,40.339366
6,5,20250328_AS_MRC5_Confluence_Rep5,16,15.985905,15.552985,4.410153,63.197999,41.845599,21.195424,20.136223,15.441291,33.500694,42.279774
7,5,20250328_AS_MRC5_Confluence_Rep5,18,15.727342,15.490449,4.648701,64.896844,43.862630,22.199846,21.211334,16.730452,35.433761,44.815438
8,5,20250328_AS_MRC5_Confluence_Rep5,20,15.980044,15.302018,4.609289,66.663187,45.731426,23.134218,22.475594,17.745928,37.490811,48.201154
9,5,20250328_AS_MRC5_Confluence_Rep5,22,15.612339,15.439423,4.674909,67.964421,47.846856,23.701419,23.962546,19.500316,39.806611,52.069649
10,5,20250328_AS_MRC5_Confluence_Rep5,24,15.967705,15.343503,4.975325,70.302996,50.456257,24.372061,25.691638,20.445436,42.806014,56.649307
11,5,20250328_AS_MRC5_Confluence_Rep5,26,15.916469,15.157538,5.117883,72.981914,53.734732,25.472910,27.246348,21.784240,45.986441,60.880364
12,5,20250328_AS_MRC5_Confluence_Rep5,28,16.222363,15.521625,5.347699,76.240196,56.790774,26.828277,28.898401,22.801715,49.424367,65.449218
13,5,20250328_AS_MRC5_Confluence_Rep5,30,16.156298,15.165913,5.549504,78.726002,59.869353,27.903990,30.530029,23.793969,53.212521,70.059586
14,5,20250328_AS_MRC5_Confluence_Rep5,32,15.810270,15.709609,5.733600,81.612404,63.401503,28.904708,32.963503,25.123615,56.693284,74.413182
15,5,20250328_AS_MRC5_Confluence_Rep5,34,16.238962,15.150253,5.964697,84.525436,66.744440,30.237361,34.589442,27.004578,60.830013,79.163903
16,5,20250328_AS_MRC5_Confluence_Rep5,36,16.101821,15.324172,6.061384,86.517880,70.235559,31.815680,36.835081,28.752159,64.695783,83.684911
17,5,20250328_AS_MRC5_Confluence_Rep5,38,16.042501,15.411124,6.225304,88.509433,73.900359,32.748384,38.677063,30.500987,68.995011,87.893102
18,5,20250328_AS_MRC5_Confluence_Rep5,40,16.163039,16.269828,6.274495,91.023355,77.153558,34.007751,40.747266,32.663602,73.370679,91.364366
19,5,20250328_AS_MRC5_Confluence_Rep5,42,16.328654,16.050516,6.455748,92.951236,80.424216,35.175183,43.227228,34.321161,77.352838,94.130639
20,5,20250328_AS_MRC5_Confluence_Rep5,44,16.375987,16.257123,6.610909,94.104054,83.165652,36.848914,45.341058,36.683016,81.317552,96.085449
21,5,20250328_AS_MRC5_Confluence_Rep5,46,16.447944,16.460610,6.833790,95.426588,86.377546,38.105449,48.323059,38.832671,84.905571,97.311392
22,5,20250328_AS_MRC5_Confluence_Rep5,48,16.347553,16.245124,7.125833,96.344989,89.054432,39.468348,50.869841,40.864321,87.515709,98.284191
23,5,20250328_AS_MRC5_Confluence_Rep5,50,16.496952,16.719965,7.036730,97.089779,91.260229,41.040518,53.836904,43.554142,90.261623,98.747501
24,5,20250328_AS_MRC5_Confluence_Rep5,52,16.774352,16.717682,7.103971,97.767029,93.132314,42.517586,56.804689,46.183264,92.502448,99.247648
25,5,20250328_AS_MRC5_Confluence_Rep5,54,16.870346,16.692751,7.510389,98.240621,94.573729,44.234537,59.448678,48.829049,94.336333,99.526654
26,5,20250328_AS_MRC5_Confluence_Rep5,56,17.001406,16.670139,7.692922,98.523237,95.669265,45.193439,62.312777,51.473465,95.626897,99.718887
27,5,20250328_AS_MRC5_Confluence_Rep5,58,17.208092,16.562274,7.863163,98.925524,96.495360,46.784406,65.008546,54.407506,96.595131,99.759094
28,5,20250328_AS_MRC5_Confluence_Rep5,60,16.629042,16.531580,8.033793,99.164963,97.260284,48.464798,67.740011,57.410777,97.559128,99.822260
29,5,20250328_AS_MRC5_Confluence_Rep5,62,17.238922,16.846496,8.035875,99.198837,97.896483,49.903551,70.634738,60.045251,98.106692,99.886318
30,5,20250328_AS_MRC5_Confluence_Rep5,64,16.851368,17.067688,8.214974,99.323960,98.245162,51.553968,72.755505,63.270288,98.425431,99.908176
31,5,20250328_AS_MRC5_Confluence_Rep5,66,17.183626,17.339164,8.415911,99.384894,98.529475,52.993423,76.093978,66.237345,98.940091,99.948576
32,5,20250328_AS_MRC5_Confluence_Rep5,68,17.183624,17.683894,8.529308,99.462355,98.839758,54.373623,78.510267,68.198120,99.095073,99.950306
33,5,20250328_AS_MRC5_Confluence_Rep5,70,17.451556,17.847562,8.635292,99.566192,98.908228,56.015261,80.991941,71.236173,99.258682,99.967299
34,5,20250328_AS_MRC5_Confluence_Rep5,72,17.847888,18.144701,9.020484,99.561191,99.159460,57.396846,83.360827,73.840861,99.486925,99.961954

Wrote replaced data to: /Users/allielas/HTP_fibroblasts_mitolyso/proliferation_growth_curves/Incucyte_sheets/r5_processed.xlsx

/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Plate_Number,Vessel Name,Elapsed,"Doxo_P12 LIN11-0C-b5 (A1), Image 1","Doxo_P12 LIN11-0C-b5 (A1), Image 2","Doxo_P12 LIN11-0C-b5 (A1), Image 3","Doxo_P12 LIN11-0C-b5 (A1), Image 4","Doxo_P12 LIN11-0C-b5 (A1), Image 5","Doxo_P12 LIN11-0C-b5 (A1), Image 6","Doxo_P12 LIN11-0C-b5 (A1), Image 7",...,"P13 LIN12-0C-b2-s2 (B3), Image 9","P13 LIN12-0C-b2-s2 (B4), Image 1","P13 LIN12-0C-b2-s2 (B4), Image 2","P13 LIN12-0C-b2-s2 (B4), Image 3","P13 LIN12-0C-b2-s2 (B4), Image 4","P13 LIN12-0C-b2-s2 (B4), Image 5","P13 LIN12-0C-b2-s2 (B4), Image 6","P13 LIN12-0C-b2-s2 (B4), Image 7","P13 LIN12-0C-b2-s2 (B4), Image 8","P13 LIN12-0C-b2-s2 (B4), Image 9"
0,6,20250410_AS_MRC5_Confluence_Rep6,0,10.62828,16.18219,18.33937,14.82026,24.99242,11.78561,17.52048,...,14.96961,12.72686,13.30706,13.00303,12.68807,21.04950,17.06103,13.74891,14.57004,11.01446
1,6,20250410_AS_MRC5_Confluence_Rep6,2,10.93968,16.39082,19.32132,17.81059,31.31132,13.69407,18.87757,...,17.86263,13.41947,14.33402,15.14163,13.34517,23.10765,19.13441,15.30417,14.96422,13.48018
2,6,20250410_AS_MRC5_Confluence_Rep6,4,12.21673,16.80493,17.67708,16.66678,32.88304,12.52527,18.99748,...,18.71694,13.07849,15.09902,15.25561,15.25493,27.98719,21.03038,16.13548,15.01919,12.77979
3,6,20250410_AS_MRC5_Confluence_Rep6,6,12.82957,17.77234,16.87589,16.65217,31.45220,13.83598,18.39427,...,20.82380,14.80544,15.61961,15.11678,16.07394,27.28509,24.24805,17.36198,16.97621,13.61123
4,6,20250410_AS_MRC5_Confluence_Rep6,8,12.54357,16.72018,19.64980,17.77835,32.47268,14.69788,17.98535,...,22.35030,17.42311,16.69867,15.58539,18.05979,32.03050,24.69228,19.01913,19.55932,16.50636
5,6,20250410_AS_MRC5_Confluence_Rep6,10,12.74633,17.57655,17.79051,18.36149,40.04501,14.80209,17.25784,...,25.32643,20.24414,19.07350,18.50265,20.53581,35.50924,28.87832,21.25943,20.85412,17.59554
6,6,20250410_AS_MRC5_Confluence_Rep6,12,12.21543,16.86523,19.82429,17.98541,36.12407,16.56202,15.45250,...,26.55444,21.88579,22.14093,18.95282,21.42469,37.58494,29.32227,23.05371,22.15042,19.33443
7,6,20250410_AS_MRC5_Confluence_Rep6,14,11.45460,17.11347,18.47881,17.86604,36.45303,14.56861,14.84477,...,28.67016,22.27983,24.36735,19.62590,22.21959,41.35270,32.26863,25.38946,22.92327,19.93758
8,6,20250410_AS_MRC5_Confluence_Rep6,16,11.44115,19.19853,17.01787,16.45180,38.66757,15.31988,14.51711,...,29.15325,24.94325,23.37317,19.49205,22.45131,45.08113,30.76978,25.41644,23.91574,21.15610
9,6,20250410_AS_MRC5_Confluence_Rep6,18,12.31179,17.00298,16.83798,17.23687,44.77750,11.27049,15.57665,...,30.62104,25.47489,25.85282,19.62816,24.43954,44.75729,33.95597,28.22640,26.39874,22.66581
10,6,20250410_AS_MRC5_Confluence_Rep6,20,12.60892,16.01296,18.72330,15.65608,53.79910,11.73890,16.60129,...,32.94970,29.39726,28.07808,22.68711,27.08001,50.05476,37.38432,31.20629,29.54225,24.28991
11,6,20250410_AS_MRC5_Confluence_Rep6,22,11.31474,16.03878,20.72942,15.65068,44.43816,13.08307,17.27177,...,37.04354,30.94536,30.15331,23.18114,30.41153,53.73969,39.27987,32.49398,32.50683,26.38153
12,6,20250410_AS_MRC5_Confluence_Rep6,24,11.16361,16.99465,18.40137,16.13479,40.35245,13.35364,16.89351,...,39.68108,32.31862,32.91801,27.60544,31.52105,55.14217,43.12104,36.02546,33.13531,27.13976
13,6,20250410_AS_MRC5_Confluence_Rep6,26,10.75025,16.10522,20.09513,17.03459,38.44099,11.75126,15.28873,...,41.99389,34.66857,33.90256,30.00702,33.39919,59.76911,47.07393,38.94722,34.46159,28.83550
14,6,20250410_AS_MRC5_Confluence_Rep6,28,10.53451,16.89309,19.72226,15.71822,37.55121,12.21727,14.99406,...,43.35207,38.81945,35.77510,30.87433,36.28578,62.65140,48.75586,42.60885,38.83065,29.10669
15,6,20250410_AS_MRC5_Confluence_Rep6,30,10.30792,18.36736,19.83706,15.30348,41.77639,12.49815,16.81306,...,47.92273,41.10748,40.47585,33.38355,37.93884,67.92204,53.59647,46.22985,45.23997,34.37411
16,6,20250410_AS_MRC5_Confluence_Rep6,32,11.90901,17.01588,18.49794,16.23102,43.70800,13.05289,16.46320,...,50.30552,45.47476,43.05104,35.62015,40.67971,69.65855,57.97456,49.31442,47.81263,37.57116
17,6,20250410_AS_MRC5_Confluence_Rep6,34,12.42331,17.37120,19.47545,15.89523,45.52290,14.11693,16.71185,...,54.29797,49.33887,43.78408,39.83119,45.30191,73.57858,63.73517,53.21746,50.39861,40.67342
18,6,20250410_AS_MRC5_Confluence_Rep6,36,14.32706,17.22779,19.63191,17.81591,44.56506,10.36952,15.88464,...,57.68719,52.61425,48.22266,44.02132,50.03435,78.05295,69.02992,56.39983,53.41694,45.54558
19,6,20250410_AS_MRC5_Confluence_Rep6,38,14.29762,15.68571,20.41269,16.49455,47.56016,15.35163,16.12510,...,61.93830,56.82077,50.72211,48.68759,55.56046,81.21825,73.02768,61.62375,55.97321,48.70417
20,6,20250410_AS_MRC5_Confluence_Rep6,40,15.03708,17.02032,22.93973,17.15533,46.57444,15.49080,16.69751,...,67.72058,59.26341,55.96591,52.94368,59.37076,84.67699,77.48995,67.17240,58.78032,50.59980
21,6,20250410_AS_MRC5_Confluence_Rep6,42,15.07792,17.74045,22.48190,16.57650,43.93431,12.84064,17.52895,...,72.67216,65.47770,60.33592,57.94239,61.42366,88.74515,81.72523,73.06162,64.01887,55.20959
22,6,20250410_AS_MRC5_Confluence_Rep6,44,15.54257,18.20947,23.16303,16.33215,50.96816,13.03984,17.49365,...,77.71668,72.87860,66.75576,58.79384,69.02938,91.81402,85.55950,78.28800,69.51963,58.14576
23,6,20250410_AS_MRC5_Confluence_Rep6,46,16.36978,18.78319,21.43445,17.27819,53.80968,13.50593,16.83614,...,82.31295,78.31805,70.82428,65.34207,76.07442,93.90707,89.79553,84.13618,74.18324,62.73909
24,6,20250410_AS_MRC5_Confluence_Rep6,48,16.05926,18.43579,20.61838,17.02975,48.86950,10.67615,17.94349,...,87.43764,82.71538,76.42162,71.37675,78.86616,95.58580,93.60488,88.91300,79.23930,68.16809
25,6,20250410_AS_MRC5_Confluence_Rep6,50,16.08153,20.07286,22.53176,17.70111,48.59292,12.17323,18.94435,...,90.73720,87.94601,79.89523,75.93687,83.66333,97.76340,95.90745,91.52542,86.61952,73.49821
26,6,20250410_AS_MRC5_Confluence_Rep6,52,16.03850,21.59842,23.81911,18.88863,46.09443,15.01427,19.52743,...,93.58807,90.75871,84.16794,80.49961,88.49766,98.71906,97.95010,95.64603,90.07484,78.90741
27,6,20250410_AS_MRC5_Confluence_Rep6,54,17.13669,21.24085,22.80840,18.72378,51.88319,16.29972,20.10264,...,96.82309,94.54688,89.18269,84.71822,92.33945,99.43769,98.99468,98.06689,94.01489,83.76413
28,6,20250410_AS_MRC5_Confluence_Rep6,56,17.13560,22.50867,22.07072,19.31470,47.13444,14.23172,22.49099,...,97.87260,96.81844,92.10439,89.14534,95.57732,99.77784,99.48200,99.19170,95.79900,89.16015
29,6,20250410_AS_MRC5_Confluence_Rep6,58,17.75015,23.89396,22.77849,19.97091,49.80790,16.66999,21.47167,...,99.17298,98.03049,95.97117,92.38432,97.56221,99.93205,99.74616,99.59161,97.77528,92.13744
30,6,20250410_AS_MRC5_Confluence_Rep6,60,18.25359,24.77034,25.00198,19.07807,51.23920,17.84978,21.26161,...,99.80605,98.82463,97.23085,94.85912,98.51868,99.98934,99.95355,99.65177,98.47075,94.16364
31,6,20250410_AS_MRC5_Confluence_Rep6,62,19.71263,24.22694,23.74795,19.93075,49.88248,16.14544,22.82042,...,99.89797,99.21976,97.66437,97.32886,99.31360,99.99016,99.95861,99.83768,99.43236,96.31181
32,6,20250410_AS_MRC5_Confluence_Rep6,64,19.32829,25.71712,24.64591,20.85261,50.41713,17.46312,22.39552,...,99.92535,99.48624,98.26472,98.36476,99.66919,99.99200,100.00000,99.93498,99.38995,97.82697
33,6,20250410_AS_MRC5_Confluence_Rep6,66,19.58212,26.12947,29.96320,22.06054,56.85512,15.12224,22.87185,...,99.95335,99.78201,99.21546,98.85551,99.89632,99.99891,99.98170,99.96612,99.81069,98.68675
34,6,20250410_AS_MRC5_Confluence_Rep6,68,19.97541,26.88449,28.44965,21.87124,56.19448,15.55671,21.84454,...,99.97678,99.91040,99.33020,99.21227,99.96455,99.98040,99.99213,99.97562,99.89182,99.58773
35,6,20250410_AS_MRC5_Confluence_Rep6,70,20.91168,26.73903,27.20246,20.18008,57.05373,18.07337,22.98282,...,99.99364,99.90391,99.66981,99.52995,99.98900,99.99891,99.99570,99.99835,99.90438,99.69727
36,6,20250410_AS_MRC5_Confluence_Rep6,72,21.37511,27.53100,28.99482,20.84258,61.81592,17.52062,24.56908,...,99.94482,99.90780,99.73264,99.79198,99.99515,100.00000,99.98450,99.96973,99.91772,99.90514

,Plate_Number,Vessel Name,Elapsed,"Doxo_P12 LIN11-0C-b5 (A1), Image 1","Doxo_P12 LIN11-0C-b5 (A1), Image 2","Doxo_P12 LIN11-0C-b5 (A1), Image 3","Doxo_P12 LIN11-0C-b5 (A1), Image 4","Doxo_P12 LIN11-0C-b5 (A1), Image 6","Doxo_P12 LIN11-0C-b5 (A1), Image 7","Doxo_P12 LIN11-0C-b5 (A1), Image 8",...,"P13 LIN12-0C-b2-s2 (B3), Image 8","P13 LIN12-0C-b2-s2 (B3), Image 9","P13 LIN12-0C-b2-s2 (B4), Image 1","P13 LIN12-0C-b2-s2 (B4), Image 2","P13 LIN12-0C-b2-s2 (B4), Image 3","P13 LIN12-0C-b2-s2 (B4), Image 4","P13 LIN12-0C-b2-s2 (B4), Image 6","P13 LIN12-0C-b2-s2 (B4), Image 7","P13 LIN12-0C-b2-s2 (B4), Image 8","P13 LIN12-0C-b2-s2 (B4), Image 9"
0,6,20250410_AS_MRC5_Confluence_Rep6,4,12.21673,16.80493,17.67708,16.66678,12.52527,18.99748,11.65462,...,14.70088,18.71694,13.07849,15.09902,15.25561,15.25493,21.03038,16.13548,15.01919,12.77979
1,6,20250410_AS_MRC5_Confluence_Rep6,6,12.82957,17.77234,16.87589,16.65217,13.83598,18.39427,11.59050,...,16.70331,20.82380,14.80544,15.61961,15.11678,16.07394,24.24805,17.36198,16.97621,13.61123
2,6,20250410_AS_MRC5_Confluence_Rep6,8,12.54357,16.72018,19.64980,17.77835,14.69788,17.98535,11.46464,...,17.70637,22.35030,17.42311,16.69867,15.58539,18.05979,24.69228,19.01913,19.55932,16.50636
3,6,20250410_AS_MRC5_Confluence_Rep6,10,12.74633,17.57655,17.79051,18.36149,14.80209,17.25784,12.16114,...,20.38339,25.32643,20.24414,19.07350,18.50265,20.53581,28.87832,21.25943,20.85412,17.59554
4,6,20250410_AS_MRC5_Confluence_Rep6,12,12.21543,16.86523,19.82429,17.98541,16.56202,15.45250,12.01855,...,22.21591,26.55444,21.88579,22.14093,18.95282,21.42469,29.32227,23.05371,22.15042,19.33443
5,6,20250410_AS_MRC5_Confluence_Rep6,14,11.45460,17.11347,18.47881,17.86604,14.56861,14.84477,12.83415,...,22.82233,28.67016,22.27983,24.36735,19.62590,22.21959,32.26863,25.38946,22.92327,19.93758
6,6,20250410_AS_MRC5_Confluence_Rep6,16,11.44115,19.19853,17.01787,16.45180,15.31988,14.51711,12.63200,...,24.09692,29.15325,24.94325,23.37317,19.49205,22.45131,30.76978,25.41644,23.91574,21.15610
7,6,20250410_AS_MRC5_Confluence_Rep6,18,12.31179,17.00298,16.83798,17.23687,11.27049,15.57665,13.49186,...,27.66997,30.62104,25.47489,25.85282,19.62816,24.43954,33.95597,28.22640,26.39874,22.66581
8,6,20250410_AS_MRC5_Confluence_Rep6,20,12.60892,16.01296,18.72330,15.65608,11.73890,16.60129,14.27823,...,29.49990,32.94970,29.39726,28.07808,22.68711,27.08001,37.38432,31.20629,29.54225,24.28991
9,6,20250410_AS_MRC5_Confluence_Rep6,22,11.31474,16.03878,20.72942,15.65068,13.08307,17.27177,13.20968,...,31.38460,37.04354,30.94536,30.15331,23.18114,30.41153,39.27987,32.49398,32.50683,26.38153
10,6,20250410_AS_MRC5_Confluence_Rep6,24,11.16361,16.99465,18.40137,16.13479,13.35364,16.89351,16.61337,...,33.10089,39.68108,32.31862,32.91801,27.60544,31.52105,43.12104,36.02546,33.13531,27.13976
11,6,20250410_AS_MRC5_Confluence_Rep6,26,10.75025,16.10522,20.09513,17.03459,11.75126,15.28873,14.89688,...,35.14471,41.99389,34.66857,33.90256,30.00702,33.39919,47.07393,38.94722,34.46159,28.83550
12,6,20250410_AS_MRC5_Confluence_Rep6,28,10.53451,16.89309,19.72226,15.71822,12.21727,14.99406,14.87073,...,39.43831,43.35207,38.81945,35.77510,30.87433,36.28578,48.75586,42.60885,38.83065,29.10669
13,6,20250410_AS_MRC5_Confluence_Rep6,30,10.30792,18.36736,19.83706,15.30348,12.49815,16.81306,16.41007,...,42.25306,47.92273,41.10748,40.47585,33.38355,37.93884,53.59647,46.22985,45.23997,34.37411
14,6,20250410_AS_MRC5_Confluence_Rep6,32,11.90901,17.01588,18.49794,16.23102,13.05289,16.46320,17.26795,...,45.80679,50.30552,45.47476,43.05104,35.62015,40.67971,57.97456,49.31442,47.81263,37.57116
15,6,20250410_AS_MRC5_Confluence_Rep6,34,12.42331,17.37120,19.47545,15.89523,14.11693,16.71185,17.81544,...,50.44272,54.29797,49.33887,43.78408,39.83119,45.30191,63.73517,53.21746,50.39861,40.67342
16,6,20250410_AS_MRC5_Confluence_Rep6,36,14.32706,17.22779,19.63191,17.81591,10.36952,15.88464,16.40714,...,54.07281,57.68719,52.61425,48.22266,44.02132,50.03435,69.02992,56.39983,53.41694,45.54558
17,6,20250410_AS_MRC5_Confluence_Rep6,38,14.29762,15.68571,20.41269,16.49455,15.35163,16.12510,18.08410,...,55.74540,61.93830,56.82077,50.72211,48.68759,55.56046,73.02768,61.62375,55.97321,48.70417
18,6,20250410_AS_MRC5_Confluence_Rep6,40,15.03708,17.02032,22.93973,17.15533,15.49080,16.69751,18.17594,...,61.15098,67.72058,59.26341,55.96591,52.94368,59.37076,77.48995,67.17240,58.78032,50.59980
19,6,20250410_AS_MRC5_Confluence_Rep6,42,15.07792,17.74045,22.48190,16.57650,12.84064,17.52895,18.78906,...,63.95760,72.67216,65.47770,60.33592,57.94239,61.42366,81.72523,73.06162,64.01887,55.20959
20,6,20250410_AS_MRC5_Confluence_Rep6,44,15.54257,18.20947,23.16303,16.33215,13.03984,17.49365,19.66319,...,68.38055,77.71668,72.87860,66.75576,58.79384,69.02938,85.55950,78.28800,69.51963,58.14576
21,6,20250410_AS_MRC5_Confluence_Rep6,46,16.36978,18.78319,21.43445,17.27819,13.50593,16.83614,21.06964,...,72.36109,82.31295,78.31805,70.82428,65.34207,76.07442,89.79553,84.13618,74.18324,62.73909
22,6,20250410_AS_MRC5_Confluence_Rep6,48,16.05926,18.43579,20.61838,17.02975,10.67615,17.94349,21.30989,...,78.57182,87.43764,82.71538,76.42162,71.37675,78.86616,93.60488,88.91300,79.23930,68.16809
23,6,20250410_AS_MRC5_Confluence_Rep6,50,16.08153,20.07286,22.53176,17.70111,12.17323,18.94435,22.12263,...,82.91233,90.73720,87.94601,79.89523,75.93687,83.66333,95.90745,91.52542,86.61952,73.49821
24,6,20250410_AS_MRC5_Confluence_Rep6,52,16.03850,21.59842,23.81911,18.88863,15.01427,19.52743,22.99545,...,87.38814,93.58807,90.75871,84.16794,80.49961,88.49766,97.95010,95.64603,90.07484,78.90741
25,6,20250410_AS_MRC5_Confluence_Rep6,54,17.13669,21.24085,22.80840,18.72378,16.29972,20.10264,24.84573,...,91.32156,96.82309,94.54688,89.18269,84.71822,92.33945,98.99468,98.06689,94.01489,83.76413
26,6,20250410_AS_MRC5_Confluence_Rep6,56,17.13560,22.50867,22.07072,19.31470,14.23172,22.49099,24.80578,...,94.09589,97.87260,96.81844,92.10439,89.14534,95.57732,99.48200,99.19170,95.79900,89.16015
27,6,20250410_AS_MRC5_Confluence_Rep6,58,17.75015,23.89396,22.77849,19.97091,16.66999,21.47167,26.23218,...,96.10296,99.17298,98.03049,95.97117,92.38432,97.56221,99.74616,99.59161,97.77528,92.13744
28,6,20250410_AS_MRC5_Confluence_Rep6,60,18.25359,24.77034,25.00198,19.07807,17.84978,21.26161,27.24882,...,97.96574,99.80605,98.82463,97.23085,94.85912,98.51868,99.95355,99.65177,98.47075,94.16364
29,6,20250410_AS_MRC5_Confluence_Rep6,62,19.71263,24.22694,23.74795,19.93075,16.14544,22.82042,28.40028,...,98.83707,99.89797,99.21976,97.66437,97.32886,99.31360,99.95861,99.83768,99.43236,96.31181
30,6,20250410_AS_MRC5_Confluence_Rep6,64,19.32829,25.71712,24.64591,20.85261,17.46312,22.39552,27.96814,...,99.62159,99.92535,99.48624,98.26472,98.36476,99.66919,100.00000,99.93498,99.38995,97.82697
31,6,20250410_AS_MRC5_Confluence_Rep6,66,19.58212,26.12947,29.96320,22.06054,15.12224,22.87185,29.02623,...,99.81711,99.95335,99.78201,99.21546,98.85551,99.89632,99.98170,99.96612,99.81069,98.68675
32,6,20250410_AS_MRC5_Confluence_Rep6,68,19.97541,26.88449,28.44965,21.87124,15.55671,21.84454,31.92062,...,99.94529,99.97678,99.91040,99.33020,99.21227,99.96455,99.99213,99.97562,99.89182,99.58773
33,6,20250410_AS_MRC5_Confluence_Rep6,70,20.91168,26.73903,27.20246,20.18008,18.07337,22.98282,33.80538,...,99.97862,99.99364,99.90391,99.66981,99.52995,99.98900,99.99570,99.99835,99.90438,99.69727
34,6,20250410_AS_MRC5_Confluence_Rep6,72,21.37511,27.53100,28.99482,20.84258,17.52062,24.56908,33.53106,...,99.95704,99.94482,99.90780,99.73264,99.79198,99.99515,99.98450,99.96973,99.91772,99.90514

,Plate_Number,Vessel Name,Elapsed,Doxo_P12 LIN11-0C-b5 (A1),Doxo_P12 LIN11-0C-b5 (A2),P34 LIN3-0A-b2-s1-ss1 (A3),P34 LIN3-0A-b2-s1-ss1 (A4),P31 LIN3-0A-b2-s1-ss2 (B1),P31 LIN3-0A-b2-s1-ss2 (B2),P29 LIN3-0A-b2-s2-ss1-ss1 (B3),...,P22 LIN8-0B-b2B-s1-ss1 (C3),P22 LIN8-0B-b2B-s1-ss1 (C4),P22 LIN8-0B-b2B-s1-ss2 (A1),P22 LIN8-0B-b2B-s1-ss2 (A2),P18 LIN6-0C-b1-s2 (A3),P18 LIN6-0C-b1-s2 (A4),P14 LIN11-0C-b5 (B1),P14 LIN11-0C-b5 (B2),P13 LIN12-0C-b2-s2 (B3),P13 LIN12-0C-b2-s2 (B4)
0,6,20250410_AS_MRC5_Confluence_Rep6,4,15.817085,14.348299,3.406888,3.653743,17.274314,15.132450,16.750299,...,13.052594,15.390854,16.009921,16.332513,13.923842,12.755273,13.066952,12.389684,17.411203,15.456611
1,6,20250410_AS_MRC5_Confluence_Rep6,6,15.914529,13.969496,3.744400,3.528267,17.920894,16.006552,17.564056,...,13.213172,15.971398,16.501149,16.161000,14.740775,13.067806,14.081154,13.012250,18.669087,16.726655
2,6,20250410_AS_MRC5_Confluence_Rep6,8,16.154989,14.436384,3.066304,3.346391,17.736721,15.641796,17.793454,...,13.748299,16.324797,16.235523,16.378240,14.272538,13.433853,15.456739,14.737861,19.950334,18.443006
3,6,20250410_AS_MRC5_Confluence_Rep6,10,16.182323,14.613454,4.122613,3.146213,17.712769,15.694571,18.639855,...,14.809229,17.065993,16.256760,16.968254,15.828793,14.662751,16.548578,15.657361,22.158696,20.867939
4,6,20250410_AS_MRC5_Confluence_Rep6,12,16.302601,13.953830,3.133886,3.305894,18.334788,16.040320,19.311890,...,15.704814,17.909097,17.211639,17.235408,16.715266,15.426595,17.956578,16.491214,23.440659,22.283133
5,6,20250410_AS_MRC5_Confluence_Rep6,14,15.744534,14.712637,3.579400,3.348662,18.872444,15.956006,20.121924,...,16.434992,18.827451,17.940053,17.839270,18.157062,16.516537,19.482042,17.519172,25.056141,23.626451
6,6,20250410_AS_MRC5_Confluence_Rep6,16,15.544715,15.131306,3.279594,2.775196,18.879555,16.220584,20.391470,...,16.694481,19.534128,17.514341,18.335687,18.940199,17.415934,19.319437,18.180476,25.959559,23.939730
7,6,20250410_AS_MRC5_Confluence_Rep6,18,15.294104,14.814262,3.154126,3.070572,19.777958,16.213395,20.841859,...,17.176171,20.564365,19.483455,19.358600,20.212264,17.775913,20.691720,19.569730,28.109420,25.830291
8,6,20250410_AS_MRC5_Confluence_Rep6,20,15.388398,14.255447,3.310760,2.978900,20.285516,16.102566,21.547286,...,18.478209,21.829756,19.685015,20.082876,20.841098,18.394979,22.501760,20.868685,30.118708,28.708154
9,6,20250410_AS_MRC5_Confluence_Rep6,22,15.789130,14.359190,3.277460,3.052834,20.362420,16.843072,22.760356,...,18.874046,23.163274,20.303435,21.555039,21.837354,18.802328,23.849857,22.189575,32.382544,30.669194
10,6,20250410_AS_MRC5_Confluence_Rep6,24,15.884181,14.030590,3.288173,2.811604,21.015017,17.040163,23.919161,...,19.727366,23.717560,21.782492,21.991640,23.358674,20.479385,25.116767,24.414734,34.625663,32.973086
11,6,20250410_AS_MRC5_Confluence_Rep6,26,15.498166,14.476180,3.046772,2.781257,21.643630,17.373304,24.927890,...,21.120254,24.901608,22.807076,23.065365,25.292909,22.360546,27.724614,25.695672,36.893771,35.161948
12,6,20250410_AS_MRC5_Confluence_Rep6,28,15.450780,14.786958,2.868891,3.370523,22.196856,18.018472,26.203535,...,21.842358,26.653016,24.058512,24.686714,27.394061,23.298118,30.032148,27.786055,39.089416,37.632089
13,6,20250410_AS_MRC5_Confluence_Rep6,30,16.139536,15.302281,3.532467,3.366844,23.497636,19.003240,27.343772,...,23.722058,28.802513,25.557124,26.260295,29.113357,24.812574,32.246520,29.739784,43.204056,41.543265
14,6,20250410_AS_MRC5_Confluence_Rep6,32,16.522285,15.125244,2.899119,2.958037,24.306613,19.474874,28.975289,...,25.345349,29.706734,27.186916,27.619405,31.396331,25.973711,34.507239,32.487526,46.465220,44.687304
15,6,20250410_AS_MRC5_Confluence_Rep6,34,17.187884,15.218035,3.394596,3.516555,25.420449,19.901804,30.863064,...,26.551555,31.374670,28.085577,28.919665,32.245770,28.352272,36.924135,34.802790,50.418654,48.285089
16,6,20250410_AS_MRC5_Confluence_Rep6,36,17.085403,15.150512,3.029836,2.788820,26.422585,20.428194,31.837907,...,27.558870,33.211599,29.744256,30.112509,35.175720,29.622768,39.751685,37.143482,54.603167,52.410606
17,6,20250410_AS_MRC5_Confluence_Rep6,38,17.706889,15.774641,3.054985,3.039619,27.479502,21.392540,33.856460,...,29.523473,34.410536,31.240420,31.694452,37.560566,31.617591,41.830901,40.105439,58.455517,56.389967
18,6,20250410_AS_MRC5_Confluence_Rep6,40,18.604066,16.278245,3.092920,2.959010,28.598734,21.930391,35.535495,...,31.146616,36.330745,32.410153,33.158069,39.337499,34.201606,45.279045,42.783363,62.991139,60.198279
19,6,20250410_AS_MRC5_Confluence_Rep6,42,18.519772,16.528779,2.987240,2.671137,29.288908,23.293302,36.870437,...,32.902625,38.543111,33.847295,34.143430,41.953971,36.357425,48.785014,45.606198,66.929844,64.899372
20,6,20250410_AS_MRC5_Confluence_Rep6,44,18.903874,16.683442,3.233745,2.716013,30.469481,23.729451,38.994836,...,35.183840,41.395494,36.150368,36.007299,45.521869,38.191750,51.620759,49.621272,71.844854,69.871309
21,6,20250410_AS_MRC5_Confluence_Rep6,46,19.127657,16.941319,2.895089,2.658256,31.691687,24.145821,40.407321,...,36.437971,43.120824,37.116741,36.954243,48.285730,40.107116,54.746959,53.855926,76.439394,75.176608
22,6,20250410_AS_MRC5_Confluence_Rep6,48,18.777701,17.360448,2.897949,2.479530,32.292889,25.163234,42.500862,...,39.219144,45.809469,38.920657,38.662856,52.218950,42.595949,58.463265,57.861922,82.331214,79.913147
23,6,20250410_AS_MRC5_Confluence_Rep6,50,19.823740,17.709841,2.787744,2.601822,33.885725,26.189885,44.738663,...,41.093304,47.664631,41.088446,40.848668,54.456579,45.062186,63.289734,62.107163,86.512326,84.374005
24,6,20250410_AS_MRC5_Confluence_Rep6,52,20.893409,18.155091,2.856283,2.414867,34.943476,27.507679,46.541072,...,42.270396,49.837380,43.081703,42.762766,58.472991,48.505027,67.137869,66.424600,90.622613,88.312788
25,6,20250410_AS_MRC5_Confluence_Rep6,54,21.366864,18.099920,2.781965,2.860679,35.776144,28.386246,48.546165,...,44.723114,51.767140,44.611013,44.918935,60.922645,51.583054,71.781735,71.131684,93.719674,91.953479
26,6,20250410_AS_MRC5_Confluence_Rep6,56,21.832189,18.445556,2.497243,2.613278,37.931222,29.034926,51.114001,...,47.610657,53.902666,46.832386,46.735503,64.016410,55.134176,76.464130,75.099311,95.954161,94.659792
27,6,20250410_AS_MRC5_Confluence_Rep6,58,22.904728,19.228152,2.858904,2.734281,39.170711,30.627645,53.370999,...,49.614989,56.646093,48.067941,48.387764,68.462910,58.625623,80.449266,80.042226,97.771235,96.649835
28,6,20250410_AS_MRC5_Confluence_Rep6,60,23.637174,19.374708,2.859937,2.872937,41.450690,31.762415,55.697609,...,52.068185,58.950715,51.097044,50.508667,71.532347,61.635627,84.070759,84.723878,98.820294,97.709124
29,6,20250410_AS_MRC5_Confluence_Rep6,62,23.916695,19.711110,2.720649,2.934502,43.270567,33.544896,58.738559,...,54.565965,61.786789,53.195499,52.731981,74.428391,65.417650,87.435528,88.678621,99.418975,98.633381
30,6,20250410_AS_MRC5_Confluence_Rep6,64,24.230452,20.693809,2.747077,2.876617,44.576592,33.996690,61.161322,...,57.063446,64.276204,55.721326,54.644158,77.886463,69.098844,90.384500,91.778451,99.735674,99.117101
31,6,20250410_AS_MRC5_Confluence_Rep6,66,25.330759,21.853941,2.637828,2.780907,45.590952,35.523379,63.235564,...,60.355130,67.241865,57.958160,56.813852,79.699834,72.442395,92.817395,93.970525,99.890640,99.524320
32,6,20250410_AS_MRC5_Confluence_Rep6,68,25.713717,22.483234,2.733735,2.931557,47.231519,37.315239,65.687353,...,62.841076,69.591266,60.566259,59.254454,82.636972,75.635402,94.977784,95.596888,99.967996,99.733090
33,6,20250410_AS_MRC5_Confluence_Rep6,70,26.293260,23.952997,2.886536,2.777851,49.070796,38.667471,68.305551,...,65.641489,72.064460,62.923580,61.048734,85.603731,78.834009,96.417606,96.978669,99.977211,99.836046
34,6,20250410_AS_MRC5_Confluence_Rep6,72,27.104884,24.835784,2.776989,2.858775,49.848665,40.359216,70.500836,...,67.468445,74.458680,64.371045,63.003382,87.703625,81.582435,97.465806,97.960071,99.979699,99.900582

,Plate_Number,Vessel Name,Elapsed,Doxo_P12 LIN11-0C-b5,P34 LIN3-0A-b2-s1-ss1,P31 LIN3-0A-b2-s1-ss2,P29 LIN3-0A-b2-s2-ss1-ss1,P25 LIN7-0C-b3-s1,P22 LIN8-0B-b2B-s1-ss1,P22 LIN8-0B-b2B-s1-ss2,P18 LIN6-0C-b1-s2,P14 LIN11-0C-b5,P13 LIN12-0C-b2-s2
0,6,20250410_AS_MRC5_Confluence_Rep6,4,15.082692,3.530316,16.203382,18.483872,7.396893,14.221724,16.171217,13.339558,12.728318,16.433907
1,6,20250410_AS_MRC5_Confluence_Rep6,6,14.942013,3.636334,16.963723,19.472289,7.725872,14.592285,16.331074,13.904291,13.546702,17.697871
2,6,20250410_AS_MRC5_Confluence_Rep6,8,15.295686,3.206347,16.689259,19.168629,7.526095,15.036548,16.306881,13.853196,15.097300,19.196670
3,6,20250410_AS_MRC5_Confluence_Rep6,10,15.397888,3.634413,16.703670,20.325086,7.567236,15.937611,16.612507,15.245772,16.102969,21.513317
4,6,20250410_AS_MRC5_Confluence_Rep6,12,15.128216,3.219890,17.187554,20.704913,7.660932,16.806956,17.223523,16.070931,17.223896,22.861896
5,6,20250410_AS_MRC5_Confluence_Rep6,14,15.228586,3.464031,17.414225,21.754034,8.146435,17.631222,17.889661,17.336800,18.500608,24.341296
6,6,20250410_AS_MRC5_Confluence_Rep6,16,15.338011,3.027395,17.550069,21.962085,8.380075,18.114304,17.925014,18.178066,18.749957,24.949644
7,6,20250410_AS_MRC5_Confluence_Rep6,18,15.054183,3.112349,17.995676,22.393150,8.738804,18.870268,19.421028,18.994088,20.130725,26.969856
8,6,20250410_AS_MRC5_Confluence_Rep6,20,14.821922,3.144830,18.194041,23.056768,8.872122,20.153982,19.883946,19.618038,21.685223,29.413431
9,6,20250410_AS_MRC5_Confluence_Rep6,22,15.074160,3.165147,18.602746,24.081759,8.994925,21.018660,20.929237,20.319841,23.019716,31.525869
10,6,20250410_AS_MRC5_Confluence_Rep6,24,14.957385,3.049888,19.027590,25.472358,9.255810,21.722463,21.887066,21.919029,24.765751,33.799374
11,6,20250410_AS_MRC5_Confluence_Rep6,26,14.987173,2.914015,19.508467,26.815674,9.491653,23.010931,22.936221,23.826728,26.710143,36.027859
12,6,20250410_AS_MRC5_Confluence_Rep6,28,15.118869,3.119707,20.107664,28.147885,9.790995,24.247687,24.372613,25.346089,28.909101,38.360753
13,6,20250410_AS_MRC5_Confluence_Rep6,30,15.720909,3.449656,21.250438,29.556588,9.945222,26.262285,25.908709,26.962966,30.993152,42.373661
14,6,20250410_AS_MRC5_Confluence_Rep6,32,15.823764,2.928578,21.890743,30.931024,10.360615,27.526041,27.403161,28.685021,33.497383,45.576262
15,6,20250410_AS_MRC5_Confluence_Rep6,34,16.202959,3.455576,22.661126,32.564910,10.340085,28.963113,28.502621,30.299021,35.863462,49.351871
16,6,20250410_AS_MRC5_Confluence_Rep6,36,16.117957,2.909328,23.425389,33.901817,10.688548,30.385234,29.928382,32.399244,38.447584,53.506887
17,6,20250410_AS_MRC5_Confluence_Rep6,38,16.740765,3.047302,24.436021,35.799352,11.043624,31.967004,31.467436,34.589079,40.968170,57.422742
18,6,20250410_AS_MRC5_Confluence_Rep6,40,17.441156,3.025965,25.264563,37.271713,11.297167,33.738681,32.784111,36.769553,44.031204,61.594709
19,6,20250410_AS_MRC5_Confluence_Rep6,42,17.524276,2.829188,26.291105,38.798659,11.574097,35.722868,33.995362,39.155698,47.195606,65.914608
20,6,20250410_AS_MRC5_Confluence_Rep6,44,17.793658,2.974879,27.099466,40.828829,12.008452,38.289667,36.078833,41.856809,50.621016,70.858081
21,6,20250410_AS_MRC5_Confluence_Rep6,46,18.034488,2.776673,27.918754,41.906419,12.150490,39.779398,37.035492,44.196423,54.301443,75.808001
22,6,20250410_AS_MRC5_Confluence_Rep6,48,18.069075,2.688739,28.728061,44.289857,12.267524,42.514306,38.791757,47.407449,58.162594,81.122181
23,6,20250410_AS_MRC5_Confluence_Rep6,50,18.766790,2.694783,30.037805,46.069316,12.444475,44.378968,40.968557,49.759383,62.698448,85.443166
24,6,20250410_AS_MRC5_Confluence_Rep6,52,19.524250,2.635575,31.225577,48.129891,13.029327,46.053888,42.922234,53.489009,66.781234,89.467700
25,6,20250410_AS_MRC5_Confluence_Rep6,54,19.733392,2.821322,32.081195,50.357591,13.312086,48.245127,44.764974,56.252849,71.456709,92.836576
26,6,20250410_AS_MRC5_Confluence_Rep6,56,20.138873,2.555260,33.483074,52.151593,13.618129,50.756662,46.783944,59.575293,75.781721,95.306977
27,6,20250410_AS_MRC5_Confluence_Rep6,58,21.066440,2.796592,34.899178,54.609847,14.143992,53.130541,48.227852,63.544266,80.245746,97.210535
28,6,20250410_AS_MRC5_Confluence_Rep6,60,21.505941,2.866437,36.606553,56.598718,14.168658,55.509450,50.802856,66.583987,84.397318,98.264709
29,6,20250410_AS_MRC5_Confluence_Rep6,62,21.813902,2.827575,38.407732,59.394614,14.558630,58.176377,52.963740,69.923021,88.057074,99.026178
30,6,20250410_AS_MRC5_Confluence_Rep6,64,22.462131,2.811847,39.286641,61.352242,14.677052,60.669825,55.182742,73.492653,91.081476,99.426388
31,6,20250410_AS_MRC5_Confluence_Rep6,66,23.592350,2.709368,40.557166,63.454140,14.814087,63.798498,57.386006,76.071114,93.393960,99.707480
32,6,20250410_AS_MRC5_Confluence_Rep6,68,24.098476,2.832646,42.273379,66.128830,15.417928,66.216171,59.910356,79.136188,95.287336,99.850543
33,6,20250410_AS_MRC5_Confluence_Rep6,70,25.123129,2.832193,43.869134,68.278148,15.847065,68.852974,61.986157,82.218870,96.698138,99.906629
34,6,20250410_AS_MRC5_Confluence_Rep6,72,25.970334,2.817882,45.103941,70.453775,16.093135,70.963562,63.687214,84.643030,97.712939,99.940141

Wrote replaced data to: /Users/allielas/HTP_fibroblasts_mitolyso/proliferation_growth_curves/Incucyte_sheets/r6_processed.xlsx

/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Plate_Number,Vessel_Name,Elapsed,"Doxo_P19 LIN12-0C-b2-s2 (A1), Image 1","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 2","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 3","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 4","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 5","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 6","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 7",...,"Blank (C3), Image 9","Blank (C4), Image 1","Blank (C4), Image 2","Blank (C4), Image 3","Blank (C4), Image 4","Blank (C4), Image 5","Blank (C4), Image 6","Blank (C4), Image 7","Blank (C4), Image 8","Blank (C4), Image 9"
0,7,20250501_AS_MRC-5_Confluence,0,14.37534,15.92760,1.806777,3.849841,87.15396,5.606152,5.800508,...,0.380996,0.293447,0.033872,0.123743,0.141499,0.638590,0.122719,0.212795,0.625819,0.286071
1,7,20250501_AS_MRC-5_Confluence,2,15.88587,15.96686,3.029051,3.373511,88.91260,6.081868,5.244959,...,0.234716,0.311544,0.087754,0.257799,0.191420,1.701336,0.483159,0.162396,0.616668,0.756870
2,7,20250501_AS_MRC-5_Confluence,4,15.77353,16.47550,3.036290,3.456963,90.30471,7.190301,6.018014,...,0.525090,0.445873,0.272550,0.336607,0.672531,5.245575,0.466838,0.182610,5.572279,0.658258
3,7,20250501_AS_MRC-5_Confluence,6,16.08801,16.31747,3.001666,3.587808,89.99898,5.811367,5.851794,...,0.471140,0.527549,0.139928,0.213478,0.710091,7.566994,0.336334,0.214161,1.539691,0.213068
4,7,20250501_AS_MRC-5_Confluence,8,16.07449,16.58627,2.832714,3.704177,88.74133,5.470730,6.220634,...,0.208493,0.334695,0.227819,0.113500,0.139860,10.554120,0.396703,0.083042,2.310151,0.615439
5,7,20250501_AS_MRC-5_Confluence,10,17.27983,16.71561,3.338751,3.628578,88.84970,5.389533,5.053198,...,0.295769,0.279925,0.027180,0.029092,0.363513,11.368350,0.357231,0.114183,1.886336,0.309085
6,7,20250501_AS_MRC-5_Confluence,12,16.67416,17.32941,2.735946,3.887538,88.73613,5.677310,5.368635,...,0.104417,0.241136,0.238336,0.064262,1.737325,8.279817,0.316324,0.122787,0.829054,1.127895
7,7,20250501_AS_MRC-5_Confluence,14,17.29806,16.88695,3.194657,3.841919,87.74017,5.299525,5.123333,...,0.084954,0.504671,0.146758,0.129890,3.004194,17.425700,0.572962,0.117461,0.659487,0.235604
8,7,20250501_AS_MRC-5_Confluence,16,18.42807,16.36398,3.035607,3.684577,88.85304,5.814235,5.384888,...,0.080583,0.264013,0.000000,0.034555,0.187869,3.115029,0.156933,0.141363,0.627732,0.057638
9,7,20250501_AS_MRC-5_Confluence,18,18.75007,15.80153,4.061611,4.389205,87.94567,5.692607,5.199273,...,0.272277,0.239633,0.169840,0.167381,0.287779,3.914582,0.404147,0.115139,0.765133,0.215731
10,7,20250501_AS_MRC-5_Confluence,20,17.06348,16.04240,3.649680,4.342425,84.77477,6.013644,5.123607,...,0.337563,0.394722,0.182337,0.000000,0.337221,4.360795,0.632512,0.082974,1.119427,0.416302
11,7,20250501_AS_MRC-5_Confluence,22,18.53515,16.18062,4.364619,3.915401,84.53255,6.453370,5.496613,...,0.401415,0.246941,0.139519,0.120739,0.495042,5.897822,0.466155,0.131324,1.094228,0.448399
12,7,20250501_AS_MRC-5_Confluence,24,19.07049,15.12087,3.851685,4.307528,83.52190,5.952320,4.660320,...,0.376830,0.411181,0.043570,0.027316,0.698891,6.388494,0.598503,0.114046,1.101876,0.407834
13,7,20250501_AS_MRC-5_Confluence,26,19.36223,16.11745,3.674197,3.204286,84.78002,5.995206,4.228242,...,0.190942,0.512593,0.000000,0.128387,1.118540,11.421680,0.358938,0.124153,2.634055,0.286345
14,7,20250501_AS_MRC-5_Confluence,28,18.10192,17.19747,3.968054,3.308020,84.05827,5.687145,4.348298,...,0.271525,0.357572,0.225975,0.072730,0.491150,9.758728,0.560260,0.156660,0.869550,0.155909
15,7,20250501_AS_MRC-5_Confluence,30,17.68404,18.03021,3.990999,4.261090,83.65569,5.742939,4.215472,...,0.088778,0.315778,0.146826,0.147372,0.325134,9.815406,0.531441,0.082700,0.899393,0.163489
16,7,20250501_AS_MRC-5_Confluence,32,17.38336,16.52104,3.786398,4.041329,81.67900,6.526169,4.381419,...,0.120329,0.248170,0.059140,0.000000,0.481316,13.972830,0.538134,0.114797,0.840868,0.532875
17,7,20250501_AS_MRC-5_Confluence,34,18.85278,15.45072,4.057515,3.429988,82.27190,6.520365,4.727450,...,0.142319,0.237721,0.240726,0.214502,0.583820,8.155662,0.447512,0.204805,0.758577,0.555753
18,7,20250501_AS_MRC-5_Confluence,36,18.89935,14.49711,3.635134,3.517606,81.45473,6.760613,4.134889,...,0.120875,0.343231,0.097178,0.030253,1.547271,14.153940,0.426956,0.122241,0.921315,0.320285
19,7,20250501_AS_MRC-5_Confluence,38,18.39441,14.80189,3.234128,3.610823,82.85839,7.434099,4.510899,...,0.145870,0.322744,0.297886,0.138153,0.432692,15.009630,0.554387,0.097520,0.729895,0.517578
20,7,20250501_AS_MRC-5_Confluence,40,18.47144,17.37414,3.295113,3.845745,79.80680,6.202606,4.543270,...,0.155226,0.405308,0.147440,0.108993,0.190464,9.583355,0.311202,0.114866,0.811366,0.158367
21,7,20250501_AS_MRC-5_Confluence,42,14.73360,16.96569,3.399530,4.049866,80.04240,6.080432,4.881583,...,0.118827,0.334763,0.000000,0.250150,0.235604,7.365534,0.396293,0.119168,1.230264,0.288120
22,7,20250501_AS_MRC-5_Confluence,44,16.53750,16.94452,3.353297,3.826076,79.94257,6.613785,4.992965,...,0.117939,0.453316,0.026702,0.282930,0.228912,7.736628,0.897481,0.145802,0.915852,0.224609
23,7,20250501_AS_MRC-5_Confluence,46,16.80705,16.90997,3.049128,3.797326,79.15640,6.095729,4.959367,...,0.186162,0.270706,0.000000,0.228912,0.230551,11.485470,0.531851,0.085091,0.756597,0.249262
24,7,20250501_AS_MRC-5_Confluence,48,17.48573,16.94807,3.223408,3.663885,79.56635,5.873649,4.948440,...,0.104280,0.233897,0.606356,0.033736,1.762525,7.334803,0.760285,0.084544,2.347506,0.728529
25,7,20250501_AS_MRC-5_Confluence,50,16.77188,16.86394,3.186939,3.419266,78.23972,7.430820,4.995424,...,0.211293,0.296998,0.030116,0.034419,1.052229,12.741130,0.472574,0.138563,1.319930,0.639683
26,7,20250501_AS_MRC-5_Confluence,52,16.89446,16.62355,2.939931,3.542737,77.81433,7.279761,5.352723,...,0.185683,0.201937,0.115139,0.036809,1.666917,13.737020,0.387688,0.107627,2.201226,0.634834
27,7,20250501_AS_MRC-5_Confluence,54,15.97056,15.57665,2.827182,3.433539,76.80329,7.743321,5.649585,...,0.294061,0.242570,0.027794,0.000000,3.003510,10.090210,0.649243,0.076896,1.088492,0.316393
28,7,20250501_AS_MRC-5_Confluence,56,16.81948,14.70041,2.852450,3.206403,78.49575,6.964870,6.076813,...,0.164855,0.333124,0.211224,0.082632,0.120466,10.943780,0.422517,0.091988,0.928144,0.224473
29,7,20250501_AS_MRC-5_Confluence,58,16.61379,17.06601,2.727000,3.208862,77.98862,8.103966,5.185069,...,0.116300,0.228092,0.083588,0.176669,4.187472,13.659920,0.567294,0.082564,0.697252,0.223175
30,7,20250501_AS_MRC-5_Confluence,60,15.31045,17.53497,2.024967,3.060397,75.06413,7.773573,6.022932,...,0.190532,0.444780,0.000000,0.000000,1.817909,13.794050,0.767728,0.155089,1.149134,0.491354
31,7,20250501_AS_MRC-5_Confluence,62,15.61161,16.37456,2.510107,2.791671,76.01699,8.254615,5.898504,...,0.095676,0.337153,0.028887,0.116300,2.391485,13.052610,0.648151,0.077442,0.810137,0.409473
32,7,20250501_AS_MRC-5_Confluence,64,15.63552,15.90725,1.978051,3.490220,74.79144,7.682063,5.775036,...,0.091442,0.239770,0.121626,0.145255,0.197361,13.489470,0.620971,0.122309,0.962290,0.170318
33,7,20250501_AS_MRC-5_Confluence,66,15.82059,16.63045,1.570900,2.462508,74.35163,7.953726,5.775855,...,0.091169,0.267223,0.033736,0.040838,0.155567,16.041300,0.356479,0.121080,1.836484,0.418488
34,7,20250501_AS_MRC-5_Confluence,68,14.94223,16.54986,1.952306,3.128141,74.69952,7.679401,5.223790,...,0.207741,0.226180,0.000000,0.000000,0.394176,9.590048,0.591333,0.117939,0.826937,0.180425
35,7,20250501_AS_MRC-5_Confluence,70,15.05627,16.16703,2.411563,2.763467,73.84840,9.054168,4.451417,...,0.227478,0.329368,0.041043,0.248306,0.670482,10.393770,0.568797,0.113500,0.860058,0.304578
36,7,20250501_AS_MRC-5_Confluence,72,15.54735,17.25278,2.953111,3.399666,74.55815,9.924196,4.217452,...,0.254384,0.448399,0.132416,0.000000,0.806245,8.209544,0.484252,0.111519,1.864824,0.251106

,Plate_Number,Vessel_Name,Elapsed,"Doxo_P19 LIN12-0C-b2-s2 (A1), Image 1","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 2","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 3","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 4","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 6","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 7","Doxo_P19 LIN12-0C-b2-s2 (A1), Image 8",...,"Blank (C3), Image 8","Blank (C3), Image 9","Blank (C4), Image 1","Blank (C4), Image 2","Blank (C4), Image 3","Blank (C4), Image 4","Blank (C4), Image 6","Blank (C4), Image 7","Blank (C4), Image 8","Blank (C4), Image 9"
0,7,20250501_AS_MRC-5_Confluence,4,15.77353,16.47550,3.036290,3.456963,7.190301,6.018014,9.575639,...,0.129890,0.525090,0.445873,0.272550,0.336607,0.672531,0.466838,0.182610,5.572279,0.658258
1,7,20250501_AS_MRC-5_Confluence,6,16.08801,16.31747,3.001666,3.587808,5.811367,5.851794,10.884910,...,0.238677,0.471140,0.527549,0.139928,0.213478,0.710091,0.336334,0.214161,1.539691,0.213068
2,7,20250501_AS_MRC-5_Confluence,8,16.07449,16.58627,2.832714,3.704177,5.470730,6.220634,10.511090,...,0.238746,0.208493,0.334695,0.227819,0.113500,0.139860,0.396703,0.083042,2.310151,0.615439
3,7,20250501_AS_MRC-5_Confluence,10,17.27983,16.71561,3.338751,3.628578,5.389533,5.053198,9.527699,...,0.511568,0.295769,0.279925,0.027180,0.029092,0.363513,0.357231,0.114183,1.886336,0.309085
4,7,20250501_AS_MRC-5_Confluence,12,16.67416,17.32941,2.735946,3.887538,5.677310,5.368635,11.183900,...,0.242297,0.104417,0.241136,0.238336,0.064262,1.737325,0.316324,0.122787,0.829054,1.127895
5,7,20250501_AS_MRC-5_Confluence,14,17.29806,16.88695,3.194657,3.841919,5.299525,5.123333,11.608190,...,0.121012,0.084954,0.504671,0.146758,0.129890,3.004194,0.572962,0.117461,0.659487,0.235604
6,7,20250501_AS_MRC-5_Confluence,16,18.42807,16.36398,3.035607,3.684577,5.814235,5.384888,10.642410,...,0.161918,0.080583,0.264013,0.000000,0.034555,0.187869,0.156933,0.141363,0.627732,0.057638
7,7,20250501_AS_MRC-5_Confluence,18,18.75007,15.80153,4.061611,4.389205,5.692607,5.199273,13.250790,...,0.264286,0.272277,0.239633,0.169840,0.167381,0.287779,0.404147,0.115139,0.765133,0.215731
8,7,20250501_AS_MRC-5_Confluence,20,17.06348,16.04240,3.649680,4.342425,6.013644,5.123607,11.377980,...,0.237243,0.337563,0.394722,0.182337,0.000000,0.337221,0.632512,0.082974,1.119427,0.416302
9,7,20250501_AS_MRC-5_Confluence,22,18.53515,16.18062,4.364619,3.915401,6.453370,5.496613,12.551490,...,0.289281,0.401415,0.246941,0.139519,0.120739,0.495042,0.466155,0.131324,1.094228,0.448399
10,7,20250501_AS_MRC-5_Confluence,24,19.07049,15.12087,3.851685,4.307528,5.952320,4.660320,12.377550,...,0.357094,0.376830,0.411181,0.043570,0.027316,0.698891,0.598503,0.114046,1.101876,0.407834
11,7,20250501_AS_MRC-5_Confluence,26,19.36223,16.11745,3.674197,3.204286,5.995206,4.228242,13.161060,...,0.151470,0.190942,0.512593,0.000000,0.128387,1.118540,0.358938,0.124153,2.634055,0.286345
12,7,20250501_AS_MRC-5_Confluence,28,18.10192,17.19747,3.968054,3.308020,5.687145,4.348298,13.639300,...,0.292354,0.271525,0.357572,0.225975,0.072730,0.491150,0.560260,0.156660,0.869550,0.155909
13,7,20250501_AS_MRC-5_Confluence,30,17.68404,18.03021,3.990999,4.261090,5.742939,4.215472,13.389010,...,0.282520,0.088778,0.315778,0.146826,0.147372,0.325134,0.531441,0.082700,0.899393,0.163489
14,7,20250501_AS_MRC-5_Confluence,32,17.38336,16.52104,3.786398,4.041329,6.526169,4.381419,14.108870,...,0.226248,0.120329,0.248170,0.059140,0.000000,0.481316,0.538134,0.114797,0.840868,0.532875
15,7,20250501_AS_MRC-5_Confluence,34,18.85278,15.45072,4.057515,3.429988,6.520365,4.727450,13.041410,...,0.176464,0.142319,0.237721,0.240726,0.214502,0.583820,0.447512,0.204805,0.758577,0.555753
16,7,20250501_AS_MRC-5_Confluence,36,18.89935,14.49711,3.635134,3.517606,6.760613,4.134889,14.249620,...,0.181586,0.120875,0.343231,0.097178,0.030253,1.547271,0.426956,0.122241,0.921315,0.320285
17,7,20250501_AS_MRC-5_Confluence,38,18.39441,14.80189,3.234128,3.610823,7.434099,4.510899,13.534200,...,0.150172,0.145870,0.322744,0.297886,0.138153,0.432692,0.554387,0.097520,0.729895,0.517578
18,7,20250501_AS_MRC-5_Confluence,40,18.47144,17.37414,3.295113,3.845745,6.202606,4.543270,13.654190,...,0.166903,0.155226,0.405308,0.147440,0.108993,0.190464,0.311202,0.114866,0.811366,0.158367
19,7,20250501_AS_MRC-5_Confluence,42,14.73360,16.96569,3.399530,4.049866,6.080432,4.881583,15.514510,...,0.202961,0.118827,0.334763,0.000000,0.250150,0.235604,0.396293,0.119168,1.230264,0.288120
20,7,20250501_AS_MRC-5_Confluence,44,16.53750,16.94452,3.353297,3.826076,6.613785,4.992965,15.719450,...,0.251789,0.117939,0.453316,0.026702,0.282930,0.228912,0.897481,0.145802,0.915852,0.224609
21,7,20250501_AS_MRC-5_Confluence,46,16.80705,16.90997,3.049128,3.797326,6.095729,4.959367,15.150440,...,0.251311,0.186162,0.270706,0.000000,0.228912,0.230551,0.531851,0.085091,0.756597,0.249262
22,7,20250501_AS_MRC-5_Confluence,48,17.48573,16.94807,3.223408,3.663885,5.873649,4.948440,14.614430,...,0.239019,0.104280,0.233897,0.606356,0.033736,1.762525,0.760285,0.084544,2.347506,0.728529
23,7,20250501_AS_MRC-5_Confluence,50,16.77188,16.86394,3.186939,3.419266,7.430820,4.995424,14.576730,...,0.191625,0.211293,0.296998,0.030116,0.034419,1.052229,0.472574,0.138563,1.319930,0.639683
24,7,20250501_AS_MRC-5_Confluence,52,16.89446,16.62355,2.939931,3.542737,7.279761,5.352723,14.832750,...,0.240316,0.185683,0.201937,0.115139,0.036809,1.666917,0.387688,0.107627,2.201226,0.634834
25,7,20250501_AS_MRC-5_Confluence,54,15.97056,15.57665,2.827182,3.433539,7.743321,5.649585,14.377320,...,0.086661,0.294061,0.242570,0.027794,0.000000,3.003510,0.649243,0.076896,1.088492,0.316393
26,7,20250501_AS_MRC-5_Confluence,56,16.81948,14.70041,2.852450,3.206403,6.964870,6.076813,14.579600,...,0.154816,0.164855,0.333124,0.211224,0.082632,0.120466,0.422517,0.091988,0.928144,0.224473
27,7,20250501_AS_MRC-5_Confluence,58,16.61379,17.06601,2.727000,3.208862,8.103966,5.185069,15.668770,...,0.145938,0.116300,0.228092,0.083588,0.176669,4.187472,0.567294,0.082564,0.697252,0.223175
28,7,20250501_AS_MRC-5_Confluence,60,15.31045,17.53497,2.024967,3.060397,7.773573,6.022932,14.993510,...,0.335992,0.190532,0.444780,0.000000,0.000000,1.817909,0.767728,0.155089,1.149134,0.491354
29,7,20250501_AS_MRC-5_Confluence,62,15.61161,16.37456,2.510107,2.791671,8.254615,5.898504,15.500370,...,0.251789,0.095676,0.337153,0.028887,0.116300,2.391485,0.648151,0.077442,0.810137,0.409473
30,7,20250501_AS_MRC-5_Confluence,64,15.63552,15.90725,1.978051,3.490220,7.682063,5.775036,15.507540,...,0.106398,0.091442,0.239770,0.121626,0.145255,0.197361,0.620971,0.122309,0.962290,0.170318
31,7,20250501_AS_MRC-5_Confluence,66,15.82059,16.63045,1.570900,2.462508,7.953726,5.775855,15.277120,...,0.190122,0.091169,0.267223,0.033736,0.040838,0.155567,0.356479,0.121080,1.836484,0.418488
32,7,20250501_AS_MRC-5_Confluence,68,14.94223,16.54986,1.952306,3.128141,7.679401,5.223790,15.869480,...,0.138631,0.207741,0.226180,0.000000,0.000000,0.394176,0.591333,0.117939,0.826937,0.180425
33,7,20250501_AS_MRC-5_Confluence,70,15.05627,16.16703,2.411563,2.763467,9.054168,4.451417,14.149840,...,0.184318,0.227478,0.329368,0.041043,0.248306,0.670482,0.568797,0.113500,0.860058,0.304578
34,7,20250501_AS_MRC-5_Confluence,72,15.54735,17.25278,2.953111,3.399666,9.924196,4.217452,14.274620,...,0.203371,0.254384,0.448399,0.132416,0.000000,0.806245,0.484252,0.111519,1.864824,0.251106

,Plate_Number,Vessel_Name,Elapsed,Doxo_P19 LIN12-0C-b2-s2 (A1),Doxo_P19 LIN12-0C-b2-s2 (A2),P34 LIN3-0A-b2-s1-ss2 (A3),P34 LIN3-0A-b2-s1-ss2 (A4),P33 LIN3-0A-b2-s2-ss1-ss1 (B1),P33 LIN3-0A-b2-s2-ss1-ss1 (B2),P29 LIN2-0A-b1-s1-ss1 (B3),...,P24 LIN7-0C-b3-s2 (A3),P24 LIN7-0C-b3-s2 (A4),P21 LIN11-0C-b5 (B1),P21 LIN11-0C-b5 (B2),P20 LIN12-0C-b2-s2 (B3),P20 LIN12-0C-b2-s2 (B4),P13 LIN11-0C-b5-s1 (C1),P13 LIN11-0C-b5-s1 (C2),Blank (C3),Blank (C4)
0,7,20250501_AS_MRC-5_Confluence,4,7.955220,4.453057,3.789882,2.297022,15.315026,12.455320,11.923360,...,9.220321,11.857602,19.490060,19.065059,17.745754,23.016741,19.761686,20.502607,0.245003,1.075943
1,7,20250501_AS_MRC-5_Confluence,6,7.942508,5.295427,3.866812,2.308614,15.446853,12.480333,12.619363,...,9.818227,12.606603,19.600086,19.002469,18.338280,23.410875,20.729056,21.292289,0.351366,0.486787
2,7,20250501_AS_MRC-5_Confluence,8,7.927912,5.101549,3.872924,2.297090,15.604418,12.411394,13.023597,...,10.126535,12.858869,21.086764,19.959202,19.379088,24.950239,22.474090,23.478021,0.251533,0.527651
3,7,20250501_AS_MRC-5_Confluence,10,7.898888,5.580602,4.187635,2.107036,15.596728,12.700902,13.804069,...,10.806731,13.193555,21.837277,20.874440,20.726820,27.152598,25.113431,25.986975,0.335617,0.420818
4,7,20250501_AS_MRC-5_Confluence,12,8.159804,5.535154,3.906660,2.275416,16.368775,13.116711,14.418347,...,11.285246,14.023401,22.959891,22.463445,21.769504,28.608219,27.178124,28.666232,0.188629,0.584640
5,7,20250501_AS_MRC-5_Confluence,14,8.218098,5.115882,3.892096,2.187876,15.969016,12.968051,14.976762,...,11.373010,14.282602,24.273551,23.694983,22.879704,30.507425,28.845570,30.053607,0.170830,0.671378
6,7,20250501_AS_MRC-5_Confluence,16,8.240863,5.426674,3.714608,2.195473,16.351839,12.675518,15.022433,...,12.358405,14.988082,24.736454,24.260920,23.950425,32.434328,30.042099,31.106041,0.133842,0.183763
7,7,20250501_AS_MRC-5_Confluence,18,8.740464,5.445983,3.526432,2.214594,16.711979,13.442389,15.532738,...,12.705367,15.730081,26.955011,25.223369,25.543819,34.046081,32.213528,33.472941,0.258396,0.295598
8,7,20250501_AS_MRC-5_Confluence,20,8.314611,5.462245,3.613392,2.171588,17.060444,13.564631,16.214675,...,13.358648,16.636195,28.572320,26.669569,26.789916,36.324759,34.506068,36.404607,0.219889,0.395687
9,7,20250501_AS_MRC-5_Confluence,22,8.787986,5.440382,3.603251,2.176112,17.207652,14.188292,16.614323,...,13.275342,17.031335,29.657826,28.294430,27.923564,38.532681,38.366561,40.038695,0.244183,0.392793
10,7,20250501_AS_MRC-5_Confluence,24,8.548847,5.537955,3.443211,2.126456,17.327359,14.086094,17.610460,...,13.632403,18.411027,31.439995,30.051840,30.336574,41.636184,42.442774,43.496646,0.232599,0.425402
11,7,20250501_AS_MRC-5_Confluence,26,8.585641,5.692505,3.706848,2.285779,17.871493,14.010948,18.224080,...,14.264000,18.876083,33.115890,32.255670,32.854026,44.973026,46.110616,46.283120,0.203678,0.645376
12,7,20250501_AS_MRC-5_Confluence,28,8.679507,5.507402,3.693839,2.081819,19.139044,14.872671,19.306539,...,14.841378,19.704988,36.052370,34.826685,34.701507,47.784054,49.628912,49.528156,0.233214,0.361226
13,7,20250501_AS_MRC-5_Confluence,30,8.812895,5.772091,3.577317,2.224966,19.276446,15.027317,20.408360,...,15.744971,20.900672,38.970066,36.668416,36.977263,51.404295,52.875298,52.938974,0.280292,0.326517
14,7,20250501_AS_MRC-5_Confluence,32,8.743580,5.511065,3.734532,2.000391,20.006486,15.566039,20.928278,...,16.290404,21.775756,41.209509,38.871811,38.996041,54.554226,57.371295,57.711879,0.226402,0.351912
15,7,20250501_AS_MRC-5_Confluence,34,8.703741,5.602164,3.841826,2.132637,20.603503,16.189799,22.254885,...,17.339319,22.245650,43.496730,41.334122,42.028884,58.370570,61.946416,62.763431,0.275631,0.405427
16,7,20250501_AS_MRC-5_Confluence,36,8.590900,5.791588,4.066572,2.065959,21.150269,16.439087,23.195935,...,18.191533,22.996013,45.851136,43.676839,44.896605,62.252446,66.293813,68.179800,0.207007,0.476091
17,7,20250501_AS_MRC-5_Confluence,38,8.557684,5.448331,3.978382,2.183958,21.621929,16.461889,24.356406,...,19.233595,24.215701,48.437565,46.388832,47.680475,66.108259,71.487208,73.611004,0.211583,0.386357
18,7,20250501_AS_MRC-5_Confluence,40,8.781175,5.771169,4.023685,2.220869,22.402504,16.899499,25.806285,...,19.850279,25.090433,50.790290,48.896150,51.613366,70.083003,75.968741,78.549290,0.208774,0.281001
19,7,20250501_AS_MRC-5_Confluence,42,8.536250,5.680000,4.061365,2.151451,22.786704,17.191163,26.814652,...,20.672555,26.492439,53.693929,52.090310,54.269007,73.735354,80.260080,82.922694,0.203764,0.356795
20,7,20250501_AS_MRC-5_Confluence,44,8.854895,5.958840,4.186755,2.095759,23.088909,17.348532,27.800165,...,21.674898,27.955652,56.616566,55.217565,58.392312,78.079414,83.819330,87.570433,0.202833,0.396950
21,7,20250501_AS_MRC-5_Confluence,46,8.643986,5.993132,4.090337,2.375642,23.835379,17.483591,29.550010,...,22.600259,29.433788,59.422137,57.980007,61.193101,81.684619,87.284851,91.035391,0.213529,0.294121
22,7,20250501_AS_MRC-5_Confluence,48,8.677945,5.946088,4.423700,2.284149,24.777114,18.435666,30.498421,...,23.143931,30.315681,62.385807,61.676389,65.793477,84.846366,90.327414,94.261884,0.299081,0.819672
23,7,20250501_AS_MRC-5_Confluence,50,8.739073,5.964415,4.343705,2.212605,25.213663,18.792176,31.698714,...,23.937339,31.764743,65.197743,64.988548,70.037666,87.755679,92.535747,96.375429,0.208322,0.498064
24,7,20250501_AS_MRC-5_Confluence,52,8.798502,6.237126,4.295065,2.689414,26.088763,19.813770,32.877862,...,24.843265,32.602099,68.646486,68.848525,73.707956,90.490353,94.565771,97.917682,0.206598,0.669022
25,7,20250501_AS_MRC-5_Confluence,54,8.573494,6.321083,4.356254,2.422362,26.454965,19.427789,35.426425,...,25.563180,33.944875,71.317624,72.007550,77.774294,92.322456,95.871303,98.763074,0.201809,0.675612
26,7,20250501_AS_MRC-5_Confluence,56,8.554756,6.040884,4.538276,2.781709,27.267606,20.442039,36.710330,...,26.300014,34.382091,73.868934,74.204950,81.387560,93.544509,97.178136,99.321316,0.185393,0.301821
27,7,20250501_AS_MRC-5_Confluence,58,9.015063,6.142066,4.661737,2.737235,27.874200,20.644957,39.089983,...,27.255414,36.431414,76.286243,77.549029,85.134531,94.990372,97.878668,99.614461,0.174671,0.780763
28,7,20250501_AS_MRC-5_Confluence,60,8.794039,6.404918,4.671136,2.879144,28.582354,20.817162,40.022850,...,28.374047,37.880593,78.724259,79.737902,88.472391,95.789016,98.461713,99.786920,0.221895,0.603249
29,7,20250501_AS_MRC-5_Confluence,62,8.749256,6.554749,4.764114,2.890702,29.458460,21.882263,41.013106,...,29.485684,39.373332,81.172546,82.892014,90.322971,96.430794,98.898035,99.865421,0.197745,0.602378
30,7,20250501_AS_MRC-5_Confluence,64,8.678858,6.569834,4.344721,2.680451,30.273666,21.916675,43.711814,...,30.130278,41.121729,82.574357,85.331935,92.102730,97.246746,99.168833,99.917403,0.184335,0.322488
31,7,20250501_AS_MRC-5_Confluence,66,8.597301,6.617611,4.922865,2.888875,29.993008,23.090879,45.909686,...,31.712058,42.629735,83.498019,86.931036,93.721569,97.762218,99.380145,99.907144,0.162857,0.403737
32,7,20250501_AS_MRC-5_Confluence,68,8.610643,6.743710,4.786249,3.013310,31.891926,24.181189,46.644411,...,32.801749,44.093640,85.035603,88.197826,94.975439,97.772008,99.460649,99.929520,0.161756,0.292124
33,7,20250501_AS_MRC-5_Confluence,70,8.470006,6.979324,4.674388,2.812764,32.051776,24.231419,49.561260,...,34.931455,46.115746,85.935712,90.162635,96.254928,98.145031,99.532116,99.949990,0.246300,0.392016
34,7,20250501_AS_MRC-5_Confluence,72,8.904175,6.859874,5.017039,2.952019,32.412406,24.338156,51.605979,...,36.078360,47.322373,86.973700,91.139088,96.846141,98.391194,99.619218,99.940836,0.228715,0.512345

,Plate_Number,Vessel_Name,Elapsed,Doxo_P19 LIN12-0C-b2-s2,P34 LIN3-0A-b2-s1-ss2,P33 LIN3-0A-b2-s2-ss1-ss1,P29 LIN2-0A-b1-s1-ss1,P25 LIN8-0B-b2B-s1-ss1,P25 LIN8-0B-b2B-s1-ss2,P24 LIN6-0C-b1-s2,P24 LIN7-0C-b3-s2,P21 LIN11-0C-b5,P20 LIN12-0C-b2-s2,P13 LIN11-0C-b5-s1,Blank
0,7,20250501_AS_MRC-5_Confluence,4,6.204138,3.043452,13.885173,12.470451,10.741892,10.111454,11.636856,10.538961,19.277559,20.381248,20.132147,0.660473
1,7,20250501_AS_MRC-5_Confluence,6,6.618967,3.087713,13.963593,12.909930,10.945689,10.148118,12.316467,11.212415,19.301277,20.874578,21.010672,0.419077
2,7,20250501_AS_MRC-5_Confluence,8,6.514730,3.085007,14.007905,13.427965,11.144140,10.400641,12.576178,11.492702,20.522983,22.164663,22.976056,0.389592
3,7,20250501_AS_MRC-5_Confluence,10,6.739745,3.147335,14.148815,14.043284,11.777318,10.549346,13.117491,12.000143,21.355859,23.939709,25.550203,0.378217
4,7,20250501_AS_MRC-5_Confluence,12,6.847479,3.091038,14.742743,14.853613,11.951225,10.904173,13.530128,12.654324,22.711668,25.188861,27.922178,0.386634
5,7,20250501_AS_MRC-5_Confluence,14,6.666990,3.039986,14.468534,15.556482,12.598547,11.347455,14.011252,12.827806,23.984267,26.693564,29.449589,0.421104
6,7,20250501_AS_MRC-5_Confluence,16,6.833769,2.955041,14.513678,15.663114,12.663564,11.592295,14.140299,13.673243,24.498687,28.192376,30.574070,0.158802
7,7,20250501_AS_MRC-5_Confluence,18,7.093223,2.870513,15.077184,16.250998,13.147020,11.803448,14.910346,14.217724,26.089190,29.794950,32.843234,0.276997
8,7,20250501_AS_MRC-5_Confluence,20,6.888428,2.892490,15.312537,16.701262,13.629345,12.192613,15.706223,14.997422,27.620944,31.557337,35.455337,0.307788
9,7,20250501_AS_MRC-5_Confluence,22,7.114184,2.889682,15.697972,17.304277,14.547110,12.503080,16.241288,15.153338,28.976128,33.228122,39.202628,0.318488
10,7,20250501_AS_MRC-5_Confluence,24,7.043401,2.784834,15.706726,18.308250,14.867510,13.275906,16.990774,16.021715,30.745917,35.986379,42.969710,0.329001
11,7,20250501_AS_MRC-5_Confluence,26,7.139073,2.996314,15.941221,19.144687,15.549277,13.764204,18.476716,16.570042,32.685780,38.913526,46.196868,0.424527
12,7,20250501_AS_MRC-5_Confluence,28,7.093455,2.887829,17.005857,20.338676,16.396787,14.667037,19.345536,17.273183,35.439527,41.242781,49.578534,0.297220
13,7,20250501_AS_MRC-5_Confluence,30,7.292493,2.901142,17.151882,21.379165,17.247280,15.170109,19.996725,18.322821,37.819241,44.190779,52.907136,0.303404
14,7,20250501_AS_MRC-5_Confluence,32,7.127322,2.867462,17.786262,22.367792,17.461505,15.760561,20.801661,19.033080,40.040660,46.775134,57.541587,0.289157
15,7,20250501_AS_MRC-5_Confluence,34,7.152953,2.987231,18.396651,23.323269,18.192991,16.106093,21.615245,19.792484,42.415426,50.199727,62.354924,0.340529
16,7,20250501_AS_MRC-5_Confluence,36,7.191244,3.066265,18.794678,24.265886,18.758360,16.628549,22.436169,20.593773,44.763987,53.574526,67.236806,0.341549
17,7,20250501_AS_MRC-5_Confluence,38,7.003007,3.081170,19.041909,25.765598,19.514713,17.127650,23.268856,21.724648,47.413199,56.894367,72.549106,0.298970
18,7,20250501_AS_MRC-5_Confluence,40,7.276172,3.122277,19.651001,27.126216,20.563183,17.514600,24.215760,22.470356,49.843220,60.848184,77.259016,0.244888
19,7,20250501_AS_MRC-5_Confluence,42,7.108125,3.106408,19.988933,28.387513,21.114210,18.039336,25.116767,23.582497,52.892119,64.002181,81.591387,0.280279
20,7,20250501_AS_MRC-5_Confluence,44,7.406867,3.141257,20.218720,29.530293,21.789444,17.905290,26.500164,24.815275,55.917066,68.235863,85.694881,0.299892
21,7,20250501_AS_MRC-5_Confluence,46,7.318559,3.232989,20.659485,31.384309,22.137868,18.540431,27.282976,26.017023,58.701072,71.438860,89.160121,0.253825
22,7,20250501_AS_MRC-5_Confluence,48,7.312016,3.353925,21.606390,32.479379,23.363889,19.457469,28.566824,26.729806,62.031098,75.319922,92.294649,0.559377
23,7,20250501_AS_MRC-5_Confluence,50,7.351744,3.278155,22.002919,34.026083,24.069323,19.713783,29.742497,27.851041,65.093145,78.896672,94.455588,0.353193
24,7,20250501_AS_MRC-5_Confluence,52,7.517814,3.492239,22.951266,35.492958,25.038771,20.295989,30.764722,28.722682,68.747506,82.099154,96.241727,0.437810
25,7,20250501_AS_MRC-5_Confluence,54,7.447288,3.389308,22.941377,37.630900,25.518721,21.075771,32.149631,29.754027,71.662587,85.048375,97.317188,0.438710
26,7,20250501_AS_MRC-5_Confluence,56,7.297820,3.659992,23.854822,39.279651,26.377534,21.434419,33.210824,30.341052,74.036942,87.466034,98.249726,0.243607
27,7,20250501_AS_MRC-5_Confluence,58,7.578564,3.699486,24.259579,41.603753,26.903033,22.172002,34.552458,31.843414,76.917636,90.062452,98.746564,0.477717
28,7,20250501_AS_MRC-5_Confluence,60,7.599479,3.775140,24.699758,43.021567,27.663163,22.723721,35.967931,33.127320,79.231081,92.130704,99.124316,0.412572
29,7,20250501_AS_MRC-5_Confluence,62,7.652002,3.827408,25.670362,44.315443,27.906919,23.547730,37.649197,34.429508,82.032280,93.376882,99.381728,0.400062
30,7,20250501_AS_MRC-5_Confluence,64,7.624346,3.512586,26.095171,46.561516,28.600074,23.880346,39.129451,35.626003,83.953146,94.674738,99.543118,0.253411
31,7,20250501_AS_MRC-5_Confluence,66,7.607456,3.905870,26.541943,48.581729,28.883517,24.746588,41.402196,37.170896,85.214528,95.741893,99.643644,0.283297
32,7,20250501_AS_MRC-5_Confluence,68,7.677176,3.899779,28.036558,49.860363,29.725897,24.786077,42.517554,38.447694,86.616714,96.373723,99.695084,0.226940
33,7,20250501_AS_MRC-5_Confluence,70,7.724665,3.743576,28.141597,52.032292,30.759186,25.117395,44.615344,40.523601,88.049174,97.199979,99.741053,0.319158
34,7,20250501_AS_MRC-5_Confluence,72,7.882025,3.984529,28.375281,53.709320,31.467178,26.044879,46.313840,41.700366,89.056394,97.618667,99.780027,0.370530

Wrote replaced data to: /Users/allielas/HTP_fibroblasts_mitolyso/proliferation_growth_curves/Incucyte_sheets/r7_processed.xlsx

In [ ]:
extra_plate_1 = "r0_2024-01-25"
extra_plate_2 = "r0_2024-03-01"

input_1= f"/Users/allielas/Desktop/Active Projects/Quality control/Incucyte_sheets/{extra_plate_1}.xlsx"
output_1= f"/Users/allielas/Desktop/Active Projects/Quality control/Incucyte_sheets/r{extra_plate_1}_processed.xlsx"
input_2= f"/Users/allielas/Desktop/Active Projects/Quality control/Incucyte_sheets/r{extra_plate_2}.xlsx"
output_2= f"/Users/allielas/Desktop/Active Projects/Quality control/Incucyte_sheets/r{extra_plate_2}_processed.xlsx"
make_average_excel_with_exclusions(input_1,output_1)
make_average_excel_with_exclusions(input_2,output_2)

Input file does not exist: /Users/allielas/Desktop/Active Projects/Quality control/Incucyte_sheets/r0_2024-01-25.xlsx

SystemExit: 2

/opt/homebrew/Caskroom/miniforge/base/envs/plotting/lib/python3.13/site-packages/IPython/core/interactiveshell.py:3707: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [ ]:
def load_mappings(path: Union[str, Path]):
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Mappings file not found: {path}")
    else:
        # assume CSV/TSV: first two columns are old,new
        df = pd.read_csv(p, dtype=str)
        if df.shape[1] < 2:
            raise ValueError("CSV mappings must have at least two columns (old, new).")
        old_col, new_col = df.columns[0], df.columns[1]
        return {
            str(o): str(n)
            for o, n in zip(df[old_col].fillna(""), df[new_col].fillna(""))
        }

def parse_inline_maps(map_args: List[str]):
    mappings = {}
    for s in map_args:
        if ":" not in s:
            raise ValueError(f"Inline mapping must be OLD:NEW, got: {s!r}")
        old, new = s.split(":", 1)
        mappings[old] = new
    return mappings


def apply_replacements(df: pd.DataFrame, mapping: Dict[str, str]):
    if not mapping:
        return df.copy()
    # For performance: compile mapping items once
    items = list(mapping.items())

    def replace_value(x):
        """
        Docstring for replace_value. Just a simple string replace

        :str x: the string to replace based on the dict
        """
        if isinstance(x, str):
            for old, new in items:
                if old:
                    x = x.replace(old, new)
            return x
        return x

    return df.applymap(replace_value)